//! C code generation from Concrete IR.
//!
//! This module translates the IR into C source code using a straightforward
//! basic-block to label+goto approach.

use crate::ir::{
    BasicBlock, BinOp, ConstKind, ConstValue, Function, Local, LocalKind, LogOp, Operand,
    Place, PlaceElem, Rvalue, StatementKind, TerminatorKind, Type, UnOp, ValueTree, IR,
};

use crate::codegen::errors::CodegenError;
use super::types::{
    generate_struct_def, mangle_fn_name, type_index_to_c, type_index_to_c_decl, type_to_c,
};

/// Generates the complete C source code for the given IR.
pub fn generate_c_code(ir: &IR) -> Result<String, CodegenError> {
    let mut output = String::new();

    // Generate header
    generate_header(&mut output);

    // Generate forward declarations for all structs
    generate_struct_forward_decls(&mut output, ir);

    // Generate struct definitions
    generate_struct_definitions(&mut output, ir);

    // Generate function forward declarations
    generate_function_forward_decls(&mut output, ir);

    // Generate function definitions
    for module_idx in &ir.top_level_modules {
        generate_module_functions(&mut output, ir, *module_idx)?;
    }

    Ok(output)
}

/// Generates the C file header with includes.
fn generate_header(output: &mut String) {
    output.push_str("/* Generated by Concrete C backend */\n");
    output.push_str("#include <stdint.h>\n");
    output.push_str("#include <stdbool.h>\n");
    output.push_str("#include <stddef.h>\n");
    output.push_str("#include <stdlib.h>\n");
    output.push_str("#include <string.h>\n");
    output.push_str("#include <stdio.h>\n");
    output.push_str("\n");
}

/// Generates forward declarations for all ADT types.
fn generate_struct_forward_decls(output: &mut String, ir: &IR) {
    use crate::ir::AdtKind;
    let mut has_decls = false;

    for (_, adt_opt) in ir.aggregates.iter() {
        if let Some(adt) = adt_opt {
            let mangled = super::types::mangle_type_name(&adt.name);
            match adt.kind {
                AdtKind::Struct => {
                    output.push_str(&format!("typedef struct {} {};\n", mangled, mangled));
                    has_decls = true;
                }
                AdtKind::Enum => {
                    // Enums use a tagged union, so forward declare as struct
                    output.push_str(&format!("typedef struct {} {};\n", mangled, mangled));
                    has_decls = true;
                }
                AdtKind::Union => {
                    output.push_str(&format!("typedef union {} {};\n", mangled, mangled));
                    has_decls = true;
                }
            }
        }
    }

    if has_decls {
        output.push('\n');
    }
}

/// Generates struct definitions.
fn generate_struct_definitions(output: &mut String, ir: &IR) {
    for (_, adt_opt) in ir.aggregates.iter() {
        if let Some(adt) = adt_opt {
            output.push_str(&generate_struct_def(adt, ir));
            output.push('\n');
        }
    }
}

/// Generates forward declarations for all functions.
fn generate_function_forward_decls(output: &mut String, ir: &IR) {
    for (_, func_opt) in ir.functions.iter() {
        if let Some(func) = func_opt {
            // Skip intrinsics - they're handled specially
            if func.is_intrinsic.is_some() {
                continue;
            }

            // Skip extern functions - they're either from libc (already declared in headers)
            // or will be linked from elsewhere
            if func.is_extern {
                continue;
            }

            let ret_ty = ir.types[func.ret_ty].as_ref().unwrap();
            let fn_name = mangle_fn_name(&func.name);
            // C requires main to return int
            let ret_type_str = if fn_name == "main" {
                "int".to_string()
            } else {
                type_to_c(ret_ty, ir)
            };

            output.push_str(&ret_type_str);
            output.push(' ');
            output.push_str(&fn_name);
            output.push('(');

            let params: Vec<&Local> = func.get_params();
            if params.is_empty() {
                output.push_str("void");
            } else {
                for (i, param) in params.iter().enumerate() {
                    if i > 0 {
                        output.push_str(", ");
                    }
                    let param_ty = ir.types[param.ty].as_ref().unwrap();
                    // C requires main's first parameter to be int (argc)
                    let (base_type, suffix) = if fn_name == "main" && i == 0 {
                        ("int".to_string(), String::new())
                    } else {
                        super::types::type_to_c_decl(param_ty, ir)
                    };
                    let param_name = param
                        .debug_name
                        .clone()
                        .unwrap_or_else(|| format!("_arg{}", i));
                    output.push_str(&format!("{} {}{}", base_type, param_name, suffix));
                }
            }

            output.push_str(");\n");
        }
    }

    output.push('\n');
}

/// Generates functions for a module and its submodules.
fn generate_module_functions(
    output: &mut String,
    ir: &IR,
    module_idx: crate::ir::ModuleIndex,
) -> Result<(), CodegenError> {
    let module = &ir.modules[module_idx];

    // Generate functions in this module
    for fn_idx in &module.functions {
        if let Some(func) = ir.functions[*fn_idx].as_ref() {
            // Skip if function is defined in a different module
            if func.module_idx != module_idx {
                continue;
            }
            generate_function(output, ir, func)?;
        }
    }

    // Recurse into submodules
    for sub_module_idx in module.modules.values() {
        generate_module_functions(output, ir, *sub_module_idx)?;
    }

    Ok(())
}

/// Generates C code for a single function.
fn generate_function(output: &mut String, ir: &IR, func: &Function) -> Result<(), CodegenError> {
    // Skip extern functions (declaration only)
    if func.is_extern {
        return Ok(());
    }

    // Skip intrinsics - they're handled specially at call sites
    if func.is_intrinsic.is_some() {
        return Ok(());
    }

    // Skip functions with no body (polymorphic placeholders)
    if func.basic_blocks.is_empty() {
        return Ok(());
    }

    let ret_ty = ir.types[func.ret_ty].as_ref().unwrap();
    let fn_name = mangle_fn_name(&func.name);
    // C requires main to return int
    let ret_type_str = if fn_name == "main" {
        "int".to_string()
    } else {
        type_to_c(ret_ty, ir)
    };

    // Function signature
    output.push_str(&ret_type_str);
    output.push(' ');
    output.push_str(&fn_name);
    output.push('(');

    let params: Vec<&Local> = func.get_params();
    if params.is_empty() {
        output.push_str("void");
    } else {
        for (i, param) in params.iter().enumerate() {
            if i > 0 {
                output.push_str(", ");
            }
            let param_ty = ir.types[param.ty].as_ref().unwrap();
            // C requires main's first parameter to be int (argc)
            let (base_type, suffix) = if fn_name == "main" && i == 0 {
                ("int".to_string(), String::new())
            } else {
                super::types::type_to_c_decl(param_ty, ir)
            };
            let param_name = param
                .debug_name
                .clone()
                .unwrap_or_else(|| format!("_arg{}", i));
            output.push_str(&format!("{} {}{}", base_type, param_name, suffix));
        }
    }

    output.push_str(") {\n");

    // Generate local variable declarations
    generate_local_declarations(output, ir, func);

    // Generate basic blocks
    for (block_idx, block) in func.basic_blocks.iter().enumerate() {
        generate_basic_block(output, ir, func, block_idx, block)?;
    }

    output.push_str("}\n\n");

    Ok(())
}

/// Generates local variable declarations at the start of the function.
fn generate_local_declarations(output: &mut String, ir: &IR, func: &Function) {
    // Find the return local (if any)
    let mut return_local_idx = None;

    for (idx, local) in func.locals.iter().enumerate() {
        match local.kind {
            LocalKind::ReturnPointer => {
                let ty = ir.types[local.ty].as_ref().unwrap();
                if !matches!(ty, Type::Unit) {
                    return_local_idx = Some(idx);
                    let (base_type, suffix) = type_index_to_c_decl(local.ty, ir);
                    output.push_str(&format!("    {} _{}{};  /* return value */\n", base_type, idx, suffix));
                }
            }
            LocalKind::Arg => {
                // Arguments are already declared as parameters, but we may need
                // to create local copies if the parameter is modified
                // For now, we'll use the parameter names directly
            }
            LocalKind::Temp => {
                // Skip void (Unit) type locals - they can't be declared in C
                let ty = ir.types[local.ty].as_ref().unwrap();
                if matches!(ty, Type::Unit) {
                    continue;
                }
                let (base_type, suffix) = type_index_to_c_decl(local.ty, ir);
                let comment = local
                    .debug_name
                    .as_ref()
                    .map(|n| format!("  /* {} */", n))
                    .unwrap_or_default();
                output.push_str(&format!("    {} _{}{};{}\n", base_type, idx, suffix, comment));
            }
        }
    }

    if return_local_idx.is_some() || func.locals.iter().any(|l| matches!(l.kind, LocalKind::Temp)) {
        output.push('\n');
    }
}

/// Generates C code for a basic block.
fn generate_basic_block(
    output: &mut String,
    ir: &IR,
    func: &Function,
    block_idx: usize,
    block: &BasicBlock,
) -> Result<(), CodegenError> {
    // Label for this block
    output.push_str(&format!("bb{}:\n", block_idx));

    // Generate statements
    for stmt in &block.statements {
        match &stmt.kind {
            StatementKind::Assign(place, rvalue) => {
                // Skip assignments to void type locals
                let local = &func.locals[place.local];
                let ty = ir.types[local.ty].as_ref().unwrap();
                if matches!(ty, Type::Unit) {
                    continue;
                }

                // Determine the actual type of the place (after projections)
                let place_ty = get_place_type(ir, func, place);
                let place_str = generate_place(ir, func, place, false);
                let rvalue_str = generate_rvalue(ir, func, rvalue)?;

                // Use memcpy for array assignments since C doesn't allow direct array assignment
                if matches!(place_ty, Type::Array(_, _)) {
                    output.push_str(&format!(
                        "    memcpy({}, {}, sizeof({}));\n",
                        place_str, rvalue_str, place_str
                    ));
                } else {
                    output.push_str(&format!("    {} = {};\n", place_str, rvalue_str));
                }
            }
            StatementKind::StorageLive(_) | StatementKind::StorageDead(_) => {
                // No-op in C - variables are declared at function start
            }
        }
    }

    // Generate terminator
    generate_terminator(output, ir, func, &block.terminator.kind)?;

    Ok(())
}

/// Gets the type of a place after applying all projections.
fn get_place_type<'a>(ir: &'a IR, func: &Function, place: &Place) -> &'a Type {
    let local = &func.locals[place.local];
    let mut current_ty = ir.types[local.ty].as_ref().unwrap();

    for proj in &place.projection {
        match proj {
            PlaceElem::Deref => {
                if let Some(inner_idx) = current_ty.get_inner_type() {
                    current_ty = ir.types[inner_idx].as_ref().unwrap();
                }
            }
            PlaceElem::Field(field_idx) => {
                if let Type::Adt(adt_idx) = current_ty {
                    let adt = ir.aggregates[*adt_idx].as_ref().unwrap();
                    let variant = adt.variants.first().unwrap();
                    let field = &variant.fields[*field_idx];
                    current_ty = ir.types[field.ty].as_ref().unwrap();
                }
            }
            PlaceElem::Index(_) | PlaceElem::ConstantIndex(_) => {
                if let Some(inner_idx) = current_ty.get_inner_type() {
                    current_ty = ir.types[inner_idx].as_ref().unwrap();
                }
            }
        }
    }

    current_ty
}

/// Generates the C representation of a place (lvalue).
fn generate_place(ir: &IR, func: &Function, place: &Place, as_address: bool) -> String {
    let local = &func.locals[place.local];

    // Get the base name
    let base_name = match local.kind {
        LocalKind::Arg => {
            local
                .debug_name
                .as_ref()
                .map(|s| s.clone())
                .unwrap_or_else(|| format!("_arg{}", place.local))
        }
        _ => format!("_{}", place.local),
    };

    if place.projection.is_empty() {
        if as_address {
            return format!("&{}", base_name);
        }
        return base_name;
    }

    // Apply projections
    let mut result = base_name;
    let mut current_ty_idx = local.ty;
    let mut is_pointer = false;

    for proj in &place.projection {
        match proj {
            PlaceElem::Deref => {
                let ty = ir.types[current_ty_idx].as_ref().unwrap();
                if let Some(inner_idx) = ty.get_inner_type() {
                    let inner_ty = ir.types[inner_idx].as_ref().unwrap();
                    // If dereferencing a reference to an array, don't add (*) because
                    // in C the array reference is already a pointer that can be indexed
                    if !matches!(inner_ty, Type::Array(_, _)) {
                        result = format!("(*{})", result);
                    }
                    current_ty_idx = inner_idx;
                } else {
                    result = format!("(*{})", result);
                }
                is_pointer = false;
            }
            PlaceElem::Field(field_idx) => {
                let ty = ir.types[current_ty_idx].as_ref().unwrap();
                if let Type::Adt(adt_idx) = ty {
                    let adt = ir.aggregates[*adt_idx].as_ref().unwrap();
                    let variant = adt.variants.first().unwrap();
                    let field = &variant.fields[*field_idx];
                    if is_pointer {
                        result = format!("{}->{}", result, field.name);
                    } else {
                        result = format!("{}.{}", result, field.name);
                    }
                    current_ty_idx = field.ty;
                    is_pointer = false;
                }
            }
            PlaceElem::Index(idx_local) => {
                let idx_name = format!("_{}", idx_local);
                result = format!("{}[{}]", result, idx_name);
                let ty = ir.types[current_ty_idx].as_ref().unwrap();
                if let Some(inner) = ty.get_inner_type() {
                    current_ty_idx = inner;
                }
            }
            PlaceElem::ConstantIndex(idx) => {
                result = format!("{}[{}]", result, idx);
                let ty = ir.types[current_ty_idx].as_ref().unwrap();
                if let Some(inner) = ty.get_inner_type() {
                    current_ty_idx = inner;
                }
            }
        }
    }

    if as_address {
        format!("&{}", result)
    } else {
        result
    }
}

/// Generates the C representation of an rvalue (expression).
fn generate_rvalue(ir: &IR, func: &Function, rvalue: &Rvalue) -> Result<String, CodegenError> {
    Ok(match rvalue {
        Rvalue::Use(operand) => generate_operand(ir, func, operand),
        Rvalue::LogicOp(op, (lhs, rhs)) => {
            let lhs_str = generate_operand(ir, func, lhs);
            let rhs_str = generate_operand(ir, func, rhs);
            let op_str = match op {
                LogOp::And => "&&",
                LogOp::Or => "||",
            };
            format!("({} {} {})", lhs_str, op_str, rhs_str)
        }
        Rvalue::BinaryOp(op, (lhs, rhs)) => {
            let lhs_str = generate_operand(ir, func, lhs);
            let rhs_str = generate_operand(ir, func, rhs);
            let op_str = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::BitXor => "^",
                BinOp::BitAnd => "&",
                BinOp::BitOr => "|",
                BinOp::Shl => "<<",
                BinOp::Shr => ">>",
                BinOp::Eq => "==",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Ne => "!=",
                BinOp::Ge => ">=",
                BinOp::Gt => ">",
            };
            format!("({} {} {})", lhs_str, op_str, rhs_str)
        }
        Rvalue::UnaryOp(op, operand) => {
            let operand_str = generate_operand(ir, func, operand);
            let op_str = match op {
                UnOp::Not => "!",
                UnOp::Neg => "-",
            };
            format!("({}{})", op_str, operand_str)
        }
        Rvalue::Ref(_mutability, place) => {
            generate_place(ir, func, place, true)
        }
        Rvalue::Cast(operand, target_ty_idx, _span) => {
            let operand_str = generate_operand(ir, func, operand);
            let target_ty = type_index_to_c(*target_ty_idx, ir);
            format!("(({}){})", target_ty, operand_str)
        }
    })
}

/// Generates the C representation of an operand.
fn generate_operand(ir: &IR, func: &Function, operand: &Operand) -> String {
    match operand {
        Operand::Place(place) => generate_place(ir, func, place, false),
        Operand::Const(const_data) => generate_const_value(ir, &const_data.data),
    }
}

/// Generates the C representation of a constant value.
fn generate_const_value(ir: &IR, const_kind: &ConstKind) -> String {
    match const_kind {
        ConstKind::Value(value_tree) => generate_value_tree(ir, value_tree),
        ConstKind::Expr(_) => {
            // Constant expressions should be evaluated before codegen
            todo!("Constant expressions not yet supported in C backend")
        }
    }
}

/// Generates the C representation of a value tree.
fn generate_value_tree(ir: &IR, value_tree: &ValueTree) -> String {
    match value_tree {
        ValueTree::Leaf(const_value) => match const_value {
            ConstValue::Bool(b) => if *b { "1" } else { "0" }.to_string(),
            ConstValue::Char(c) => {
                let ch = *c as char;
                // Escape special characters for C
                match ch {
                    '\n' => "'\\n'".to_string(),
                    '\r' => "'\\r'".to_string(),
                    '\t' => "'\\t'".to_string(),
                    '\\' => "'\\\\'".to_string(),
                    '\'' => "'\\''".to_string(),
                    '\0' => "'\\0'".to_string(),
                    _ if ch.is_ascii_control() => format!("'\\x{:02x}'", *c),
                    _ => format!("'{}'", ch),
                }
            }
            ConstValue::I8(v) => format!("((int8_t){})", v),
            ConstValue::I16(v) => format!("((int16_t){})", v),
            ConstValue::I32(v) => v.to_string(),
            ConstValue::I64(v) => format!("{}LL", v),
            ConstValue::I128(v) => format!("((__int128){}LL)", v),
            ConstValue::U8(v) => format!("((uint8_t){}u)", v),
            ConstValue::U16(v) => format!("((uint16_t){}u)", v),
            ConstValue::U32(v) => format!("{}u", v),
            ConstValue::U64(v) => format!("{}uLL", v),
            ConstValue::U128(v) => format!("((unsigned __int128){}uLL)", v),
            ConstValue::F32(v) => format!("{}f", v),
            ConstValue::F64(v) => v.clone(),
        },
        ValueTree::Branch(values) => {
            // Array or struct initializer
            let elements: Vec<String> = values.iter().map(|v| generate_value_tree(ir, v)).collect();
            format!("{{ {} }}", elements.join(", "))
        }
    }
}

/// Generates C code for a terminator.
fn generate_terminator(
    output: &mut String,
    ir: &IR,
    func: &Function,
    terminator: &TerminatorKind,
) -> Result<(), CodegenError> {
    match terminator {
        TerminatorKind::Goto { target } => {
            output.push_str(&format!("    goto bb{};\n", target));
        }
        TerminatorKind::Return => {
            // Find the return local
            let return_local = func
                .locals
                .iter()
                .enumerate()
                .find(|(_, l)| matches!(l.kind, LocalKind::ReturnPointer));

            if let Some((idx, local)) = return_local {
                let ty = ir.types[local.ty].as_ref().unwrap();
                if !matches!(ty, Type::Unit) {
                    output.push_str(&format!("    return _{};\n", idx));
                } else {
                    output.push_str("    return;\n");
                }
            } else {
                output.push_str("    return;\n");
            }
        }
        TerminatorKind::Unreachable => {
            output.push_str("    __builtin_unreachable();\n");
        }
        TerminatorKind::Call {
            func: fn_idx,
            args,
            destination,
            target,
        } => {
            let called_func = ir.functions[*fn_idx].as_ref().unwrap();

            // Check if it's an intrinsic
            if let Some(intrinsic) = &called_func.is_intrinsic {
                let intrinsic_result = match intrinsic {
                    crate::ir::ConcreteIntrinsic::SizeOf(type_idx) => {
                        let ty = type_index_to_c(*type_idx, ir);
                        format!("sizeof({})", ty)
                    }
                    crate::ir::ConcreteIntrinsic::AlignOf(type_idx) => {
                        let ty = type_index_to_c(*type_idx, ir);
                        format!("_Alignof({})", ty)
                    }
                };
                let dest_str = generate_place(ir, func, destination, false);
                output.push_str(&format!("    {} = {};\n", dest_str, intrinsic_result));
            } else {
                // Regular function call
                let fn_name = mangle_fn_name(&called_func.name);
                let args_str: Vec<String> = args
                    .iter()
                    .map(|arg| generate_rvalue(ir, func, arg))
                    .collect::<Result<Vec<_>, _>>()?;

                let dest_str = generate_place(ir, func, destination, false);
                let ret_ty = ir.types[called_func.ret_ty].as_ref().unwrap();

                if matches!(ret_ty, Type::Unit) {
                    output.push_str(&format!("    {}({});\n", fn_name, args_str.join(", ")));
                } else {
                    output.push_str(&format!(
                        "    {} = {}({});\n",
                        dest_str,
                        fn_name,
                        args_str.join(", ")
                    ));
                }
            }

            // Jump to target block if function returns
            if let Some(target_block) = target {
                output.push_str(&format!("    goto bb{};\n", target_block));
            }
        }
        TerminatorKind::SwitchInt {
            discriminator,
            targets,
        } => {
            let disc_str = generate_operand(ir, func, discriminator);

            // For simple boolean switches (common case for if/else)
            if targets.values.len() == 1 {
                let value = value_tree_to_int(&targets.values[0]);
                // targets[0] is the match case, targets[1] is the default/otherwise
                if value == Some(0) {
                    // if (!disc) goto targets[0]; else goto targets[1];
                    output.push_str(&format!(
                        "    if ({}) goto bb{}; else goto bb{};\n",
                        disc_str, targets.targets[1], targets.targets[0]
                    ));
                } else {
                    output.push_str(&format!(
                        "    if ({} == {}) goto bb{}; else goto bb{};\n",
                        disc_str,
                        value.unwrap_or(0),
                        targets.targets[0],
                        targets.targets[1]
                    ));
                }
            } else {
                // General switch
                output.push_str(&format!("    switch ({}) {{\n", disc_str));

                for (value, target) in targets.values.iter().zip(targets.targets.iter()) {
                    if let Some(v) = value_tree_to_int(value) {
                        output.push_str(&format!(
                            "        case {}: goto bb{};\n",
                            v, target
                        ));
                    }
                }

                // Default case (last target)
                let default_target = targets.targets.last().unwrap();
                output.push_str(&format!(
                    "        default: goto bb{};\n",
                    default_target
                ));

                output.push_str("    }\n");
            }
        }
    }

    Ok(())
}

/// Converts a ValueTree to an integer value if possible.
fn value_tree_to_int(value: &ValueTree) -> Option<i128> {
    match value {
        ValueTree::Leaf(const_value) => match const_value {
            ConstValue::Bool(b) => Some(if *b { 1 } else { 0 }),
            ConstValue::Char(c) => Some(*c as i128),
            ConstValue::I8(v) => Some(*v as i128),
            ConstValue::I16(v) => Some(*v as i128),
            ConstValue::I32(v) => Some(*v as i128),
            ConstValue::I64(v) => Some(*v as i128),
            ConstValue::I128(v) => Some(*v),
            ConstValue::U8(v) => Some(*v as i128),
            ConstValue::U16(v) => Some(*v as i128),
            ConstValue::U32(v) => Some(*v as i128),
            ConstValue::U64(v) => Some(*v as i128),
            ConstValue::U128(v) => Some(*v as i128),
            _ => None,
        },
        _ => None,
    }
}
