/* Generated by Concrete C backend */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

typedef struct A A;

struct A {
    int32_t a;
    int32_t b;
};

int main(void);
int32_t ImplBlockMut_hello_1(A* self, int32_t other);
void ImplBlockMut_set_a_2(A* self, int32_t value);

int main(void) {
    int32_t _0;  /* return value */
    A _1;  /* x */
    A _2;

bb0:
    _2.a = 2;
    _2.b = 3;
    _1 = _2;
    ImplBlockMut_set_a_2(&_1, 4);
    goto bb1;
bb1:
    _0 = _1.a;
    return _0;
bb2:
    return _0;
}

int32_t ImplBlockMut_hello_1(A* self, int32_t other) {
    int32_t _0;  /* return value */
    int32_t _3;
    int32_t _4;

bb0:
    _3 = (*self).a;
    _4 = other;
    _0 = (_3 * _4);
    return _0;
bb1:
    return _0;
}

void ImplBlockMut_set_a_2(A* self, int32_t value) {
bb0:
    (*self).a = value;
    return;
bb1:
    return;
}

