use std::num::NonZero;

#[derive(Debug)]
pub struct Cst {
    nodes: Vec<CstNode>,
}

#[derive(Debug)]
enum CstNode {
    /// An offset to a token from the token stream. The token type may be deduced by the context.
    Token(usize),

    /// A reference to a rule with a kind and number of children (never zero).
    Rule(NodeKind, NonZero<usize>),
}

#[derive(Debug)]
enum NodeKind {
    // TODO: Autogenerated.
}
