base_url = "https://unbalancedparentheses.github.io/concrete2"
title = "Concrete"
description = "An LL(1), linear, capability-oriented systems language for auditable and formally verifiable code"
compile_sass = false
build_search_index = true
generate_feeds = false
minify_html = true

[markdown]
smart_punctuation = true

[extra]
repo_url = "https://github.com/unbalancedparentheses/concrete2"
