; Generated by Concrete compiler (SSA path)
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx14.0.0"
%struct.String = type { ptr, i64, i64 }
%struct.Vec = type { ptr, i64, i64 }
%variant.Option.Some = type { i64 }
%variant.Option.None = type {}
%enum.Option = type { i32, [12 x i8] }
%variant.Result.Ok = type { i64 }
%variant.Result.Err = type { i64 }
%enum.Result = type { i32, [12 x i8] }
%struct.Config = type { i32, i32, i32 }
%struct.BatchStats = type { i32, i32, i32, i32, i32 }
%variant.ParseError.Empty = type {}
%variant.ParseError.Overflow = type {}
%variant.ParseError.InvalidFormat = type {}
%enum.ParseError = type { i32, [1 x i8] }
%variant.ValidResult.Good = type { i32 }
%variant.ValidResult.Bad = type { %enum.ParseError }
%enum.ValidResult = type { i32, [4 x i8] }
%variant.PipelineResult.Success = type { %struct.BatchStats }
%variant.PipelineResult.Failure = type { %enum.ParseError }
%enum.PipelineResult = type { i32, [20 x i8] }
@__concrete_argc = private global i32 0
@__concrete_argv = private global ptr null
@fmt.main = private constant [6 x i8] c"%lld\0A\00"
@.fmt_ld = private constant [4 x i8] c"%ld\00"
@.fmt_str = private constant [5 x i8] c"%.*s\00"
@.str_true = private constant [5 x i8] c"true\00"
@.str_false = private constant [6 x i8] c"false\00"
@.fmt_f = private constant [3 x i8] c"%g\00"
declare ptr @malloc(i64)
declare void @free(ptr)
declare ptr @realloc(ptr, i64)
declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
declare i64 @write(i32, ptr, i64)
declare void @abort()
declare i32 @printf(ptr, ...)
declare i64 @strlen(ptr)
declare ptr @memset(ptr, i32, i64)
declare i32 @memcmp(ptr, ptr, i64)
declare i32 @snprintf(ptr, i64, ptr, ...)
declare i64 @strtol(ptr, ptr, i32)
declare i64 @llvm.smax.i64(i64, i64)
declare i64 @llvm.smin.i64(i64, i64)
declare i32 @clock_gettime(i32, ptr)
declare i32 @putchar(i32)
define %enum.ValidResult @validate_config(ptr %cfg) {
entry:
  %t5 = alloca %enum.ValidResult
  %t7 = alloca %enum.ParseError
  %t15 = alloca %enum.ValidResult
  %t17 = alloca %enum.ParseError
  %t22 = alloca %enum.ValidResult
  %t0 = getelementptr i8, ptr %cfg, i64 4
  %t1 = load i32, ptr %t0
  %t3 = load i32, ptr %cfg
  %t4 = icmp sge i32 %t1, %t3
  br i1 %t4, label %then0, label %merge2
then0:
  store i32 1, ptr %t5
  %t6 = getelementptr i8, ptr %t5, i64 4
  store i32 2, ptr %t7
  %t9 = load %enum.ParseError, ptr %t7
  store %enum.ParseError %t9, ptr %t6
  %t11 = load %enum.ValidResult, ptr %t5
  ret %enum.ValidResult %t11
merge2:
  %t12 = getelementptr i8, ptr %cfg, i64 8
  %t13 = load i32, ptr %t12
  %t14 = icmp sle i32 %t13, 0
  br i1 %t14, label %then3, label %merge5
then3:
  store i32 1, ptr %t15
  %t16 = getelementptr i8, ptr %t15, i64 4
  store i32 1, ptr %t17
  %t19 = load %enum.ParseError, ptr %t17
  store %enum.ParseError %t19, ptr %t16
  %t21 = load %enum.ValidResult, ptr %t15
  ret %enum.ValidResult %t21
merge5:
  store i32 0, ptr %t22
  %t23 = getelementptr i8, ptr %t22, i64 4
  store i32 1, ptr %t23
  %t25 = load %enum.ValidResult, ptr %t22
  ret %enum.ValidResult %t25
}

define %enum.ValidResult @validate_and_scale(i32 %val, ptr %cfg) {
entry:
  %t3 = alloca %enum.ValidResult
  %t5 = alloca %enum.ParseError
  %t13 = alloca %enum.ValidResult
  %t15 = alloca %enum.ParseError
  %t20 = alloca %enum.ValidResult
  %t0 = getelementptr i8, ptr %cfg, i64 4
  %t1 = load i32, ptr %t0
  %t2 = icmp slt i32 %val, %t1
  br i1 %t2, label %then0, label %merge2
then0:
  store i32 1, ptr %t3
  %t4 = getelementptr i8, ptr %t3, i64 4
  store i32 1, ptr %t5
  %t7 = load %enum.ParseError, ptr %t5
  store %enum.ParseError %t7, ptr %t4
  %t9 = load %enum.ValidResult, ptr %t3
  ret %enum.ValidResult %t9
merge2:
  %t11 = load i32, ptr %cfg
  %t12 = icmp sgt i32 %val, %t11
  br i1 %t12, label %then3, label %merge5
then3:
  store i32 1, ptr %t13
  %t14 = getelementptr i8, ptr %t13, i64 4
  store i32 1, ptr %t15
  %t17 = load %enum.ParseError, ptr %t15
  store %enum.ParseError %t17, ptr %t14
  %t19 = load %enum.ValidResult, ptr %t13
  ret %enum.ValidResult %t19
merge5:
  store i32 0, ptr %t20
  %t21 = getelementptr i8, ptr %t20, i64 4
  %t22 = getelementptr i8, ptr %cfg, i64 8
  %t23 = load i32, ptr %t22
  %t24 = mul i32 %val, %t23
  store i32 %t24, ptr %t21
  %t26 = load %enum.ValidResult, ptr %t20
  ret %enum.ValidResult %t26
}

define %enum.ValidResult @process_value(i32 %val, ptr %cfg) {
entry:
  %ssa.t0 = alloca %enum.ValidResult
  %ssa.t1 = alloca %enum.ValidResult
  %t8 = alloca %enum.ValidResult
  %borrow.16 = alloca %struct.Config
  %t0 = call %enum.ValidResult @validate_config(ptr %cfg)
  store %enum.ValidResult %t0, ptr %ssa.t0
  %t2 = load i32, ptr %ssa.t0
  %t3 = sext i32 %t2 to i64
  %t4 = icmp eq i64 %t3, 1
  br i1 %t4, label %arm01, label %check12
arm01:
  store %enum.ValidResult %t0, ptr %ssa.t1
  %t5 = getelementptr i8, ptr %ssa.t1, i64 4
  %t7 = load %enum.ParseError, ptr %t5
  store i32 1, ptr %t8
  %t9 = getelementptr i8, ptr %t8, i64 4
  store %enum.ParseError %t7, ptr %t9
  %t11 = load %enum.ValidResult, ptr %t8
  ret %enum.ValidResult %t11
check12:
  %t12 = icmp eq i64 %t3, 0
  br i1 %t12, label %merge0, label %check24
check24:
  unreachable
merge0:
  call void @llvm.memcpy.p0.p0.i64(ptr %borrow.16, ptr %cfg, i64 12, i1 false)
  %t17 = call %enum.ValidResult @validate_and_scale(i32 %val, ptr %borrow.16)
  ret %enum.ValidResult %t17
}

define %struct.Vec @process_batch(ptr %values, ptr %cfg) {
entry:
  %agg.2 = alloca %struct.Config
  %agg.3 = alloca %struct.Vec
  %mutref.19 = alloca %struct.Vec
  %ssa.t3 = alloca %struct.Config
  %ssa.t4 = alloca %enum.ValidResult
  %ssa.t5 = alloca %enum.ValidResult
  %ssa.t6 = alloca i32
  %t0 = call %struct.Vec @vec_new_4()
  %t1 = call i64 @vec_len(ptr %values)
  call void @llvm.memcpy.p0.p0.i64(ptr %agg.2, ptr %cfg, i64 12, i1 false)
  store %struct.Vec %t0, ptr %agg.3
  br label %while.hdr0
while.hdr0:
  %phi.6 = phi i64 [0, %entry], [%t25, %merge3]
  %t7 = icmp slt i64 %phi.6, %t1
  br i1 %t7, label %while.body1, label %while.exit2
while.body1:
  %ssa.t2 = call ptr @vec_get_4(ptr %values, i64 %phi.6)
  %t8 = load i32, ptr %ssa.t2
  %pload.9 = load %struct.Config, ptr %agg.2
  store %struct.Config %pload.9, ptr %ssa.t3
  %t10 = call %enum.ValidResult @process_value(i32 %t8, ptr %ssa.t3)
  store %enum.ValidResult %t10, ptr %ssa.t4
  %t12 = load i32, ptr %ssa.t4
  %t13 = sext i32 %t12 to i64
  %t14 = icmp eq i64 %t13, 0
  br i1 %t14, label %arm04, label %check15
arm04:
  store %enum.ValidResult %t10, ptr %ssa.t5
  %t15 = getelementptr i8, ptr %ssa.t5, i64 4
  %t17 = load i32, ptr %t15
  %pload.18 = load %struct.Vec, ptr %agg.3
  store %struct.Vec %pload.18, ptr %mutref.19
  store i32 %t17, ptr %ssa.t6
  call void @vec_push_4(ptr %mutref.19, ptr %ssa.t6)
  %wb.20 = load %struct.Vec, ptr %mutref.19
  store %struct.Vec %wb.20, ptr %agg.3
  br label %merge3
check15:
  %t21 = icmp eq i64 %t13, 1
  br i1 %t21, label %merge3, label %check27
check27:
  unreachable
merge3:
  %t25 = add i64 %phi.6, 1
  br label %while.hdr0
while.exit2:
  %unpro.27 = load %struct.Vec, ptr %agg.3
  ret %struct.Vec %unpro.27
}

define i32 @find_first_exceeding(ptr %values, i32 %threshold) {
entry:
  %t0 = call i64 @vec_len(ptr %values)
  %t1 = sub i32 0, 1
  br label %while.hdr0
while.hdr0:
  %phi.6 = phi i64 [0, %entry], [%t10, %merge5]
  %t7 = icmp slt i64 %phi.6, %t0
  br i1 %t7, label %while.body1, label %while.exit2
while.body1:
  %ssa.t7 = call ptr @vec_get_4(ptr %values, i64 %phi.6)
  %t8 = load i32, ptr %ssa.t7
  %t9 = icmp sgt i32 %t8, %threshold
  br i1 %t9, label %then3, label %merge5
then3:
  br label %while.exit2
merge5:
  %t10 = add i64 %phi.6, 1
  br label %while.hdr0
while.exit2:
  %exit.11 = phi i32 [%t1, %while.hdr0], [%t8, %then3]
  ret i32 %exit.11
}

define i32 @count_in_range(ptr %values, i32 %lo, i32 %hi) {
entry:
  %t0 = call i64 @vec_len(ptr %values)
  br label %while.hdr0
while.hdr0:
  %phi.5 = phi i32 [0, %entry], [%t12, %merge8], [%phi.5, %then3], [%phi.5, %then6]
  %phi.6 = phi i64 [0, %entry], [%t9, %merge8], [%t9, %then3], [%t9, %then6]
  %t7 = icmp slt i64 %phi.6, %t0
  br i1 %t7, label %while.body1, label %while.exit2
while.body1:
  %ssa.t8 = call ptr @vec_get_4(ptr %values, i64 %phi.6)
  %t8 = load i32, ptr %ssa.t8
  %t9 = add i64 %phi.6, 1
  %t10 = icmp slt i32 %t8, %lo
  br i1 %t10, label %then3, label %merge5
then3:
  br label %while.hdr0
merge5:
  %t11 = icmp sgt i32 %t8, %hi
  br i1 %t11, label %then6, label %merge8
then6:
  br label %while.hdr0
merge8:
  %t12 = add i32 %phi.5, 1
  br label %while.hdr0
while.exit2:
  ret i32 %phi.5
}

define i32 @sum_values(ptr %values) {
entry:
  %t0 = call i64 @vec_len(ptr %values)
  br label %while.hdr0
while.hdr0:
  %phi.3 = phi i32 [0, %entry], [%t7, %while.body1]
  %phi.4 = phi i64 [0, %entry], [%t8, %while.body1]
  %t5 = icmp slt i64 %phi.4, %t0
  br i1 %t5, label %while.body1, label %while.exit2
while.body1:
  %ssa.t9 = call ptr @vec_get_4(ptr %values, i64 %phi.4)
  %t6 = load i32, ptr %ssa.t9
  %t7 = add i32 %phi.3, %t6
  %t8 = add i64 %phi.4, 1
  br label %while.hdr0
while.exit2:
  ret i32 %phi.3
}

define i32 @process_with_cleanup(i32 %n, ptr %cfg) {
entry:
  %agg.1 = alloca %struct.Config
  %agg.2 = alloca %struct.Vec
  %mutref.7 = alloca %struct.Vec
  %ssa.t10 = alloca i32
  %borrow.13 = alloca %struct.Vec
  %ssa.t11 = alloca %struct.Config
  %borrow.15 = alloca %struct.Vec
  %ssa.t12 = alloca %struct.Vec
  %ssa.t13 = alloca %struct.Vec
  %t0 = call %struct.Vec @vec_new_4()
  call void @llvm.memcpy.p0.p0.i64(ptr %agg.1, ptr %cfg, i64 12, i1 false)
  store %struct.Vec %t0, ptr %agg.2
  br label %while.hdr0
while.hdr0:
  %phi.4 = phi i32 [0, %entry], [%t10, %while.body1]
  %t5 = icmp slt i32 %phi.4, %n
  br i1 %t5, label %while.body1, label %while.exit2
while.body1:
  %pload.6 = load %struct.Vec, ptr %agg.2
  store %struct.Vec %pload.6, ptr %mutref.7
  %t8 = mul i32 %phi.4, 3
  store i32 %t8, ptr %ssa.t10
  call void @vec_push_4(ptr %mutref.7, ptr %ssa.t10)
  %wb.9 = load %struct.Vec, ptr %mutref.7
  store %struct.Vec %wb.9, ptr %agg.2
  %t10 = add i32 %phi.4, 1
  br label %while.hdr0
while.exit2:
  %unpro.11 = load %struct.Config, ptr %agg.1
  %unpro.12 = load %struct.Vec, ptr %agg.2
  store %struct.Vec %unpro.12, ptr %borrow.13
  store %struct.Config %unpro.11, ptr %ssa.t11
  %t14 = call %struct.Vec @process_batch(ptr %borrow.13, ptr %ssa.t11)
  store %struct.Vec %t14, ptr %borrow.15
  %t16 = call i64 @vec_len(ptr %borrow.15)
  %t17 = trunc i64 %t16 to i32
  store %struct.Vec %unpro.12, ptr %ssa.t12
  call void @vec_free(ptr %ssa.t12)
  store %struct.Vec %t14, ptr %ssa.t13
  call void @vec_free(ptr %ssa.t13)
  ret i32 %t17
}

define %enum.PipelineResult @run_pipeline(ptr %cfg) {
entry:
  %mutref.17 = alloca %struct.Vec
  %mutref.19 = alloca %struct.Vec
  %mutref.21 = alloca %struct.Vec
  %mutref.23 = alloca %struct.Vec
  %mutref.25 = alloca %struct.Vec
  %mutref.27 = alloca %struct.Vec
  %mutref.29 = alloca %struct.Vec
  %mutref.32 = alloca %struct.Vec
  %ssa.t14 = alloca %enum.ValidResult
  %ssa.t15 = alloca %enum.ValidResult
  %t8 = alloca %enum.PipelineResult
  %ssa.t16 = alloca i32
  %ssa.t17 = alloca i32
  %ssa.t18 = alloca i32
  %ssa.t19 = alloca i32
  %ssa.t20 = alloca i32
  %ssa.t21 = alloca i32
  %ssa.t22 = alloca i32
  %ssa.t23 = alloca i32
  %borrow.34 = alloca %struct.Vec
  %borrow.37 = alloca %struct.Vec
  %borrow.39 = alloca %struct.Vec
  %borrow.42 = alloca %struct.Vec
  %borrow.44 = alloca %struct.Vec
  %borrow.46 = alloca %struct.Vec
  %ssa.t24 = alloca %struct.Vec
  %ssa.t25 = alloca %struct.Vec
  %t48 = alloca %enum.PipelineResult
  %t50 = alloca %struct.BatchStats
  %t0 = call %enum.ValidResult @validate_config(ptr %cfg)
  store %enum.ValidResult %t0, ptr %ssa.t14
  %t2 = load i32, ptr %ssa.t14
  %t3 = sext i32 %t2 to i64
  %t4 = icmp eq i64 %t3, 1
  br i1 %t4, label %arm01, label %check12
arm01:
  store %enum.ValidResult %t0, ptr %ssa.t15
  %t5 = getelementptr i8, ptr %ssa.t15, i64 4
  %t7 = load %enum.ParseError, ptr %t5
  store i32 1, ptr %t8
  %t9 = getelementptr i8, ptr %t8, i64 4
  store %enum.ParseError %t7, ptr %t9
  %t11 = load %enum.PipelineResult, ptr %t8
  ret %enum.PipelineResult %t11
check12:
  %t12 = icmp eq i64 %t3, 0
  br i1 %t12, label %merge0, label %check24
check24:
  unreachable
merge0:
  %t16 = call %struct.Vec @vec_new_4()
  store %struct.Vec %t16, ptr %mutref.17
  store i32 5, ptr %ssa.t16
  call void @vec_push_4(ptr %mutref.17, ptr %ssa.t16)
  %wb.18 = load %struct.Vec, ptr %mutref.17
  store %struct.Vec %wb.18, ptr %mutref.19
  store i32 15, ptr %ssa.t17
  call void @vec_push_4(ptr %mutref.19, ptr %ssa.t17)
  %wb.20 = load %struct.Vec, ptr %mutref.19
  store %struct.Vec %wb.20, ptr %mutref.21
  store i32 25, ptr %ssa.t18
  call void @vec_push_4(ptr %mutref.21, ptr %ssa.t18)
  %wb.22 = load %struct.Vec, ptr %mutref.21
  store %struct.Vec %wb.22, ptr %mutref.23
  store i32 35, ptr %ssa.t19
  call void @vec_push_4(ptr %mutref.23, ptr %ssa.t19)
  %wb.24 = load %struct.Vec, ptr %mutref.23
  store %struct.Vec %wb.24, ptr %mutref.25
  store i32 45, ptr %ssa.t20
  call void @vec_push_4(ptr %mutref.25, ptr %ssa.t20)
  %wb.26 = load %struct.Vec, ptr %mutref.25
  store %struct.Vec %wb.26, ptr %mutref.27
  store i32 55, ptr %ssa.t21
  call void @vec_push_4(ptr %mutref.27, ptr %ssa.t21)
  %wb.28 = load %struct.Vec, ptr %mutref.27
  store %struct.Vec %wb.28, ptr %mutref.29
  %t30 = sub i32 0, 5
  store i32 %t30, ptr %ssa.t22
  call void @vec_push_4(ptr %mutref.29, ptr %ssa.t22)
  %wb.31 = load %struct.Vec, ptr %mutref.29
  store %struct.Vec %wb.31, ptr %mutref.32
  store i32 100, ptr %ssa.t23
  call void @vec_push_4(ptr %mutref.32, ptr %ssa.t23)
  %wb.33 = load %struct.Vec, ptr %mutref.32
  store %struct.Vec %wb.33, ptr %borrow.34
  %t35 = call i64 @vec_len(ptr %borrow.34)
  %t36 = trunc i64 %t35 to i32
  store %struct.Vec %wb.33, ptr %borrow.37
  %t38 = call %struct.Vec @process_batch(ptr %borrow.37, ptr %cfg)
  store %struct.Vec %t38, ptr %borrow.39
  %t40 = call i64 @vec_len(ptr %borrow.39)
  %t41 = trunc i64 %t40 to i32
  store %struct.Vec %t38, ptr %borrow.42
  %t43 = call i32 @sum_values(ptr %borrow.42)
  store %struct.Vec %t38, ptr %borrow.44
  %t45 = call i32 @find_first_exceeding(ptr %borrow.44, i32 60)
  store %struct.Vec %t38, ptr %borrow.46
  %t47 = call i32 @count_in_range(ptr %borrow.46, i32 20, i32 80)
  store %struct.Vec %wb.33, ptr %ssa.t24
  call void @vec_free(ptr %ssa.t24)
  store %struct.Vec %t38, ptr %ssa.t25
  call void @vec_free(ptr %ssa.t25)
  store i32 0, ptr %t48
  %t49 = getelementptr i8, ptr %t48, i64 4
  store i32 %t36, ptr %t50
  %t52 = getelementptr i8, ptr %t50, i64 4
  store i32 %t41, ptr %t52
  %t53 = getelementptr i8, ptr %t50, i64 8
  store i32 %t43, ptr %t53
  %t54 = getelementptr i8, ptr %t50, i64 12
  store i32 %t45, ptr %t54
  %t55 = getelementptr i8, ptr %t50, i64 16
  store i32 %t47, ptr %t55
  %t56 = load %struct.BatchStats, ptr %t50
  store %struct.BatchStats %t56, ptr %t49
  %t58 = load %enum.PipelineResult, ptr %t48
  ret %enum.PipelineResult %t58
}

define i64 @user_main() {
entry:
  %t0 = alloca %struct.Config
  %ssa.t26 = alloca %struct.Config
  %ssa.t27 = alloca %enum.PipelineResult
  %ssa.t28 = alloca %enum.PipelineResult
  %ssa.t29 = alloca %struct.BatchStats
  %ssa.t30 = alloca %struct.BatchStats
  %ssa.t31 = alloca %struct.BatchStats
  %ssa.t32 = alloca %struct.BatchStats
  %ssa.t33 = alloca %struct.BatchStats
  %t32 = alloca %struct.Config
  %ssa.t34 = alloca %struct.Config
  %ssa.t35 = alloca %enum.PipelineResult
  %ssa.t36 = alloca %enum.PipelineResult
  %ssa.t37 = alloca %enum.ParseError
  %t58 = alloca %struct.Config
  %ssa.t38 = alloca %struct.Config
  %ssa.t39 = alloca %enum.PipelineResult
  %ssa.t40 = alloca %enum.PipelineResult
  %ssa.t41 = alloca %enum.ParseError
  %t84 = alloca %struct.Config
  %ssa.t42 = alloca %struct.Config
  store i32 50, ptr %t0
  %t2 = getelementptr i8, ptr %t0, i64 4
  store i32 0, ptr %t2
  %t3 = getelementptr i8, ptr %t0, i64 8
  store i32 2, ptr %t3
  %t4 = load %struct.Config, ptr %t0
  store %struct.Config %t4, ptr %ssa.t26
  %t5 = call %enum.PipelineResult @run_pipeline(ptr %ssa.t26)
  store %enum.PipelineResult %t5, ptr %ssa.t27
  %t7 = load i32, ptr %ssa.t27
  %t8 = sext i32 %t7 to i64
  %t9 = icmp eq i64 %t8, 0
  br i1 %t9, label %arm01, label %check12
arm01:
  store %enum.PipelineResult %t5, ptr %ssa.t28
  %t10 = getelementptr i8, ptr %ssa.t28, i64 4
  %t12 = load %struct.BatchStats, ptr %t10
  store %struct.BatchStats %t12, ptr %ssa.t29
  %t14 = load i32, ptr %ssa.t29
  %t15 = icmp ne i32 %t14, 8
  br i1 %t15, label %then3, label %merge5
then3:
  ret i64 1
merge5:
  store %struct.BatchStats %t12, ptr %ssa.t30
  %t16 = getelementptr i8, ptr %ssa.t30, i64 4
  %t17 = load i32, ptr %t16
  %t18 = icmp ne i32 %t17, 5
  br i1 %t18, label %then6, label %merge8
then6:
  ret i64 2
merge8:
  store %struct.BatchStats %t12, ptr %ssa.t31
  %t19 = getelementptr i8, ptr %ssa.t31, i64 8
  %t20 = load i32, ptr %t19
  %t21 = icmp ne i32 %t20, 250
  br i1 %t21, label %then9, label %merge11
then9:
  ret i64 3
merge11:
  store %struct.BatchStats %t12, ptr %ssa.t32
  %t22 = getelementptr i8, ptr %ssa.t32, i64 12
  %t23 = load i32, ptr %t22
  %t24 = icmp ne i32 %t23, 70
  br i1 %t24, label %then12, label %merge14
then12:
  ret i64 4
merge14:
  store %struct.BatchStats %t12, ptr %ssa.t33
  %t25 = getelementptr i8, ptr %ssa.t33, i64 16
  %t26 = load i32, ptr %t25
  %t27 = icmp ne i32 %t26, 3
  br i1 %t27, label %then15, label %merge0
then15:
  ret i64 5
check12:
  %t28 = icmp eq i64 %t8, 1
  br i1 %t28, label %arm118, label %check219
arm118:
  ret i64 10
check219:
  unreachable
merge0:
  store i32 10, ptr %t32
  %t34 = getelementptr i8, ptr %t32, i64 4
  store i32 20, ptr %t34
  %t35 = getelementptr i8, ptr %t32, i64 8
  store i32 1, ptr %t35
  %t36 = load %struct.Config, ptr %t32
  store %struct.Config %t36, ptr %ssa.t34
  %t37 = call %enum.PipelineResult @run_pipeline(ptr %ssa.t34)
  store %enum.PipelineResult %t37, ptr %ssa.t35
  %t39 = load i32, ptr %ssa.t35
  %t40 = sext i32 %t39 to i64
  %t41 = icmp eq i64 %t40, 0
  br i1 %t41, label %arm021, label %check122
arm021:
  ret i64 20
check122:
  %t45 = icmp eq i64 %t40, 1
  br i1 %t45, label %arm123, label %check224
arm123:
  store %enum.PipelineResult %t37, ptr %ssa.t36
  %t46 = getelementptr i8, ptr %ssa.t36, i64 4
  %t48 = load %enum.ParseError, ptr %t46
  store %enum.ParseError %t48, ptr %ssa.t37
  %t50 = load i32, ptr %ssa.t37
  %t51 = sext i32 %t50 to i64
  %t52 = icmp eq i64 %t51, 2
  br i1 %t52, label %merge20, label %check127
check127:
  %t54 = icmp eq i64 %t51, 0
  br i1 %t54, label %arm128, label %check229
arm128:
  ret i64 21
check229:
  %t56 = icmp eq i64 %t51, 1
  br i1 %t56, label %arm230, label %check331
arm230:
  ret i64 22
check331:
  unreachable
check224:
  unreachable
merge20:
  store i32 100, ptr %t58
  %t60 = getelementptr i8, ptr %t58, i64 4
  store i32 0, ptr %t60
  %t61 = getelementptr i8, ptr %t58, i64 8
  store i32 0, ptr %t61
  %t62 = load %struct.Config, ptr %t58
  store %struct.Config %t62, ptr %ssa.t38
  %t63 = call %enum.PipelineResult @run_pipeline(ptr %ssa.t38)
  store %enum.PipelineResult %t63, ptr %ssa.t39
  %t65 = load i32, ptr %ssa.t39
  %t66 = sext i32 %t65 to i64
  %t67 = icmp eq i64 %t66, 0
  br i1 %t67, label %arm033, label %check134
arm033:
  ret i64 30
check134:
  %t71 = icmp eq i64 %t66, 1
  br i1 %t71, label %arm135, label %check236
arm135:
  store %enum.PipelineResult %t63, ptr %ssa.t40
  %t72 = getelementptr i8, ptr %ssa.t40, i64 4
  %t74 = load %enum.ParseError, ptr %t72
  store %enum.ParseError %t74, ptr %ssa.t41
  %t76 = load i32, ptr %ssa.t41
  %t77 = sext i32 %t76 to i64
  %t78 = icmp eq i64 %t77, 1
  br i1 %t78, label %merge32, label %check139
check139:
  %t80 = icmp eq i64 %t77, 0
  br i1 %t80, label %arm140, label %check241
arm140:
  ret i64 31
check241:
  %t82 = icmp eq i64 %t77, 2
  br i1 %t82, label %arm242, label %check343
arm242:
  ret i64 32
check343:
  unreachable
check236:
  unreachable
merge32:
  store i32 30, ptr %t84
  %t86 = getelementptr i8, ptr %t84, i64 4
  store i32 0, ptr %t86
  %t87 = getelementptr i8, ptr %t84, i64 8
  store i32 1, ptr %t87
  %t88 = load %struct.Config, ptr %t84
  store %struct.Config %t88, ptr %ssa.t42
  %t89 = call i32 @process_with_cleanup(i32 10, ptr %ssa.t42)
  %t90 = icmp ne i32 %t89, 10
  br i1 %t90, label %then44, label %merge46
then44:
  ret i64 40
merge46:
  ret i64 0
}

define i32 @__concrete_get_argc() {
entry:
  %argc = load i32, ptr @__concrete_argc
  ret i32 %argc
}

define ptr @__concrete_get_argv(i32 %idx) {
entry:
  %argv = load ptr, ptr @__concrete_argv
  %idx64 = sext i32 %idx to i64
  %argp = getelementptr ptr, ptr %argv, i64 %idx64
  %arg = load ptr, ptr %argp
  ret ptr %arg
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  store i32 %argc, ptr @__concrete_argc
  store ptr %argv, ptr @__concrete_argv
  %result = call i64 @user_main()
  %fmt = getelementptr [6 x i8], ptr @fmt.main, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %fmt, i64 %result)
  ret i32 0
}

define ptr @__concrete_check_oom(ptr %p) {
entry:
  %is_null = icmp eq ptr %p, null
  br i1 %is_null, label %oom, label %ok
oom:
  call void @abort()
  unreachable
ok:
  ret ptr %p
}

define i64 @string_length(ptr %s) {
entry:
  %len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len = load i64, ptr %len_ptr
  ret i64 %len
}

define void @drop_string(ptr %s) {
entry:
  %data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data = load ptr, ptr %data_ptr
  call void @free(ptr %data)
  ret void
}

define %struct.String @string_concat(ptr %a, ptr %b) {
entry:
  %a_data_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 0
  %a_data = load ptr, ptr %a_data_ptr
  %a_len_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 1
  %a_len = load i64, ptr %a_len_ptr
  %b_data_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 0
  %b_data = load ptr, ptr %b_data_ptr
  %b_len_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 1
  %b_len = load i64, ptr %b_len_ptr
  %total_len = add i64 %a_len, %b_len
  %buf.raw = call ptr @malloc(i64 %total_len)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %buf, ptr %a_data, i64 %a_len, i1 false)
  %dst = getelementptr i8, ptr %buf, i64 %a_len
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %b_data, i64 %b_len, i1 false)
  call void @free(ptr %a_data)
  call void @free(ptr %b_data)
  %sc_alloca = alloca %struct.String
  %sc_data_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 0
  store ptr %buf, ptr %sc_data_ptr
  %sc_len_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 1
  store i64 %total_len, ptr %sc_len_ptr
  %sc_cap_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 2
  store i64 %total_len, ptr %sc_cap_ptr
  %sc_result = load %struct.String, ptr %sc_alloca
  ret %struct.String %sc_result
}

define %struct.String @string_slice(ptr %s, i64 %start, i64 %end_) {
entry:
  %len_ptr.ss = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len.ss = load i64, ptr %len_ptr.ss
  %s_clamped = call i64 @llvm.smax.i64(i64 %start, i64 0)
  %s_min = call i64 @llvm.smin.i64(i64 %s_clamped, i64 %len.ss)
  %e_clamped = call i64 @llvm.smax.i64(i64 %end_, i64 0)
  %e_min = call i64 @llvm.smin.i64(i64 %e_clamped, i64 %len.ss)
  %e_final = call i64 @llvm.smax.i64(i64 %e_min, i64 %s_min)
  %slice_len = sub i64 %e_final, %s_min
  %slice_buf.raw = call ptr @malloc(i64 %slice_len)
  %slice_buf = call ptr @__concrete_check_oom(ptr %slice_buf.raw)
  %data_ptr.ss = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data.ss = load ptr, ptr %data_ptr.ss
  %src = getelementptr i8, ptr %data.ss, i64 %s_min
  call void @llvm.memcpy.p0.p0.i64(ptr %slice_buf, ptr %src, i64 %slice_len, i1 false)
  %res.ss = alloca %struct.String
  %res_d.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 0
  store ptr %slice_buf, ptr %res_d.ss
  %res_l.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 1
  store i64 %slice_len, ptr %res_l.ss
  %res_c.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 2
  store i64 %slice_len, ptr %res_c.ss
  %result.ss = load %struct.String, ptr %res.ss
  ret %struct.String %result.ss
}

define %struct.String @string_substr(ptr %s, i64 %start, i64 %len) {
entry:
  %end_ = add i64 %start, %len
  %result.ssub = call %struct.String @string_slice(ptr %s, i64 %start, i64 %end_)
  ret %struct.String %result.ssub
}

define i64 @string_char_at(ptr %s, i64 %index) {
entry:
  %len_ptr.sca = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len.sca = load i64, ptr %len_ptr.sca
  %neg = icmp slt i64 %index, 0
  %oob = icmp sge i64 %index, %len.sca
  %bad = or i1 %neg, %oob
  br i1 %bad, label %ret_neg, label %ok_idx
ret_neg:
  ret i64 -1
ok_idx:
  %data_ptr.sca = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data.sca = load ptr, ptr %data_ptr.sca
  %char_ptr = getelementptr i8, ptr %data.sca, i64 %index
  %byte = load i8, ptr %char_ptr
  %char = zext i8 %byte to i64
  ret i64 %char
}

define i1 @string_contains(ptr %haystack, ptr %needle) {
entry:
  %h_data_ptr = getelementptr %struct.String, ptr %haystack, i32 0, i32 0
  %h_data = load ptr, ptr %h_data_ptr
  %h_len_ptr = getelementptr %struct.String, ptr %haystack, i32 0, i32 1
  %h_len = load i64, ptr %h_len_ptr
  %n_data_ptr = getelementptr %struct.String, ptr %needle, i32 0, i32 0
  %n_data = load ptr, ptr %n_data_ptr
  %n_len_ptr = getelementptr %struct.String, ptr %needle, i32 0, i32 1
  %n_len = load i64, ptr %n_len_ptr
  %n_empty = icmp eq i64 %n_len, 0
  br i1 %n_empty, label %found, label %check_len
check_len:
  %too_long = icmp ugt i64 %n_len, %h_len
  br i1 %too_long, label %not_found, label %loop_start
loop_start:
  %max_i = sub i64 %h_len, %n_len
  br label %loop
loop:
  %i = phi i64 [0, %loop_start], [%i_next, %loop_cont]
  %h_ptr = getelementptr i8, ptr %h_data, i64 %i
  %cmp = call i32 @memcmp(ptr %h_ptr, ptr %n_data, i64 %n_len)
  %match = icmp eq i32 %cmp, 0
  br i1 %match, label %found, label %loop_cont
loop_cont:
  %i_next = add i64 %i, 1
  %done = icmp ugt i64 %i_next, %max_i
  br i1 %done, label %not_found, label %loop
found:
  ret i1 1
not_found:
  ret i1 0
}

define i1 @string_eq(ptr %a, ptr %b) {
entry:
  %a_len_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 1
  %a_len = load i64, ptr %a_len_ptr
  %b_len_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 1
  %b_len = load i64, ptr %b_len_ptr
  %len_eq = icmp eq i64 %a_len, %b_len
  br i1 %len_eq, label %cmp_data, label %not_eq
cmp_data:
  %zero_len = icmp eq i64 %a_len, 0
  br i1 %zero_len, label %eq, label %do_cmp
do_cmp:
  %a_data_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 0
  %a_data = load ptr, ptr %a_data_ptr
  %b_data_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 0
  %b_data = load ptr, ptr %b_data_ptr
  %cmp_res = call i32 @memcmp(ptr %a_data, ptr %b_data, i64 %a_len)
  %eq_data = icmp eq i32 %cmp_res, 0
  br i1 %eq_data, label %eq, label %not_eq
eq:
  ret i1 1
not_eq:
  ret i1 0
}

define %struct.String @int_to_string(i64 %n) {
entry:
  %buf.raw = call ptr @malloc(i64 32)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  %fmt_its = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %buf, i64 32, ptr %fmt_its, i64 %n)
  %wext = sext i32 %written to i64
  %res.its = alloca %struct.String
  %res_d.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 0
  store ptr %buf, ptr %res_d.its
  %res_l.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 1
  store i64 %wext, ptr %res_l.its
  %res_c.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 2
  store i64 32, ptr %res_c.its
  %result.its = load %struct.String, ptr %res.its
  ret %struct.String %result.its
}

define %enum.Result @string_to_int(ptr %s) {
entry:
  %sti_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sti_data = load ptr, ptr %sti_data_ptr
  %sti_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sti_len = load i64, ptr %sti_len_ptr
  %sti_buf_sz = add i64 %sti_len, 1
  %sti_buf.raw = call ptr @malloc(i64 %sti_buf_sz)
  %sti_buf = call ptr @__concrete_check_oom(ptr %sti_buf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %sti_buf, ptr %sti_data, i64 %sti_len, i1 false)
  %sti_null = getelementptr i8, ptr %sti_buf, i64 %sti_len
  store i8 0, ptr %sti_null
  %endptr_alloca = alloca ptr
  %sti_val = call i64 @strtol(ptr %sti_buf, ptr %endptr_alloca, i32 10)
  %endptr = load ptr, ptr %endptr_alloca
  %end_expected = getelementptr i8, ptr %sti_buf, i64 %sti_len
  %valid = icmp eq ptr %endptr, %end_expected
  %empty_input = icmp eq i64 %sti_len, 0
  %not_empty = xor i1 %empty_input, 1
  %final_ok = and i1 %valid, %not_empty
  call void @free(ptr %sti_buf)
  %res.sti = alloca %enum.Result
  br i1 %final_ok, label %sti_ok, label %sti_err
sti_ok:
  store i32 0, ptr %res.sti
  %data_ptr.sti_ok = getelementptr i8, ptr %res.sti, i64 8
  store i64 %sti_val, ptr %data_ptr.sti_ok
  br label %sti_done
sti_err:
  store i32 1, ptr %res.sti
  %data_ptr.sti_err = getelementptr i8, ptr %res.sti, i64 8
  store i64 1, ptr %data_ptr.sti_err
  br label %sti_done
sti_done:
  %result.sti = load %enum.Result, ptr %res.sti
  ret %enum.Result %result.sti
}

define %struct.String @bool_to_string(i1 %b) {
entry:
  br i1 %b, label %bts_true, label %bts_false
bts_true:
  %tbuf.raw = call ptr @malloc(i64 4)
  %tbuf = call ptr @__concrete_check_oom(ptr %tbuf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %tbuf, ptr @.str_true, i64 4, i1 false)
  %tres = alloca %struct.String
  %td = getelementptr %struct.String, ptr %tres, i32 0, i32 0
  store ptr %tbuf, ptr %td
  %tl = getelementptr %struct.String, ptr %tres, i32 0, i32 1
  store i64 4, ptr %tl
  %tc = getelementptr %struct.String, ptr %tres, i32 0, i32 2
  store i64 4, ptr %tc
  %tresult = load %struct.String, ptr %tres
  ret %struct.String %tresult
bts_false:
  %fbuf.raw = call ptr @malloc(i64 5)
  %fbuf = call ptr @__concrete_check_oom(ptr %fbuf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %fbuf, ptr @.str_false, i64 5, i1 false)
  %fres = alloca %struct.String
  %fd = getelementptr %struct.String, ptr %fres, i32 0, i32 0
  store ptr %fbuf, ptr %fd
  %fl = getelementptr %struct.String, ptr %fres, i32 0, i32 1
  store i64 5, ptr %fl
  %fc = getelementptr %struct.String, ptr %fres, i32 0, i32 2
  store i64 5, ptr %fc
  %fresult = load %struct.String, ptr %fres
  ret %struct.String %fresult
}

define %struct.String @float_to_string(double %f) {
entry:
  %fbuf.fts.raw = call ptr @malloc(i64 64)
  %fbuf.fts = call ptr @__concrete_check_oom(ptr %fbuf.fts.raw)
  %fmt.fts = getelementptr [3 x i8], ptr @.fmt_f, i64 0, i64 0
  %written.fts = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %fbuf.fts, i64 64, ptr %fmt.fts, double %f)
  %wext.fts = sext i32 %written.fts to i64
  %res.fts = alloca %struct.String
  %res_d.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 0
  store ptr %fbuf.fts, ptr %res_d.fts
  %res_l.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 1
  store i64 %wext.fts, ptr %res_l.fts
  %res_c.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 2
  store i64 64, ptr %res_c.fts
  %result.fts = load %struct.String, ptr %res.fts
  ret %struct.String %result.fts
}

define %struct.String @string_trim(ptr %s) {
entry:
  %st_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %st_data = load ptr, ptr %st_data_ptr
  %st_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %st_len = load i64, ptr %st_len_ptr
  br label %trim_left
trim_left:
  %tl_i = phi i64 [0, %entry], [%tl_next, %tl_ws]
  %tl_done = icmp uge i64 %tl_i, %st_len
  br i1 %tl_done, label %trim_result, label %tl_check
tl_check:
  %tl_ptr = getelementptr i8, ptr %st_data, i64 %tl_i
  %tl_ch = load i8, ptr %tl_ptr
  %tl_is_sp = icmp eq i8 %tl_ch, 32
  %tl_is_tab = icmp eq i8 %tl_ch, 9
  %tl_is_nl = icmp eq i8 %tl_ch, 10
  %tl_is_cr = icmp eq i8 %tl_ch, 13
  %tl_w1 = or i1 %tl_is_sp, %tl_is_tab
  %tl_w2 = or i1 %tl_is_nl, %tl_is_cr
  %tl_is_ws = or i1 %tl_w1, %tl_w2
  br i1 %tl_is_ws, label %tl_ws, label %trim_right_init
tl_ws:
  %tl_next = add i64 %tl_i, 1
  br label %trim_left
trim_right_init:
  %tr_start = sub i64 %st_len, 1
  br label %trim_right
trim_right:
  %tr_i = phi i64 [%tr_start, %trim_right_init], [%tr_prev, %tr_ws]
  %tr_done = icmp ult i64 %tr_i, %tl_i
  br i1 %tr_done, label %trim_result, label %tr_check
tr_check:
  %tr_ptr = getelementptr i8, ptr %st_data, i64 %tr_i
  %tr_ch = load i8, ptr %tr_ptr
  %tr_is_sp = icmp eq i8 %tr_ch, 32
  %tr_is_tab = icmp eq i8 %tr_ch, 9
  %tr_is_nl = icmp eq i8 %tr_ch, 10
  %tr_is_cr = icmp eq i8 %tr_ch, 13
  %tr_w1 = or i1 %tr_is_sp, %tr_is_tab
  %tr_w2 = or i1 %tr_is_nl, %tr_is_cr
  %tr_is_ws = or i1 %tr_w1, %tr_w2
  br i1 %tr_is_ws, label %tr_ws, label %trim_result
tr_ws:
  %tr_prev = sub i64 %tr_i, 1
  br label %trim_right
trim_result:
  %tr_left = phi i64 [%tl_i, %trim_left], [%tl_i, %trim_right], [%tl_i, %tr_check]
  %tr_right_raw = phi i64 [0, %trim_left], [%tl_i, %trim_right], [%tr_i, %tr_check]
  %tr_right = add i64 %tr_right_raw, 1
  %tr_empty = icmp uge i64 %tr_left, %tr_right
  br i1 %tr_empty, label %trim_empty, label %trim_copy
trim_empty:
  %te_buf.raw = call ptr @malloc(i64 1)
  %te_buf = call ptr @__concrete_check_oom(ptr %te_buf.raw)
  %te_res = alloca %struct.String
  %te_d = getelementptr %struct.String, ptr %te_res, i32 0, i32 0
  store ptr %te_buf, ptr %te_d
  %te_l = getelementptr %struct.String, ptr %te_res, i32 0, i32 1
  store i64 0, ptr %te_l
  %te_c = getelementptr %struct.String, ptr %te_res, i32 0, i32 2
  store i64 1, ptr %te_c
  %te_result = load %struct.String, ptr %te_res
  ret %struct.String %te_result
trim_copy:
  %tc_len = sub i64 %tr_right, %tr_left
  %tc_buf.raw = call ptr @malloc(i64 %tc_len)
  %tc_buf = call ptr @__concrete_check_oom(ptr %tc_buf.raw)
  %tc_src = getelementptr i8, ptr %st_data, i64 %tr_left
  call void @llvm.memcpy.p0.p0.i64(ptr %tc_buf, ptr %tc_src, i64 %tc_len, i1 false)
  %tc_res = alloca %struct.String
  %tc_d = getelementptr %struct.String, ptr %tc_res, i32 0, i32 0
  store ptr %tc_buf, ptr %tc_d
  %tc_l = getelementptr %struct.String, ptr %tc_res, i32 0, i32 1
  store i64 %tc_len, ptr %tc_l
  %tc_c = getelementptr %struct.String, ptr %tc_res, i32 0, i32 2
  store i64 %tc_len, ptr %tc_c
  %tc_result = load %struct.String, ptr %tc_res
  ret %struct.String %tc_result
}

define void @print_string(ptr %s) {
entry:
  %ps_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %ps_data = load ptr, ptr %ps_data_ptr
  %ps_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %ps_len = load i64, ptr %ps_len_ptr
  %ps_fmt = getelementptr [5 x i8], ptr @.fmt_str, i64 0, i64 0
  %ps_len32 = trunc i64 %ps_len to i32
  %ps_written = call i32 (ptr, ...) @printf(ptr %ps_fmt, i32 %ps_len32, ptr %ps_data)
  ret void
}

define void @print_int(i64 %n) {
entry:
  %pi_fmt = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %pi_written = call i32 (ptr, ...) @printf(ptr %pi_fmt, i64 %n)
  ret void
}

define void @print_char(i64 %c) {
entry:
  %pc_int = trunc i64 %c to i32
  %pc_wr = call i32 @putchar(i32 %pc_int)
  ret void
}

define void @print_bool(i1 %b) {
entry:
  %is_true = icmp eq i1 %b, 1
  br i1 %is_true, label %print_true, label %print_false
print_true:
  %true_ptr = getelementptr [5 x i8], ptr @.str_true, i64 0, i64 0
  %tw = call i32 (ptr, ...) @printf(ptr %true_ptr)
  ret void
print_false:
  %false_ptr = getelementptr [6 x i8], ptr @.str_false, i64 0, i64 0
  %fw = call i32 (ptr, ...) @printf(ptr %false_ptr)
  ret void
}

define void @string_push_char(ptr %s, i64 %c) {
entry:
  %spc_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %spc_len = load i64, ptr %spc_len_ptr
  %spc_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %spc_cap = load i64, ptr %spc_cap_ptr
  %spc_full = icmp eq i64 %spc_len, %spc_cap
  br i1 %spc_full, label %spc_grow, label %spc_store
spc_grow:
  %spc_newcap = mul i64 %spc_cap, 2
  %spc_nc_clamped = call i64 @llvm.smax.i64(i64 %spc_newcap, i64 8)
  %spc_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %spc_data = load ptr, ptr %spc_data_ptr
  %spc_newbuf.raw = call ptr @realloc(ptr %spc_data, i64 %spc_nc_clamped)
  %spc_newbuf = call ptr @__concrete_check_oom(ptr %spc_newbuf.raw)
  store ptr %spc_newbuf, ptr %spc_data_ptr
  store i64 %spc_nc_clamped, ptr %spc_cap_ptr
  br label %spc_store
spc_store:
  %spc_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %spc_data2 = load ptr, ptr %spc_dp2
  %spc_slot = getelementptr i8, ptr %spc_data2, i64 %spc_len
  %spc_byte = trunc i64 %c to i8
  store i8 %spc_byte, ptr %spc_slot
  %spc_newlen = add i64 %spc_len, 1
  store i64 %spc_newlen, ptr %spc_len_ptr
  ret void
}

define void @string_append(ptr %s, ptr %other) {
entry:
  %sa_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sa_len = load i64, ptr %sa_len_ptr
  %sa_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sa_cap = load i64, ptr %sa_cap_ptr
  %sa_olen_ptr = getelementptr %struct.String, ptr %other, i32 0, i32 1
  %sa_olen = load i64, ptr %sa_olen_ptr
  %sa_needed = add i64 %sa_len, %sa_olen
  %sa_need_grow = icmp ugt i64 %sa_needed, %sa_cap
  br i1 %sa_need_grow, label %sa_grow, label %sa_copy
sa_grow:
  %sa_dblcap = mul i64 %sa_cap, 2
  %sa_newcap = call i64 @llvm.smax.i64(i64 %sa_dblcap, i64 %sa_needed)
  %sa_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sa_data = load ptr, ptr %sa_data_ptr
  %sa_newbuf.raw = call ptr @realloc(ptr %sa_data, i64 %sa_newcap)
  %sa_newbuf = call ptr @__concrete_check_oom(ptr %sa_newbuf.raw)
  store ptr %sa_newbuf, ptr %sa_data_ptr
  store i64 %sa_newcap, ptr %sa_cap_ptr
  br label %sa_copy
sa_copy:
  %sa_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sa_data2 = load ptr, ptr %sa_dp2
  %sa_dst = getelementptr i8, ptr %sa_data2, i64 %sa_len
  %sa_odata_ptr = getelementptr %struct.String, ptr %other, i32 0, i32 0
  %sa_odata = load ptr, ptr %sa_odata_ptr
  call void @llvm.memcpy.p0.p0.i64(ptr %sa_dst, ptr %sa_odata, i64 %sa_olen, i1 false)
  store i64 %sa_needed, ptr %sa_len_ptr
  ret void
}

define void @string_append_int(ptr %s, i64 %n) {
entry:
  %sai_buf = alloca [32 x i8]
  %sai_fmt = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %sai_written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %sai_buf, i64 32, ptr %sai_fmt, i64 %n)
  %sai_len = sext i32 %sai_written to i64
  %sai_slen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sai_slen = load i64, ptr %sai_slen_ptr
  %sai_scap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sai_scap = load i64, ptr %sai_scap_ptr
  %sai_needed = add i64 %sai_slen, %sai_len
  %sai_need_grow = icmp ugt i64 %sai_needed, %sai_scap
  br i1 %sai_need_grow, label %sai_grow, label %sai_copy
sai_grow:
  %sai_dblcap = mul i64 %sai_scap, 2
  %sai_newcap = call i64 @llvm.smax.i64(i64 %sai_dblcap, i64 %sai_needed)
  %sai_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sai_data = load ptr, ptr %sai_data_ptr
  %sai_newbuf.raw = call ptr @realloc(ptr %sai_data, i64 %sai_newcap)
  %sai_newbuf = call ptr @__concrete_check_oom(ptr %sai_newbuf.raw)
  store ptr %sai_newbuf, ptr %sai_data_ptr
  store i64 %sai_newcap, ptr %sai_scap_ptr
  br label %sai_copy
sai_copy:
  %sai_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sai_data2 = load ptr, ptr %sai_dp2
  %sai_dst = getelementptr i8, ptr %sai_data2, i64 %sai_slen
  call void @llvm.memcpy.p0.p0.i64(ptr %sai_dst, ptr %sai_buf, i64 %sai_len, i1 false)
  store i64 %sai_needed, ptr %sai_slen_ptr
  ret void
}

define void @string_append_bool(ptr %s, i1 %b) {
entry:
  br i1 %b, label %sab_true, label %sab_false
sab_true:
  %sab_tlen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sab_tlen = load i64, ptr %sab_tlen_ptr
  %sab_tcap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sab_tcap = load i64, ptr %sab_tcap_ptr
  %sab_tneeded = add i64 %sab_tlen, 4
  %sab_tneed_grow = icmp ugt i64 %sab_tneeded, %sab_tcap
  br i1 %sab_tneed_grow, label %sab_tgrow, label %sab_tcopy
sab_tgrow:
  %sab_tdblcap = mul i64 %sab_tcap, 2
  %sab_tnewcap = call i64 @llvm.smax.i64(i64 %sab_tdblcap, i64 %sab_tneeded)
  %sab_tdata_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_tdata = load ptr, ptr %sab_tdata_ptr
  %sab_tnewbuf.raw = call ptr @realloc(ptr %sab_tdata, i64 %sab_tnewcap)
  %sab_tnewbuf = call ptr @__concrete_check_oom(ptr %sab_tnewbuf.raw)
  store ptr %sab_tnewbuf, ptr %sab_tdata_ptr
  store i64 %sab_tnewcap, ptr %sab_tcap_ptr
  br label %sab_tcopy
sab_tcopy:
  %sab_tdp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_tdata2 = load ptr, ptr %sab_tdp2
  %sab_tdst = getelementptr i8, ptr %sab_tdata2, i64 %sab_tlen
  call void @llvm.memcpy.p0.p0.i64(ptr %sab_tdst, ptr @.str_true, i64 4, i1 false)
  store i64 %sab_tneeded, ptr %sab_tlen_ptr
  ret void
sab_false:
  %sab_flen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sab_flen = load i64, ptr %sab_flen_ptr
  %sab_fcap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sab_fcap = load i64, ptr %sab_fcap_ptr
  %sab_fneeded = add i64 %sab_flen, 5
  %sab_fneed_grow = icmp ugt i64 %sab_fneeded, %sab_fcap
  br i1 %sab_fneed_grow, label %sab_fgrow, label %sab_fcopy
sab_fgrow:
  %sab_fdblcap = mul i64 %sab_fcap, 2
  %sab_fnewcap = call i64 @llvm.smax.i64(i64 %sab_fdblcap, i64 %sab_fneeded)
  %sab_fdata_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_fdata = load ptr, ptr %sab_fdata_ptr
  %sab_fnewbuf.raw = call ptr @realloc(ptr %sab_fdata, i64 %sab_fnewcap)
  %sab_fnewbuf = call ptr @__concrete_check_oom(ptr %sab_fnewbuf.raw)
  store ptr %sab_fnewbuf, ptr %sab_fdata_ptr
  store i64 %sab_fnewcap, ptr %sab_fcap_ptr
  br label %sab_fcopy
sab_fcopy:
  %sab_fdp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_fdata2 = load ptr, ptr %sab_fdp2
  %sab_fdst = getelementptr i8, ptr %sab_fdata2, i64 %sab_flen
  call void @llvm.memcpy.p0.p0.i64(ptr %sab_fdst, ptr @.str_false, i64 5, i1 false)
  store i64 %sab_fneeded, ptr %sab_flen_ptr
  ret void
}

define void @string_reserve(ptr %s, i64 %extra) {
entry:
  %sr_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sr_cap = load i64, ptr %sr_cap_ptr
  %sr_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sr_len = load i64, ptr %sr_len_ptr
  %sr_needed = add i64 %sr_len, %extra
  %sr_need_grow = icmp ugt i64 %sr_needed, %sr_cap
  br i1 %sr_need_grow, label %sr_grow, label %sr_done
sr_grow:
  %sr_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sr_data = load ptr, ptr %sr_data_ptr
  %sr_newbuf.raw = call ptr @realloc(ptr %sr_data, i64 %sr_needed)
  %sr_newbuf = call ptr @__concrete_check_oom(ptr %sr_newbuf.raw)
  store ptr %sr_newbuf, ptr %sr_data_ptr
  store i64 %sr_needed, ptr %sr_cap_ptr
  br label %sr_done
sr_done:
  ret void
}

define i64 @clock_monotonic_ns() {
entry:
  %ts = alloca [2 x i64]
  %clk_ret = call i32 @clock_gettime(i32 6, ptr %ts)
  %sec_ptr = getelementptr i64, ptr %ts, i64 0
  %sec = load i64, ptr %sec_ptr
  %nsec_ptr = getelementptr i64, ptr %ts, i64 1
  %nsec = load i64, ptr %nsec_ptr
  %sec_ns = mul i64 %sec, 1000000000
  %total = add i64 %sec_ns, %nsec
  ret i64 %total
}

define i64 @vec_len(ptr %vec) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  ret i64 %len
}

define void @vec_free(ptr %vec) {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  call void @free(ptr %data)
  ret void
}

define %struct.Vec @vec_new_4() alwaysinline {
entry:
  %buf.raw = call ptr @malloc(i64 32)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  %v = alloca %struct.Vec
  %bp = getelementptr %struct.Vec, ptr %v, i32 0, i32 0
  store ptr %buf, ptr %bp
  %lp = getelementptr %struct.Vec, ptr %v, i32 0, i32 1
  store i64 0, ptr %lp
  %cp = getelementptr %struct.Vec, ptr %v, i32 0, i32 2
  store i64 8, ptr %cp
  %r = load %struct.Vec, ptr %v
  ret %struct.Vec %r
}

define void @vec_push_4(ptr %vec, ptr %val) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  %cp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 2
  %cap = load i64, ptr %cp
  %full = icmp eq i64 %len, %cap
  br i1 %full, label %grow, label %store
grow:
  %newcap = mul i64 %cap, 2
  %newbytes = mul i64 %newcap, 4
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %newbuf.raw = call ptr @realloc(ptr %data, i64 %newbytes)
  %newbuf = call ptr @__concrete_check_oom(ptr %newbuf.raw)
  store ptr %newbuf, ptr %dp
  store i64 %newcap, ptr %cp
  br label %store
store:
  %dp2 = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data2 = load ptr, ptr %dp2
  %offset = mul i64 %len, 4
  %slot = getelementptr i8, ptr %data2, i64 %offset
  call void @llvm.memcpy.p0.p0.i64(ptr %slot, ptr %val, i64 4, i1 false)
  %newlen = add i64 %len, 1
  store i64 %newlen, ptr %lp
  ret void
}

define ptr @vec_get_4(ptr %vec, i64 %idx) alwaysinline {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %offset = mul i64 %idx, 4
  %slot = getelementptr i8, ptr %data, i64 %offset
  ret ptr %slot
}

define void @vec_set_4(ptr %vec, i64 %idx, ptr %val) alwaysinline {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %offset = mul i64 %idx, 4
  %slot = getelementptr i8, ptr %data, i64 %offset
  call void @llvm.memcpy.p0.p0.i64(ptr %slot, ptr %val, i64 4, i1 false)
  ret void
}

define %enum.Option @vec_pop_4_4(ptr %vec) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  %empty = icmp eq i64 %len, 0
  br i1 %empty, label %none, label %some
some:
  %newlen = sub i64 %len, 1
  store i64 %newlen, ptr %lp
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %offset = mul i64 %newlen, 4
  %slot = getelementptr i8, ptr %data, i64 %offset
  %res = alloca %enum.Option
  call void @memset(ptr %res, i32 0, i64 8)
  store i32 0, ptr %res
  %payload = getelementptr i8, ptr %res, i64 4
  call void @llvm.memcpy.p0.p0.i64(ptr %payload, ptr %slot, i64 4, i1 false)
  %r = load %enum.Option, ptr %res
  ret %enum.Option %r
none:
  %res2 = alloca %enum.Option
  call void @memset(ptr %res2, i32 0, i64 8)
  store i32 1, ptr %res2
  %r2 = load %enum.Option, ptr %res2
  ret %enum.Option %r2
}

