; Generated by Concrete compiler (SSA path)
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx14.0.0"
%struct.String = type { ptr, i64, i64 }
%struct.Vec = type { ptr, i64, i64 }
%variant.Option.Some = type { i64 }
%variant.Option.None = type {}
%enum.Option = type { i32, [12 x i8] }
%variant.Result.Ok = type { i64 }
%variant.Result.Err = type { i64 }
%enum.Result = type { i32, [12 x i8] }
%variant.Op.Push = type { i32 }
%variant.Op.Pop = type {}
%variant.Op.Add = type {}
%variant.Op.Sub = type {}
%variant.Op.Mul = type {}
%variant.Op.Dup = type {}
%variant.Op.Swap = type {}
%variant.Op.LoadConst = type { i32 }
%variant.Op.Store = type { i32 }
%variant.Op.Load = type { i32 }
%variant.Op.Halt = type {}
%enum.Op = type { i32, [4 x i8] }
@__concrete_argc = private global i32 0
@__concrete_argv = private global ptr null
@fmt.main = private constant [6 x i8] c"%lld\0A\00"
@.fmt_ld = private constant [4 x i8] c"%ld\00"
@.fmt_str = private constant [5 x i8] c"%.*s\00"
@.str_true = private constant [5 x i8] c"true\00"
@.str_false = private constant [6 x i8] c"false\00"
@.fmt_f = private constant [3 x i8] c"%g\00"
declare ptr @malloc(i64)
declare void @free(ptr)
declare ptr @realloc(ptr, i64)
declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
declare i64 @write(i32, ptr, i64)
declare void @abort()
declare i32 @printf(ptr, ...)
declare i64 @strlen(ptr)
declare ptr @memset(ptr, i32, i64)
declare i32 @memcmp(ptr, ptr, i64)
declare i32 @snprintf(ptr, i64, ptr, ...)
declare i64 @strtol(ptr, ptr, i32)
declare i64 @llvm.smax.i64(i64, i64)
declare i64 @llvm.smin.i64(i64, i64)
declare i32 @clock_gettime(i32, ptr)
declare i32 @putchar(i32)
define i32 @tag_of(ptr %op) {
entry:
  %ssa.t0 = alloca %enum.Op
  %t0 = load %enum.Op, ptr %op
  store %enum.Op %t0, ptr %ssa.t0
  %t2 = load i32, ptr %ssa.t0
  %t3 = sext i32 %t2 to i64
  %t4 = icmp eq i64 %t3, 0
  br i1 %t4, label %arm01, label %check12
arm01:
  ret i32 0
check12:
  %t8 = icmp eq i64 %t3, 1
  br i1 %t8, label %arm13, label %check24
arm13:
  ret i32 1
check24:
  %t10 = icmp eq i64 %t3, 2
  br i1 %t10, label %arm25, label %check36
arm25:
  ret i32 2
check36:
  %t12 = icmp eq i64 %t3, 3
  br i1 %t12, label %arm37, label %check48
arm37:
  ret i32 3
check48:
  %t14 = icmp eq i64 %t3, 4
  br i1 %t14, label %arm49, label %check510
arm49:
  ret i32 4
check510:
  %t16 = icmp eq i64 %t3, 5
  br i1 %t16, label %arm511, label %check612
arm511:
  ret i32 5
check612:
  %t18 = icmp eq i64 %t3, 6
  br i1 %t18, label %arm613, label %check714
arm613:
  ret i32 6
check714:
  %t20 = icmp eq i64 %t3, 7
  br i1 %t20, label %arm715, label %check816
arm715:
  ret i32 7
check816:
  %t24 = icmp eq i64 %t3, 8
  br i1 %t24, label %arm817, label %check918
arm817:
  ret i32 8
check918:
  %t28 = icmp eq i64 %t3, 9
  br i1 %t28, label %arm919, label %check1020
arm919:
  ret i32 9
check1020:
  %t32 = icmp eq i64 %t3, 10
  br i1 %t32, label %arm1021, label %check1122
arm1021:
  ret i32 10
check1122:
  unreachable
}

define i32 @operand_of(ptr %op) {
entry:
  %ssa.t1 = alloca %enum.Op
  %ssa.t2 = alloca %enum.Op
  %ssa.t3 = alloca %enum.Op
  %ssa.t4 = alloca %enum.Op
  %ssa.t5 = alloca %enum.Op
  %t0 = load %enum.Op, ptr %op
  store %enum.Op %t0, ptr %ssa.t1
  %t2 = load i32, ptr %ssa.t1
  %t3 = sext i32 %t2 to i64
  %t4 = icmp eq i64 %t3, 0
  br i1 %t4, label %arm01, label %check12
arm01:
  store %enum.Op %t0, ptr %ssa.t2
  %t5 = getelementptr i8, ptr %ssa.t2, i64 4
  %t7 = load i32, ptr %t5
  ret i32 %t7
check12:
  %t8 = icmp eq i64 %t3, 1
  br i1 %t8, label %arm13, label %check24
arm13:
  ret i32 0
check24:
  %t10 = icmp eq i64 %t3, 2
  br i1 %t10, label %arm25, label %check36
arm25:
  ret i32 0
check36:
  %t12 = icmp eq i64 %t3, 3
  br i1 %t12, label %arm37, label %check48
arm37:
  ret i32 0
check48:
  %t14 = icmp eq i64 %t3, 4
  br i1 %t14, label %arm49, label %check510
arm49:
  ret i32 0
check510:
  %t16 = icmp eq i64 %t3, 5
  br i1 %t16, label %arm511, label %check612
arm511:
  ret i32 0
check612:
  %t18 = icmp eq i64 %t3, 6
  br i1 %t18, label %arm613, label %check714
arm613:
  ret i32 0
check714:
  %t20 = icmp eq i64 %t3, 7
  br i1 %t20, label %arm715, label %check816
arm715:
  store %enum.Op %t0, ptr %ssa.t3
  %t21 = getelementptr i8, ptr %ssa.t3, i64 4
  %t23 = load i32, ptr %t21
  ret i32 %t23
check816:
  %t24 = icmp eq i64 %t3, 8
  br i1 %t24, label %arm817, label %check918
arm817:
  store %enum.Op %t0, ptr %ssa.t4
  %t25 = getelementptr i8, ptr %ssa.t4, i64 4
  %t27 = load i32, ptr %t25
  ret i32 %t27
check918:
  %t28 = icmp eq i64 %t3, 9
  br i1 %t28, label %arm919, label %check1020
arm919:
  store %enum.Op %t0, ptr %ssa.t5
  %t29 = getelementptr i8, ptr %ssa.t5, i64 4
  %t31 = load i32, ptr %t29
  ret i32 %t31
check1020:
  %t32 = icmp eq i64 %t3, 10
  br i1 %t32, label %arm1021, label %check1122
arm1021:
  ret i32 0
check1122:
  unreachable
}

define %enum.Op @decode(i32 %tag, i32 %operand) {
entry:
  %t1 = alloca %enum.Op
  %t6 = alloca %enum.Op
  %t10 = alloca %enum.Op
  %t14 = alloca %enum.Op
  %t18 = alloca %enum.Op
  %t22 = alloca %enum.Op
  %t26 = alloca %enum.Op
  %t30 = alloca %enum.Op
  %t35 = alloca %enum.Op
  %t40 = alloca %enum.Op
  %t44 = alloca %enum.Op
  %t0 = icmp eq i32 %tag, 0
  br i1 %t0, label %then0, label %merge2
then0:
  store i32 0, ptr %t1
  %t2 = getelementptr i8, ptr %t1, i64 4
  store i32 %operand, ptr %t2
  %t4 = load %enum.Op, ptr %t1
  ret %enum.Op %t4
merge2:
  %t5 = icmp eq i32 %tag, 1
  br i1 %t5, label %then3, label %merge5
then3:
  store i32 1, ptr %t6
  %t8 = load %enum.Op, ptr %t6
  ret %enum.Op %t8
merge5:
  %t9 = icmp eq i32 %tag, 2
  br i1 %t9, label %then6, label %merge8
then6:
  store i32 2, ptr %t10
  %t12 = load %enum.Op, ptr %t10
  ret %enum.Op %t12
merge8:
  %t13 = icmp eq i32 %tag, 3
  br i1 %t13, label %then9, label %merge11
then9:
  store i32 3, ptr %t14
  %t16 = load %enum.Op, ptr %t14
  ret %enum.Op %t16
merge11:
  %t17 = icmp eq i32 %tag, 4
  br i1 %t17, label %then12, label %merge14
then12:
  store i32 4, ptr %t18
  %t20 = load %enum.Op, ptr %t18
  ret %enum.Op %t20
merge14:
  %t21 = icmp eq i32 %tag, 5
  br i1 %t21, label %then15, label %merge17
then15:
  store i32 5, ptr %t22
  %t24 = load %enum.Op, ptr %t22
  ret %enum.Op %t24
merge17:
  %t25 = icmp eq i32 %tag, 6
  br i1 %t25, label %then18, label %merge20
then18:
  store i32 6, ptr %t26
  %t28 = load %enum.Op, ptr %t26
  ret %enum.Op %t28
merge20:
  %t29 = icmp eq i32 %tag, 7
  br i1 %t29, label %then21, label %merge23
then21:
  store i32 7, ptr %t30
  %t31 = getelementptr i8, ptr %t30, i64 4
  store i32 %operand, ptr %t31
  %t33 = load %enum.Op, ptr %t30
  ret %enum.Op %t33
merge23:
  %t34 = icmp eq i32 %tag, 8
  br i1 %t34, label %then24, label %merge26
then24:
  store i32 8, ptr %t35
  %t36 = getelementptr i8, ptr %t35, i64 4
  store i32 %operand, ptr %t36
  %t38 = load %enum.Op, ptr %t35
  ret %enum.Op %t38
merge26:
  %t39 = icmp eq i32 %tag, 9
  br i1 %t39, label %then27, label %merge29
then27:
  store i32 9, ptr %t40
  %t41 = getelementptr i8, ptr %t40, i64 4
  store i32 %operand, ptr %t41
  %t43 = load %enum.Op, ptr %t40
  ret %enum.Op %t43
merge29:
  store i32 10, ptr %t44
  %t46 = load %enum.Op, ptr %t44
  ret %enum.Op %t46
}

define void @push(ptr %stack, ptr %sp, i32 %val) {
entry:
  %ssa.t6 = alloca i32
  %ssa.t7 = alloca i32
  %t0 = load i32, ptr %sp
  %t1 = sext i32 %t0 to i64
  %t2 = call i64 @vec_len(ptr %stack)
  %t3 = icmp sge i64 %t1, %t2
  br i1 %t3, label %then0, label %else1
then0:
  store i32 %val, ptr %ssa.t6
  call void @vec_push_4(ptr %stack, ptr %ssa.t6)
  br label %merge2
else1:
  store i32 %val, ptr %ssa.t7
  call void @vec_set_4(ptr %stack, i64 %t1, ptr %ssa.t7)
  br label %merge2
merge2:
  %t4 = load i32, ptr %sp
  %t5 = add i32 %t4, 1
  store i32 %t5, ptr %sp
  ret void
}

define i32 @pop(ptr %stack, ptr %sp) {
entry:
  %t0 = load i32, ptr %sp
  %t1 = sub i32 %t0, 1
  store i32 %t1, ptr %sp
  %t3 = sext i32 %t1 to i64
  %ssa.t8 = call ptr @vec_get_4(ptr %stack, i64 %t3)
  %t4 = load i32, ptr %ssa.t8
  ret i32 %t4
}

define i32 @top(ptr %stack, i32 %sp) {
entry:
  %t0 = sub i32 %sp, 1
  %t1 = sext i32 %t0 to i64
  %ssa.t9 = call ptr @vec_get_4(ptr %stack, i64 %t1)
  %t2 = load i32, ptr %ssa.t9
  ret i32 %t2
}

define i32 @verify_opcodes() {
entry:
  %t0 = alloca %enum.Op
  %borrow.4 = alloca %enum.Op
  %borrow.7 = alloca %enum.Op
  %t10 = alloca %enum.Op
  %borrow.13 = alloca %enum.Op
  %t16 = alloca %enum.Op
  %borrow.19 = alloca %enum.Op
  %t22 = alloca %enum.Op
  %borrow.25 = alloca %enum.Op
  %t28 = alloca %enum.Op
  %borrow.31 = alloca %enum.Op
  %t34 = alloca %enum.Op
  %borrow.37 = alloca %enum.Op
  %t40 = alloca %enum.Op
  %borrow.43 = alloca %enum.Op
  %t46 = alloca %enum.Op
  %borrow.50 = alloca %enum.Op
  %borrow.53 = alloca %enum.Op
  %t56 = alloca %enum.Op
  %borrow.60 = alloca %enum.Op
  %t63 = alloca %enum.Op
  %borrow.67 = alloca %enum.Op
  %t70 = alloca %enum.Op
  %borrow.73 = alloca %enum.Op
  store i32 0, ptr %t0
  %t1 = getelementptr i8, ptr %t0, i64 4
  store i32 42, ptr %t1
  %t3 = load %enum.Op, ptr %t0
  store %enum.Op %t3, ptr %borrow.4
  %t5 = call i32 @tag_of(ptr %borrow.4)
  %t6 = icmp ne i32 %t5, 0
  br i1 %t6, label %then0, label %merge2
then0:
  ret i32 1
merge2:
  store %enum.Op %t3, ptr %borrow.7
  %t8 = call i32 @operand_of(ptr %borrow.7)
  %t9 = icmp ne i32 %t8, 42
  br i1 %t9, label %then3, label %merge5
then3:
  ret i32 2
merge5:
  store i32 1, ptr %t10
  %t12 = load %enum.Op, ptr %t10
  store %enum.Op %t12, ptr %borrow.13
  %t14 = call i32 @tag_of(ptr %borrow.13)
  %t15 = icmp ne i32 %t14, 1
  br i1 %t15, label %then6, label %merge8
then6:
  ret i32 3
merge8:
  store i32 2, ptr %t16
  %t18 = load %enum.Op, ptr %t16
  store %enum.Op %t18, ptr %borrow.19
  %t20 = call i32 @tag_of(ptr %borrow.19)
  %t21 = icmp ne i32 %t20, 2
  br i1 %t21, label %then9, label %merge11
then9:
  ret i32 4
merge11:
  store i32 3, ptr %t22
  %t24 = load %enum.Op, ptr %t22
  store %enum.Op %t24, ptr %borrow.25
  %t26 = call i32 @tag_of(ptr %borrow.25)
  %t27 = icmp ne i32 %t26, 3
  br i1 %t27, label %then12, label %merge14
then12:
  ret i32 5
merge14:
  store i32 4, ptr %t28
  %t30 = load %enum.Op, ptr %t28
  store %enum.Op %t30, ptr %borrow.31
  %t32 = call i32 @tag_of(ptr %borrow.31)
  %t33 = icmp ne i32 %t32, 4
  br i1 %t33, label %then15, label %merge17
then15:
  ret i32 6
merge17:
  store i32 5, ptr %t34
  %t36 = load %enum.Op, ptr %t34
  store %enum.Op %t36, ptr %borrow.37
  %t38 = call i32 @tag_of(ptr %borrow.37)
  %t39 = icmp ne i32 %t38, 5
  br i1 %t39, label %then18, label %merge20
then18:
  ret i32 7
merge20:
  store i32 6, ptr %t40
  %t42 = load %enum.Op, ptr %t40
  store %enum.Op %t42, ptr %borrow.43
  %t44 = call i32 @tag_of(ptr %borrow.43)
  %t45 = icmp ne i32 %t44, 6
  br i1 %t45, label %then21, label %merge23
then21:
  ret i32 8
merge23:
  store i32 7, ptr %t46
  %t47 = getelementptr i8, ptr %t46, i64 4
  store i32 99, ptr %t47
  %t49 = load %enum.Op, ptr %t46
  store %enum.Op %t49, ptr %borrow.50
  %t51 = call i32 @tag_of(ptr %borrow.50)
  %t52 = icmp ne i32 %t51, 7
  br i1 %t52, label %then24, label %merge26
then24:
  ret i32 9
merge26:
  store %enum.Op %t49, ptr %borrow.53
  %t54 = call i32 @operand_of(ptr %borrow.53)
  %t55 = icmp ne i32 %t54, 99
  br i1 %t55, label %then27, label %merge29
then27:
  ret i32 10
merge29:
  store i32 8, ptr %t56
  %t57 = getelementptr i8, ptr %t56, i64 4
  store i32 1, ptr %t57
  %t59 = load %enum.Op, ptr %t56
  store %enum.Op %t59, ptr %borrow.60
  %t61 = call i32 @tag_of(ptr %borrow.60)
  %t62 = icmp ne i32 %t61, 8
  br i1 %t62, label %then30, label %merge32
then30:
  ret i32 11
merge32:
  store i32 9, ptr %t63
  %t64 = getelementptr i8, ptr %t63, i64 4
  store i32 0, ptr %t64
  %t66 = load %enum.Op, ptr %t63
  store %enum.Op %t66, ptr %borrow.67
  %t68 = call i32 @tag_of(ptr %borrow.67)
  %t69 = icmp ne i32 %t68, 9
  br i1 %t69, label %then33, label %merge35
then33:
  ret i32 12
merge35:
  store i32 10, ptr %t70
  %t72 = load %enum.Op, ptr %t70
  store %enum.Op %t72, ptr %borrow.73
  %t74 = call i32 @tag_of(ptr %borrow.73)
  %t75 = icmp ne i32 %t74, 10
  br i1 %t75, label %then36, label %merge38
then36:
  ret i32 13
merge38:
  ret i32 0
}

define void @emit(ptr %prog, i32 %tag, i32 %operand) {
entry:
  %ssa.t10 = alloca i32
  %ssa.t11 = alloca i32
  store i32 %tag, ptr %ssa.t10
  call void @vec_push_4(ptr %prog, ptr %ssa.t10)
  store i32 %operand, ptr %ssa.t11
  call void @vec_push_4(ptr %prog, ptr %ssa.t11)
  ret void
}

define i64 @user_main() {
entry:
  %mutref.5 = alloca %struct.Vec
  %mutref.7 = alloca %struct.Vec
  %mutref.9 = alloca %struct.Vec
  %mutref.11 = alloca %struct.Vec
  %mutref.13 = alloca %struct.Vec
  %mutref.15 = alloca %struct.Vec
  %mutref.17 = alloca %struct.Vec
  %mutref.19 = alloca %struct.Vec
  %mutref.21 = alloca %struct.Vec
  %mutref.23 = alloca %struct.Vec
  %mutref.25 = alloca %struct.Vec
  %mutref.27 = alloca %struct.Vec
  %mutref.29 = alloca %struct.Vec
  %mutref.31 = alloca %struct.Vec
  %mutref.33 = alloca %struct.Vec
  %mutref.35 = alloca %struct.Vec
  %mutref.37 = alloca %struct.Vec
  %mutref.39 = alloca %struct.Vec
  %mutref.41 = alloca %struct.Vec
  %mutref.43 = alloca %struct.Vec
  %mutref.45 = alloca %struct.Vec
  %agg.54 = alloca %struct.Vec
  %agg.55 = alloca %struct.Vec
  %mutref.78 = alloca %struct.Vec
  %mutref.79 = alloca i32
  %mutref.86 = alloca i32
  %mutref.93 = alloca i32
  %mutref.98 = alloca i32
  %mutref.102 = alloca %struct.Vec
  %mutref.103 = alloca i32
  %mutref.111 = alloca i32
  %mutref.116 = alloca i32
  %mutref.120 = alloca %struct.Vec
  %mutref.121 = alloca i32
  %mutref.129 = alloca i32
  %mutref.134 = alloca i32
  %mutref.138 = alloca %struct.Vec
  %mutref.139 = alloca i32
  %mutref.149 = alloca %struct.Vec
  %mutref.150 = alloca i32
  %mutref.157 = alloca i32
  %mutref.162 = alloca i32
  %mutref.166 = alloca %struct.Vec
  %mutref.167 = alloca i32
  %mutref.171 = alloca %struct.Vec
  %mutref.172 = alloca i32
  %mutref.179 = alloca i32
  %mutref.185 = alloca %struct.Vec
  %mutref.186 = alloca i32
  %borrow.47 = alloca %struct.Vec
  %ssa.t12 = alloca %struct.Vec
  %borrow.70 = alloca %struct.Vec
  %borrow.73 = alloca %struct.Vec
  %borrow.85 = alloca %struct.Vec
  %borrow.92 = alloca %struct.Vec
  %borrow.97 = alloca %struct.Vec
  %borrow.110 = alloca %struct.Vec
  %borrow.115 = alloca %struct.Vec
  %borrow.128 = alloca %struct.Vec
  %borrow.133 = alloca %struct.Vec
  %borrow.146 = alloca %struct.Vec
  %borrow.156 = alloca %struct.Vec
  %borrow.161 = alloca %struct.Vec
  %borrow.178 = alloca %struct.Vec
  %ssa.t15 = alloca %struct.Vec
  %ssa.t16 = alloca %struct.Vec
  %ssa.t17 = alloca %struct.Vec
  %ssa.t18 = alloca %struct.Vec
  %ssa.t19 = alloca %struct.Vec
  %ssa.t20 = alloca %struct.Vec
  %borrow.243 = alloca %struct.Vec
  %ssa.t21 = alloca %struct.Vec
  %ssa.t22 = alloca %struct.Vec
  %t0 = call i32 @verify_opcodes()
  %t1 = icmp ne i32 %t0, 0
  br i1 %t1, label %then0, label %merge2
then0:
  %t2 = sext i32 %t0 to i64
  %t3 = add i64 %t2, 100
  ret i64 %t3
merge2:
  %t4 = call %struct.Vec @vec_new_4()
  store %struct.Vec %t4, ptr %mutref.5
  call void @emit(ptr %mutref.5, i32 0, i32 1)
  %wb.6 = load %struct.Vec, ptr %mutref.5
  store %struct.Vec %wb.6, ptr %mutref.7
  call void @emit(ptr %mutref.7, i32 0, i32 5)
  %wb.8 = load %struct.Vec, ptr %mutref.7
  store %struct.Vec %wb.8, ptr %mutref.9
  call void @emit(ptr %mutref.9, i32 4, i32 0)
  %wb.10 = load %struct.Vec, ptr %mutref.9
  store %struct.Vec %wb.10, ptr %mutref.11
  call void @emit(ptr %mutref.11, i32 0, i32 4)
  %wb.12 = load %struct.Vec, ptr %mutref.11
  store %struct.Vec %wb.12, ptr %mutref.13
  call void @emit(ptr %mutref.13, i32 4, i32 0)
  %wb.14 = load %struct.Vec, ptr %mutref.13
  store %struct.Vec %wb.14, ptr %mutref.15
  call void @emit(ptr %mutref.15, i32 0, i32 3)
  %wb.16 = load %struct.Vec, ptr %mutref.15
  store %struct.Vec %wb.16, ptr %mutref.17
  call void @emit(ptr %mutref.17, i32 4, i32 0)
  %wb.18 = load %struct.Vec, ptr %mutref.17
  store %struct.Vec %wb.18, ptr %mutref.19
  call void @emit(ptr %mutref.19, i32 0, i32 2)
  %wb.20 = load %struct.Vec, ptr %mutref.19
  store %struct.Vec %wb.20, ptr %mutref.21
  call void @emit(ptr %mutref.21, i32 4, i32 0)
  %wb.22 = load %struct.Vec, ptr %mutref.21
  store %struct.Vec %wb.22, ptr %mutref.23
  call void @emit(ptr %mutref.23, i32 8, i32 0)
  %wb.24 = load %struct.Vec, ptr %mutref.23
  store %struct.Vec %wb.24, ptr %mutref.25
  call void @emit(ptr %mutref.25, i32 0, i32 3)
  %wb.26 = load %struct.Vec, ptr %mutref.25
  store %struct.Vec %wb.26, ptr %mutref.27
  call void @emit(ptr %mutref.27, i32 0, i32 7)
  %wb.28 = load %struct.Vec, ptr %mutref.27
  store %struct.Vec %wb.28, ptr %mutref.29
  call void @emit(ptr %mutref.29, i32 2, i32 0)
  %wb.30 = load %struct.Vec, ptr %mutref.29
  store %struct.Vec %wb.30, ptr %mutref.31
  call void @emit(ptr %mutref.31, i32 5, i32 0)
  %wb.32 = load %struct.Vec, ptr %mutref.31
  store %struct.Vec %wb.32, ptr %mutref.33
  call void @emit(ptr %mutref.33, i32 2, i32 0)
  %wb.34 = load %struct.Vec, ptr %mutref.33
  store %struct.Vec %wb.34, ptr %mutref.35
  call void @emit(ptr %mutref.35, i32 9, i32 0)
  %wb.36 = load %struct.Vec, ptr %mutref.35
  store %struct.Vec %wb.36, ptr %mutref.37
  call void @emit(ptr %mutref.37, i32 6, i32 0)
  %wb.38 = load %struct.Vec, ptr %mutref.37
  store %struct.Vec %wb.38, ptr %mutref.39
  call void @emit(ptr %mutref.39, i32 3, i32 0)
  %wb.40 = load %struct.Vec, ptr %mutref.39
  store %struct.Vec %wb.40, ptr %mutref.41
  call void @emit(ptr %mutref.41, i32 0, i32 58)
  %wb.42 = load %struct.Vec, ptr %mutref.41
  store %struct.Vec %wb.42, ptr %mutref.43
  call void @emit(ptr %mutref.43, i32 3, i32 0)
  %wb.44 = load %struct.Vec, ptr %mutref.43
  store %struct.Vec %wb.44, ptr %mutref.45
  call void @emit(ptr %mutref.45, i32 10, i32 0)
  %wb.46 = load %struct.Vec, ptr %mutref.45
  store %struct.Vec %wb.46, ptr %borrow.47
  %t48 = call i64 @vec_len(ptr %borrow.47)
  %t49 = trunc i64 %t48 to i32
  %t50 = icmp ne i32 %t49, 42
  br i1 %t50, label %then3, label %merge5
then3:
  store %struct.Vec %wb.46, ptr %ssa.t12
  call void @vec_free(ptr %ssa.t12)
  ret i64 1
merge5:
  %t52 = call %struct.Vec @vec_new_4()
  %t53 = sdiv i32 %t49, 2
  store %struct.Vec %wb.46, ptr %agg.54
  store %struct.Vec %t52, ptr %agg.55
  br label %while.hdr6
while.hdr6:
  %phi.59 = phi i32 [0, %merge5], [%if.phi.230, %merge11]
  %phi.60 = phi i32 [0, %merge5], [%if.phi.231, %merge11]
  %phi.61 = phi i32 [0, %merge5], [%if.phi.232, %merge11]
  %phi.62 = phi i32 [0, %merge5], [%if.phi.233, %merge11]
  %phi.64 = phi i32 [0, %merge5], [%if.phi.234, %merge11]
  %t65 = icmp eq i32 %phi.62, 0
  br i1 %t65, label %while.body7, label %while.exit8
while.body7:
  %t66 = icmp sge i32 %phi.60, %t53
  br i1 %t66, label %then9, label %else10
then9:
  br label %merge11
else10:
  %t67 = shl i32 %phi.60, 1
  %t68 = sext i32 %t67 to i64
  %pload.69 = load %struct.Vec, ptr %agg.54
  store %struct.Vec %pload.69, ptr %borrow.70
  %ssa.t13 = call ptr @vec_get_4(ptr %borrow.70, i64 %t68)
  %t71 = load i32, ptr %ssa.t13
  %pload.72 = load %struct.Vec, ptr %agg.54
  store %struct.Vec %pload.72, ptr %borrow.73
  %t74 = add i64 %t68, 1
  %ssa.t14 = call ptr @vec_get_4(ptr %borrow.73, i64 %t74)
  %t75 = load i32, ptr %ssa.t14
  %t76 = icmp eq i32 %t71, 0
  br i1 %t76, label %then12, label %else13
then12:
  %pload.77 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.77, ptr %mutref.78
  store i32 %phi.59, ptr %mutref.79
  call void @push(ptr %mutref.78, ptr %mutref.79, i32 %t75)
  %wb.80 = load %struct.Vec, ptr %mutref.78
  store %struct.Vec %wb.80, ptr %agg.55
  %wb.81 = load i32, ptr %mutref.79
  %t82 = add i32 %phi.60, 1
  br label %merge14
else13:
  %t83 = icmp eq i32 %t71, 1
  br i1 %t83, label %then15, label %else16
then15:
  %pload.84 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.84, ptr %borrow.85
  store i32 %phi.59, ptr %mutref.86
  %t87 = call i32 @pop(ptr %borrow.85, ptr %mutref.86)
  %wb.88 = load i32, ptr %mutref.86
  %t89 = add i32 %phi.60, 1
  br label %merge17
else16:
  %t90 = icmp eq i32 %t71, 2
  br i1 %t90, label %then18, label %else19
then18:
  %pload.91 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.91, ptr %borrow.92
  store i32 %phi.59, ptr %mutref.93
  %t94 = call i32 @pop(ptr %borrow.92, ptr %mutref.93)
  %wb.95 = load i32, ptr %mutref.93
  %pload.96 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.96, ptr %borrow.97
  store i32 %wb.95, ptr %mutref.98
  %t99 = call i32 @pop(ptr %borrow.97, ptr %mutref.98)
  %wb.100 = load i32, ptr %mutref.98
  %pload.101 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.101, ptr %mutref.102
  store i32 %wb.100, ptr %mutref.103
  %t104 = add i32 %t99, %t94
  call void @push(ptr %mutref.102, ptr %mutref.103, i32 %t104)
  %wb.105 = load %struct.Vec, ptr %mutref.102
  store %struct.Vec %wb.105, ptr %agg.55
  %wb.106 = load i32, ptr %mutref.103
  %t107 = add i32 %phi.60, 1
  br label %merge20
else19:
  %t108 = icmp eq i32 %t71, 3
  br i1 %t108, label %then21, label %else22
then21:
  %pload.109 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.109, ptr %borrow.110
  store i32 %phi.59, ptr %mutref.111
  %t112 = call i32 @pop(ptr %borrow.110, ptr %mutref.111)
  %wb.113 = load i32, ptr %mutref.111
  %pload.114 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.114, ptr %borrow.115
  store i32 %wb.113, ptr %mutref.116
  %t117 = call i32 @pop(ptr %borrow.115, ptr %mutref.116)
  %wb.118 = load i32, ptr %mutref.116
  %pload.119 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.119, ptr %mutref.120
  store i32 %wb.118, ptr %mutref.121
  %t122 = sub i32 %t117, %t112
  call void @push(ptr %mutref.120, ptr %mutref.121, i32 %t122)
  %wb.123 = load %struct.Vec, ptr %mutref.120
  store %struct.Vec %wb.123, ptr %agg.55
  %wb.124 = load i32, ptr %mutref.121
  %t125 = add i32 %phi.60, 1
  br label %merge23
else22:
  %t126 = icmp eq i32 %t71, 4
  br i1 %t126, label %then24, label %else25
then24:
  %pload.127 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.127, ptr %borrow.128
  store i32 %phi.59, ptr %mutref.129
  %t130 = call i32 @pop(ptr %borrow.128, ptr %mutref.129)
  %wb.131 = load i32, ptr %mutref.129
  %pload.132 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.132, ptr %borrow.133
  store i32 %wb.131, ptr %mutref.134
  %t135 = call i32 @pop(ptr %borrow.133, ptr %mutref.134)
  %wb.136 = load i32, ptr %mutref.134
  %pload.137 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.137, ptr %mutref.138
  store i32 %wb.136, ptr %mutref.139
  %t140 = mul i32 %t135, %t130
  call void @push(ptr %mutref.138, ptr %mutref.139, i32 %t140)
  %wb.141 = load %struct.Vec, ptr %mutref.138
  store %struct.Vec %wb.141, ptr %agg.55
  %wb.142 = load i32, ptr %mutref.139
  %t143 = add i32 %phi.60, 1
  br label %merge26
else25:
  %t144 = icmp eq i32 %t71, 5
  br i1 %t144, label %then27, label %else28
then27:
  %pload.145 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.145, ptr %borrow.146
  %t147 = call i32 @top(ptr %borrow.146, i32 %phi.59)
  %pload.148 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.148, ptr %mutref.149
  store i32 %phi.59, ptr %mutref.150
  call void @push(ptr %mutref.149, ptr %mutref.150, i32 %t147)
  %wb.151 = load %struct.Vec, ptr %mutref.149
  store %struct.Vec %wb.151, ptr %agg.55
  %wb.152 = load i32, ptr %mutref.150
  %t153 = add i32 %phi.60, 1
  br label %merge29
else28:
  %t154 = icmp eq i32 %t71, 6
  br i1 %t154, label %then30, label %else31
then30:
  %pload.155 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.155, ptr %borrow.156
  store i32 %phi.59, ptr %mutref.157
  %t158 = call i32 @pop(ptr %borrow.156, ptr %mutref.157)
  %wb.159 = load i32, ptr %mutref.157
  %pload.160 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.160, ptr %borrow.161
  store i32 %wb.159, ptr %mutref.162
  %t163 = call i32 @pop(ptr %borrow.161, ptr %mutref.162)
  %wb.164 = load i32, ptr %mutref.162
  %pload.165 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.165, ptr %mutref.166
  store i32 %wb.164, ptr %mutref.167
  call void @push(ptr %mutref.166, ptr %mutref.167, i32 %t158)
  %wb.168 = load %struct.Vec, ptr %mutref.166
  store %struct.Vec %wb.168, ptr %agg.55
  %wb.169 = load i32, ptr %mutref.167
  store %struct.Vec %wb.168, ptr %mutref.171
  store i32 %wb.169, ptr %mutref.172
  call void @push(ptr %mutref.171, ptr %mutref.172, i32 %t163)
  %wb.173 = load %struct.Vec, ptr %mutref.171
  store %struct.Vec %wb.173, ptr %agg.55
  %wb.174 = load i32, ptr %mutref.172
  %t175 = add i32 %phi.60, 1
  br label %merge32
else31:
  %t176 = icmp eq i32 %t71, 8
  br i1 %t176, label %then33, label %else34
then33:
  %pload.177 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.177, ptr %borrow.178
  store i32 %phi.59, ptr %mutref.179
  %t180 = call i32 @pop(ptr %borrow.178, ptr %mutref.179)
  %wb.181 = load i32, ptr %mutref.179
  %t182 = add i32 %phi.60, 1
  br label %merge35
else34:
  %t183 = icmp eq i32 %t71, 9
  br i1 %t183, label %then36, label %else37
then36:
  %pload.184 = load %struct.Vec, ptr %agg.55
  store %struct.Vec %pload.184, ptr %mutref.185
  store i32 %phi.59, ptr %mutref.186
  call void @push(ptr %mutref.185, ptr %mutref.186, i32 %phi.61)
  %wb.187 = load %struct.Vec, ptr %mutref.185
  store %struct.Vec %wb.187, ptr %agg.55
  %wb.188 = load i32, ptr %mutref.186
  %t189 = add i32 %phi.60, 1
  br label %merge38
else37:
  %t190 = icmp eq i32 %t71, 10
  br i1 %t190, label %then39, label %else40
then39:
  br label %merge41
else40:
  %t191 = add i32 %phi.60, 1
  br label %merge41
merge41:
  %if.phi.192 = phi i32 [%phi.60, %then39], [%t191, %else40]
  %if.phi.193 = phi i32 [1, %then39], [%phi.62, %else40]
  br label %merge38
merge38:
  %if.phi.194 = phi i32 [%wb.188, %then36], [%phi.59, %merge41]
  %if.phi.195 = phi i32 [%t189, %then36], [%if.phi.192, %merge41]
  %if.phi.196 = phi i32 [%phi.62, %then36], [%if.phi.193, %merge41]
  br label %merge35
merge35:
  %if.phi.197 = phi i32 [%wb.181, %then33], [%if.phi.194, %merge38]
  %if.phi.198 = phi i32 [%t182, %then33], [%if.phi.195, %merge38]
  %if.phi.199 = phi i32 [%t180, %then33], [%phi.61, %merge38]
  %if.phi.200 = phi i32 [%phi.62, %then33], [%if.phi.196, %merge38]
  br label %merge32
merge32:
  %if.phi.201 = phi i32 [%wb.174, %then30], [%if.phi.197, %merge35]
  %if.phi.202 = phi i32 [%t175, %then30], [%if.phi.198, %merge35]
  %if.phi.203 = phi i32 [%phi.61, %then30], [%if.phi.199, %merge35]
  %if.phi.204 = phi i32 [%phi.62, %then30], [%if.phi.200, %merge35]
  br label %merge29
merge29:
  %if.phi.205 = phi i32 [%wb.152, %then27], [%if.phi.201, %merge32]
  %if.phi.206 = phi i32 [%t153, %then27], [%if.phi.202, %merge32]
  %if.phi.207 = phi i32 [%phi.61, %then27], [%if.phi.203, %merge32]
  %if.phi.208 = phi i32 [%phi.62, %then27], [%if.phi.204, %merge32]
  br label %merge26
merge26:
  %if.phi.209 = phi i32 [%wb.142, %then24], [%if.phi.205, %merge29]
  %if.phi.210 = phi i32 [%t143, %then24], [%if.phi.206, %merge29]
  %if.phi.211 = phi i32 [%phi.61, %then24], [%if.phi.207, %merge29]
  %if.phi.212 = phi i32 [%phi.62, %then24], [%if.phi.208, %merge29]
  br label %merge23
merge23:
  %if.phi.213 = phi i32 [%wb.124, %then21], [%if.phi.209, %merge26]
  %if.phi.214 = phi i32 [%t125, %then21], [%if.phi.210, %merge26]
  %if.phi.215 = phi i32 [%phi.61, %then21], [%if.phi.211, %merge26]
  %if.phi.216 = phi i32 [%phi.62, %then21], [%if.phi.212, %merge26]
  br label %merge20
merge20:
  %if.phi.217 = phi i32 [%wb.106, %then18], [%if.phi.213, %merge23]
  %if.phi.218 = phi i32 [%t107, %then18], [%if.phi.214, %merge23]
  %if.phi.219 = phi i32 [%phi.61, %then18], [%if.phi.215, %merge23]
  %if.phi.220 = phi i32 [%phi.62, %then18], [%if.phi.216, %merge23]
  br label %merge17
merge17:
  %if.phi.221 = phi i32 [%wb.88, %then15], [%if.phi.217, %merge20]
  %if.phi.222 = phi i32 [%t89, %then15], [%if.phi.218, %merge20]
  %if.phi.223 = phi i32 [%phi.61, %then15], [%if.phi.219, %merge20]
  %if.phi.224 = phi i32 [%phi.62, %then15], [%if.phi.220, %merge20]
  br label %merge14
merge14:
  %if.phi.225 = phi i32 [%wb.81, %then12], [%if.phi.221, %merge17]
  %if.phi.226 = phi i32 [%t82, %then12], [%if.phi.222, %merge17]
  %if.phi.227 = phi i32 [%phi.61, %then12], [%if.phi.223, %merge17]
  %if.phi.228 = phi i32 [%phi.62, %then12], [%if.phi.224, %merge17]
  %t229 = add i32 %phi.64, 1
  br label %merge11
merge11:
  %if.phi.230 = phi i32 [%phi.59, %then9], [%if.phi.225, %merge14]
  %if.phi.231 = phi i32 [%phi.60, %then9], [%if.phi.226, %merge14]
  %if.phi.232 = phi i32 [%phi.61, %then9], [%if.phi.227, %merge14]
  %if.phi.233 = phi i32 [1, %then9], [%if.phi.228, %merge14]
  %if.phi.234 = phi i32 [%phi.64, %then9], [%t229, %merge14]
  br label %while.hdr6
while.exit8:
  %unpro.235 = load %struct.Vec, ptr %agg.54
  %unpro.236 = load %struct.Vec, ptr %agg.55
  %t237 = icmp ne i32 %phi.64, 21
  br i1 %t237, label %then42, label %merge44
then42:
  store %struct.Vec %unpro.236, ptr %ssa.t15
  call void @vec_free(ptr %ssa.t15)
  store %struct.Vec %unpro.235, ptr %ssa.t16
  call void @vec_free(ptr %ssa.t16)
  ret i64 2
merge44:
  %t239 = icmp ne i32 %phi.59, 1
  br i1 %t239, label %then45, label %merge47
then45:
  store %struct.Vec %unpro.236, ptr %ssa.t17
  call void @vec_free(ptr %ssa.t17)
  store %struct.Vec %unpro.235, ptr %ssa.t18
  call void @vec_free(ptr %ssa.t18)
  ret i64 3
merge47:
  %t241 = icmp ne i32 %phi.61, 120
  br i1 %t241, label %then48, label %merge50
then48:
  store %struct.Vec %unpro.236, ptr %ssa.t19
  call void @vec_free(ptr %ssa.t19)
  store %struct.Vec %unpro.235, ptr %ssa.t20
  call void @vec_free(ptr %ssa.t20)
  ret i64 4
merge50:
  store %struct.Vec %unpro.236, ptr %borrow.243
  %t244 = call i32 @top(ptr %borrow.243, i32 %phi.59)
  store %struct.Vec %unpro.236, ptr %ssa.t21
  call void @vec_free(ptr %ssa.t21)
  store %struct.Vec %unpro.235, ptr %ssa.t22
  call void @vec_free(ptr %ssa.t22)
  %t245 = sext i32 %t244 to i64
  ret i64 %t245
}

define i32 @__concrete_get_argc() {
entry:
  %argc = load i32, ptr @__concrete_argc
  ret i32 %argc
}

define ptr @__concrete_get_argv(i32 %idx) {
entry:
  %argv = load ptr, ptr @__concrete_argv
  %idx64 = sext i32 %idx to i64
  %argp = getelementptr ptr, ptr %argv, i64 %idx64
  %arg = load ptr, ptr %argp
  ret ptr %arg
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  store i32 %argc, ptr @__concrete_argc
  store ptr %argv, ptr @__concrete_argv
  %result = call i64 @user_main()
  %fmt = getelementptr [6 x i8], ptr @fmt.main, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %fmt, i64 %result)
  ret i32 0
}

define ptr @__concrete_check_oom(ptr %p) {
entry:
  %is_null = icmp eq ptr %p, null
  br i1 %is_null, label %oom, label %ok
oom:
  call void @abort()
  unreachable
ok:
  ret ptr %p
}

define i64 @string_length(ptr %s) {
entry:
  %len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len = load i64, ptr %len_ptr
  ret i64 %len
}

define void @drop_string(ptr %s) {
entry:
  %data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data = load ptr, ptr %data_ptr
  call void @free(ptr %data)
  ret void
}

define %struct.String @string_concat(ptr %a, ptr %b) {
entry:
  %a_data_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 0
  %a_data = load ptr, ptr %a_data_ptr
  %a_len_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 1
  %a_len = load i64, ptr %a_len_ptr
  %b_data_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 0
  %b_data = load ptr, ptr %b_data_ptr
  %b_len_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 1
  %b_len = load i64, ptr %b_len_ptr
  %total_len = add i64 %a_len, %b_len
  %buf.raw = call ptr @malloc(i64 %total_len)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %buf, ptr %a_data, i64 %a_len, i1 false)
  %dst = getelementptr i8, ptr %buf, i64 %a_len
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %b_data, i64 %b_len, i1 false)
  call void @free(ptr %a_data)
  call void @free(ptr %b_data)
  %sc_alloca = alloca %struct.String
  %sc_data_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 0
  store ptr %buf, ptr %sc_data_ptr
  %sc_len_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 1
  store i64 %total_len, ptr %sc_len_ptr
  %sc_cap_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 2
  store i64 %total_len, ptr %sc_cap_ptr
  %sc_result = load %struct.String, ptr %sc_alloca
  ret %struct.String %sc_result
}

define %struct.String @string_slice(ptr %s, i64 %start, i64 %end_) {
entry:
  %len_ptr.ss = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len.ss = load i64, ptr %len_ptr.ss
  %s_clamped = call i64 @llvm.smax.i64(i64 %start, i64 0)
  %s_min = call i64 @llvm.smin.i64(i64 %s_clamped, i64 %len.ss)
  %e_clamped = call i64 @llvm.smax.i64(i64 %end_, i64 0)
  %e_min = call i64 @llvm.smin.i64(i64 %e_clamped, i64 %len.ss)
  %e_final = call i64 @llvm.smax.i64(i64 %e_min, i64 %s_min)
  %slice_len = sub i64 %e_final, %s_min
  %slice_buf.raw = call ptr @malloc(i64 %slice_len)
  %slice_buf = call ptr @__concrete_check_oom(ptr %slice_buf.raw)
  %data_ptr.ss = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data.ss = load ptr, ptr %data_ptr.ss
  %src = getelementptr i8, ptr %data.ss, i64 %s_min
  call void @llvm.memcpy.p0.p0.i64(ptr %slice_buf, ptr %src, i64 %slice_len, i1 false)
  %res.ss = alloca %struct.String
  %res_d.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 0
  store ptr %slice_buf, ptr %res_d.ss
  %res_l.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 1
  store i64 %slice_len, ptr %res_l.ss
  %res_c.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 2
  store i64 %slice_len, ptr %res_c.ss
  %result.ss = load %struct.String, ptr %res.ss
  ret %struct.String %result.ss
}

define %struct.String @string_substr(ptr %s, i64 %start, i64 %len) {
entry:
  %end_ = add i64 %start, %len
  %result.ssub = call %struct.String @string_slice(ptr %s, i64 %start, i64 %end_)
  ret %struct.String %result.ssub
}

define i64 @string_char_at(ptr %s, i64 %index) {
entry:
  %len_ptr.sca = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len.sca = load i64, ptr %len_ptr.sca
  %neg = icmp slt i64 %index, 0
  %oob = icmp sge i64 %index, %len.sca
  %bad = or i1 %neg, %oob
  br i1 %bad, label %ret_neg, label %ok_idx
ret_neg:
  ret i64 -1
ok_idx:
  %data_ptr.sca = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data.sca = load ptr, ptr %data_ptr.sca
  %char_ptr = getelementptr i8, ptr %data.sca, i64 %index
  %byte = load i8, ptr %char_ptr
  %char = zext i8 %byte to i64
  ret i64 %char
}

define i1 @string_contains(ptr %haystack, ptr %needle) {
entry:
  %h_data_ptr = getelementptr %struct.String, ptr %haystack, i32 0, i32 0
  %h_data = load ptr, ptr %h_data_ptr
  %h_len_ptr = getelementptr %struct.String, ptr %haystack, i32 0, i32 1
  %h_len = load i64, ptr %h_len_ptr
  %n_data_ptr = getelementptr %struct.String, ptr %needle, i32 0, i32 0
  %n_data = load ptr, ptr %n_data_ptr
  %n_len_ptr = getelementptr %struct.String, ptr %needle, i32 0, i32 1
  %n_len = load i64, ptr %n_len_ptr
  %n_empty = icmp eq i64 %n_len, 0
  br i1 %n_empty, label %found, label %check_len
check_len:
  %too_long = icmp ugt i64 %n_len, %h_len
  br i1 %too_long, label %not_found, label %loop_start
loop_start:
  %max_i = sub i64 %h_len, %n_len
  br label %loop
loop:
  %i = phi i64 [0, %loop_start], [%i_next, %loop_cont]
  %h_ptr = getelementptr i8, ptr %h_data, i64 %i
  %cmp = call i32 @memcmp(ptr %h_ptr, ptr %n_data, i64 %n_len)
  %match = icmp eq i32 %cmp, 0
  br i1 %match, label %found, label %loop_cont
loop_cont:
  %i_next = add i64 %i, 1
  %done = icmp ugt i64 %i_next, %max_i
  br i1 %done, label %not_found, label %loop
found:
  ret i1 1
not_found:
  ret i1 0
}

define i1 @string_eq(ptr %a, ptr %b) {
entry:
  %a_len_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 1
  %a_len = load i64, ptr %a_len_ptr
  %b_len_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 1
  %b_len = load i64, ptr %b_len_ptr
  %len_eq = icmp eq i64 %a_len, %b_len
  br i1 %len_eq, label %cmp_data, label %not_eq
cmp_data:
  %zero_len = icmp eq i64 %a_len, 0
  br i1 %zero_len, label %eq, label %do_cmp
do_cmp:
  %a_data_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 0
  %a_data = load ptr, ptr %a_data_ptr
  %b_data_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 0
  %b_data = load ptr, ptr %b_data_ptr
  %cmp_res = call i32 @memcmp(ptr %a_data, ptr %b_data, i64 %a_len)
  %eq_data = icmp eq i32 %cmp_res, 0
  br i1 %eq_data, label %eq, label %not_eq
eq:
  ret i1 1
not_eq:
  ret i1 0
}

define %struct.String @int_to_string(i64 %n) {
entry:
  %buf.raw = call ptr @malloc(i64 32)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  %fmt_its = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %buf, i64 32, ptr %fmt_its, i64 %n)
  %wext = sext i32 %written to i64
  %res.its = alloca %struct.String
  %res_d.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 0
  store ptr %buf, ptr %res_d.its
  %res_l.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 1
  store i64 %wext, ptr %res_l.its
  %res_c.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 2
  store i64 32, ptr %res_c.its
  %result.its = load %struct.String, ptr %res.its
  ret %struct.String %result.its
}

define %enum.Result @string_to_int(ptr %s) {
entry:
  %sti_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sti_data = load ptr, ptr %sti_data_ptr
  %sti_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sti_len = load i64, ptr %sti_len_ptr
  %sti_buf_sz = add i64 %sti_len, 1
  %sti_buf.raw = call ptr @malloc(i64 %sti_buf_sz)
  %sti_buf = call ptr @__concrete_check_oom(ptr %sti_buf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %sti_buf, ptr %sti_data, i64 %sti_len, i1 false)
  %sti_null = getelementptr i8, ptr %sti_buf, i64 %sti_len
  store i8 0, ptr %sti_null
  %endptr_alloca = alloca ptr
  %sti_val = call i64 @strtol(ptr %sti_buf, ptr %endptr_alloca, i32 10)
  %endptr = load ptr, ptr %endptr_alloca
  %end_expected = getelementptr i8, ptr %sti_buf, i64 %sti_len
  %valid = icmp eq ptr %endptr, %end_expected
  %empty_input = icmp eq i64 %sti_len, 0
  %not_empty = xor i1 %empty_input, 1
  %final_ok = and i1 %valid, %not_empty
  call void @free(ptr %sti_buf)
  %res.sti = alloca %enum.Result
  br i1 %final_ok, label %sti_ok, label %sti_err
sti_ok:
  store i32 0, ptr %res.sti
  %data_ptr.sti_ok = getelementptr i8, ptr %res.sti, i64 8
  store i64 %sti_val, ptr %data_ptr.sti_ok
  br label %sti_done
sti_err:
  store i32 1, ptr %res.sti
  %data_ptr.sti_err = getelementptr i8, ptr %res.sti, i64 8
  store i64 1, ptr %data_ptr.sti_err
  br label %sti_done
sti_done:
  %result.sti = load %enum.Result, ptr %res.sti
  ret %enum.Result %result.sti
}

define %struct.String @bool_to_string(i1 %b) {
entry:
  br i1 %b, label %bts_true, label %bts_false
bts_true:
  %tbuf.raw = call ptr @malloc(i64 4)
  %tbuf = call ptr @__concrete_check_oom(ptr %tbuf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %tbuf, ptr @.str_true, i64 4, i1 false)
  %tres = alloca %struct.String
  %td = getelementptr %struct.String, ptr %tres, i32 0, i32 0
  store ptr %tbuf, ptr %td
  %tl = getelementptr %struct.String, ptr %tres, i32 0, i32 1
  store i64 4, ptr %tl
  %tc = getelementptr %struct.String, ptr %tres, i32 0, i32 2
  store i64 4, ptr %tc
  %tresult = load %struct.String, ptr %tres
  ret %struct.String %tresult
bts_false:
  %fbuf.raw = call ptr @malloc(i64 5)
  %fbuf = call ptr @__concrete_check_oom(ptr %fbuf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %fbuf, ptr @.str_false, i64 5, i1 false)
  %fres = alloca %struct.String
  %fd = getelementptr %struct.String, ptr %fres, i32 0, i32 0
  store ptr %fbuf, ptr %fd
  %fl = getelementptr %struct.String, ptr %fres, i32 0, i32 1
  store i64 5, ptr %fl
  %fc = getelementptr %struct.String, ptr %fres, i32 0, i32 2
  store i64 5, ptr %fc
  %fresult = load %struct.String, ptr %fres
  ret %struct.String %fresult
}

define %struct.String @float_to_string(double %f) {
entry:
  %fbuf.fts.raw = call ptr @malloc(i64 64)
  %fbuf.fts = call ptr @__concrete_check_oom(ptr %fbuf.fts.raw)
  %fmt.fts = getelementptr [3 x i8], ptr @.fmt_f, i64 0, i64 0
  %written.fts = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %fbuf.fts, i64 64, ptr %fmt.fts, double %f)
  %wext.fts = sext i32 %written.fts to i64
  %res.fts = alloca %struct.String
  %res_d.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 0
  store ptr %fbuf.fts, ptr %res_d.fts
  %res_l.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 1
  store i64 %wext.fts, ptr %res_l.fts
  %res_c.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 2
  store i64 64, ptr %res_c.fts
  %result.fts = load %struct.String, ptr %res.fts
  ret %struct.String %result.fts
}

define %struct.String @string_trim(ptr %s) {
entry:
  %st_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %st_data = load ptr, ptr %st_data_ptr
  %st_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %st_len = load i64, ptr %st_len_ptr
  br label %trim_left
trim_left:
  %tl_i = phi i64 [0, %entry], [%tl_next, %tl_ws]
  %tl_done = icmp uge i64 %tl_i, %st_len
  br i1 %tl_done, label %trim_result, label %tl_check
tl_check:
  %tl_ptr = getelementptr i8, ptr %st_data, i64 %tl_i
  %tl_ch = load i8, ptr %tl_ptr
  %tl_is_sp = icmp eq i8 %tl_ch, 32
  %tl_is_tab = icmp eq i8 %tl_ch, 9
  %tl_is_nl = icmp eq i8 %tl_ch, 10
  %tl_is_cr = icmp eq i8 %tl_ch, 13
  %tl_w1 = or i1 %tl_is_sp, %tl_is_tab
  %tl_w2 = or i1 %tl_is_nl, %tl_is_cr
  %tl_is_ws = or i1 %tl_w1, %tl_w2
  br i1 %tl_is_ws, label %tl_ws, label %trim_right_init
tl_ws:
  %tl_next = add i64 %tl_i, 1
  br label %trim_left
trim_right_init:
  %tr_start = sub i64 %st_len, 1
  br label %trim_right
trim_right:
  %tr_i = phi i64 [%tr_start, %trim_right_init], [%tr_prev, %tr_ws]
  %tr_done = icmp ult i64 %tr_i, %tl_i
  br i1 %tr_done, label %trim_result, label %tr_check
tr_check:
  %tr_ptr = getelementptr i8, ptr %st_data, i64 %tr_i
  %tr_ch = load i8, ptr %tr_ptr
  %tr_is_sp = icmp eq i8 %tr_ch, 32
  %tr_is_tab = icmp eq i8 %tr_ch, 9
  %tr_is_nl = icmp eq i8 %tr_ch, 10
  %tr_is_cr = icmp eq i8 %tr_ch, 13
  %tr_w1 = or i1 %tr_is_sp, %tr_is_tab
  %tr_w2 = or i1 %tr_is_nl, %tr_is_cr
  %tr_is_ws = or i1 %tr_w1, %tr_w2
  br i1 %tr_is_ws, label %tr_ws, label %trim_result
tr_ws:
  %tr_prev = sub i64 %tr_i, 1
  br label %trim_right
trim_result:
  %tr_left = phi i64 [%tl_i, %trim_left], [%tl_i, %trim_right], [%tl_i, %tr_check]
  %tr_right_raw = phi i64 [0, %trim_left], [%tl_i, %trim_right], [%tr_i, %tr_check]
  %tr_right = add i64 %tr_right_raw, 1
  %tr_empty = icmp uge i64 %tr_left, %tr_right
  br i1 %tr_empty, label %trim_empty, label %trim_copy
trim_empty:
  %te_buf.raw = call ptr @malloc(i64 1)
  %te_buf = call ptr @__concrete_check_oom(ptr %te_buf.raw)
  %te_res = alloca %struct.String
  %te_d = getelementptr %struct.String, ptr %te_res, i32 0, i32 0
  store ptr %te_buf, ptr %te_d
  %te_l = getelementptr %struct.String, ptr %te_res, i32 0, i32 1
  store i64 0, ptr %te_l
  %te_c = getelementptr %struct.String, ptr %te_res, i32 0, i32 2
  store i64 1, ptr %te_c
  %te_result = load %struct.String, ptr %te_res
  ret %struct.String %te_result
trim_copy:
  %tc_len = sub i64 %tr_right, %tr_left
  %tc_buf.raw = call ptr @malloc(i64 %tc_len)
  %tc_buf = call ptr @__concrete_check_oom(ptr %tc_buf.raw)
  %tc_src = getelementptr i8, ptr %st_data, i64 %tr_left
  call void @llvm.memcpy.p0.p0.i64(ptr %tc_buf, ptr %tc_src, i64 %tc_len, i1 false)
  %tc_res = alloca %struct.String
  %tc_d = getelementptr %struct.String, ptr %tc_res, i32 0, i32 0
  store ptr %tc_buf, ptr %tc_d
  %tc_l = getelementptr %struct.String, ptr %tc_res, i32 0, i32 1
  store i64 %tc_len, ptr %tc_l
  %tc_c = getelementptr %struct.String, ptr %tc_res, i32 0, i32 2
  store i64 %tc_len, ptr %tc_c
  %tc_result = load %struct.String, ptr %tc_res
  ret %struct.String %tc_result
}

define void @print_string(ptr %s) {
entry:
  %ps_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %ps_data = load ptr, ptr %ps_data_ptr
  %ps_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %ps_len = load i64, ptr %ps_len_ptr
  %ps_fmt = getelementptr [5 x i8], ptr @.fmt_str, i64 0, i64 0
  %ps_len32 = trunc i64 %ps_len to i32
  %ps_written = call i32 (ptr, ...) @printf(ptr %ps_fmt, i32 %ps_len32, ptr %ps_data)
  ret void
}

define void @print_int(i64 %n) {
entry:
  %pi_fmt = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %pi_written = call i32 (ptr, ...) @printf(ptr %pi_fmt, i64 %n)
  ret void
}

define void @print_char(i64 %c) {
entry:
  %pc_int = trunc i64 %c to i32
  %pc_wr = call i32 @putchar(i32 %pc_int)
  ret void
}

define void @print_bool(i1 %b) {
entry:
  %is_true = icmp eq i1 %b, 1
  br i1 %is_true, label %print_true, label %print_false
print_true:
  %true_ptr = getelementptr [5 x i8], ptr @.str_true, i64 0, i64 0
  %tw = call i32 (ptr, ...) @printf(ptr %true_ptr)
  ret void
print_false:
  %false_ptr = getelementptr [6 x i8], ptr @.str_false, i64 0, i64 0
  %fw = call i32 (ptr, ...) @printf(ptr %false_ptr)
  ret void
}

define void @string_push_char(ptr %s, i64 %c) {
entry:
  %spc_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %spc_len = load i64, ptr %spc_len_ptr
  %spc_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %spc_cap = load i64, ptr %spc_cap_ptr
  %spc_full = icmp eq i64 %spc_len, %spc_cap
  br i1 %spc_full, label %spc_grow, label %spc_store
spc_grow:
  %spc_newcap = mul i64 %spc_cap, 2
  %spc_nc_clamped = call i64 @llvm.smax.i64(i64 %spc_newcap, i64 8)
  %spc_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %spc_data = load ptr, ptr %spc_data_ptr
  %spc_newbuf.raw = call ptr @realloc(ptr %spc_data, i64 %spc_nc_clamped)
  %spc_newbuf = call ptr @__concrete_check_oom(ptr %spc_newbuf.raw)
  store ptr %spc_newbuf, ptr %spc_data_ptr
  store i64 %spc_nc_clamped, ptr %spc_cap_ptr
  br label %spc_store
spc_store:
  %spc_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %spc_data2 = load ptr, ptr %spc_dp2
  %spc_slot = getelementptr i8, ptr %spc_data2, i64 %spc_len
  %spc_byte = trunc i64 %c to i8
  store i8 %spc_byte, ptr %spc_slot
  %spc_newlen = add i64 %spc_len, 1
  store i64 %spc_newlen, ptr %spc_len_ptr
  ret void
}

define void @string_append(ptr %s, ptr %other) {
entry:
  %sa_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sa_len = load i64, ptr %sa_len_ptr
  %sa_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sa_cap = load i64, ptr %sa_cap_ptr
  %sa_olen_ptr = getelementptr %struct.String, ptr %other, i32 0, i32 1
  %sa_olen = load i64, ptr %sa_olen_ptr
  %sa_needed = add i64 %sa_len, %sa_olen
  %sa_need_grow = icmp ugt i64 %sa_needed, %sa_cap
  br i1 %sa_need_grow, label %sa_grow, label %sa_copy
sa_grow:
  %sa_dblcap = mul i64 %sa_cap, 2
  %sa_newcap = call i64 @llvm.smax.i64(i64 %sa_dblcap, i64 %sa_needed)
  %sa_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sa_data = load ptr, ptr %sa_data_ptr
  %sa_newbuf.raw = call ptr @realloc(ptr %sa_data, i64 %sa_newcap)
  %sa_newbuf = call ptr @__concrete_check_oom(ptr %sa_newbuf.raw)
  store ptr %sa_newbuf, ptr %sa_data_ptr
  store i64 %sa_newcap, ptr %sa_cap_ptr
  br label %sa_copy
sa_copy:
  %sa_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sa_data2 = load ptr, ptr %sa_dp2
  %sa_dst = getelementptr i8, ptr %sa_data2, i64 %sa_len
  %sa_odata_ptr = getelementptr %struct.String, ptr %other, i32 0, i32 0
  %sa_odata = load ptr, ptr %sa_odata_ptr
  call void @llvm.memcpy.p0.p0.i64(ptr %sa_dst, ptr %sa_odata, i64 %sa_olen, i1 false)
  store i64 %sa_needed, ptr %sa_len_ptr
  ret void
}

define void @string_append_int(ptr %s, i64 %n) {
entry:
  %sai_buf = alloca [32 x i8]
  %sai_fmt = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %sai_written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %sai_buf, i64 32, ptr %sai_fmt, i64 %n)
  %sai_len = sext i32 %sai_written to i64
  %sai_slen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sai_slen = load i64, ptr %sai_slen_ptr
  %sai_scap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sai_scap = load i64, ptr %sai_scap_ptr
  %sai_needed = add i64 %sai_slen, %sai_len
  %sai_need_grow = icmp ugt i64 %sai_needed, %sai_scap
  br i1 %sai_need_grow, label %sai_grow, label %sai_copy
sai_grow:
  %sai_dblcap = mul i64 %sai_scap, 2
  %sai_newcap = call i64 @llvm.smax.i64(i64 %sai_dblcap, i64 %sai_needed)
  %sai_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sai_data = load ptr, ptr %sai_data_ptr
  %sai_newbuf.raw = call ptr @realloc(ptr %sai_data, i64 %sai_newcap)
  %sai_newbuf = call ptr @__concrete_check_oom(ptr %sai_newbuf.raw)
  store ptr %sai_newbuf, ptr %sai_data_ptr
  store i64 %sai_newcap, ptr %sai_scap_ptr
  br label %sai_copy
sai_copy:
  %sai_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sai_data2 = load ptr, ptr %sai_dp2
  %sai_dst = getelementptr i8, ptr %sai_data2, i64 %sai_slen
  call void @llvm.memcpy.p0.p0.i64(ptr %sai_dst, ptr %sai_buf, i64 %sai_len, i1 false)
  store i64 %sai_needed, ptr %sai_slen_ptr
  ret void
}

define void @string_append_bool(ptr %s, i1 %b) {
entry:
  br i1 %b, label %sab_true, label %sab_false
sab_true:
  %sab_tlen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sab_tlen = load i64, ptr %sab_tlen_ptr
  %sab_tcap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sab_tcap = load i64, ptr %sab_tcap_ptr
  %sab_tneeded = add i64 %sab_tlen, 4
  %sab_tneed_grow = icmp ugt i64 %sab_tneeded, %sab_tcap
  br i1 %sab_tneed_grow, label %sab_tgrow, label %sab_tcopy
sab_tgrow:
  %sab_tdblcap = mul i64 %sab_tcap, 2
  %sab_tnewcap = call i64 @llvm.smax.i64(i64 %sab_tdblcap, i64 %sab_tneeded)
  %sab_tdata_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_tdata = load ptr, ptr %sab_tdata_ptr
  %sab_tnewbuf.raw = call ptr @realloc(ptr %sab_tdata, i64 %sab_tnewcap)
  %sab_tnewbuf = call ptr @__concrete_check_oom(ptr %sab_tnewbuf.raw)
  store ptr %sab_tnewbuf, ptr %sab_tdata_ptr
  store i64 %sab_tnewcap, ptr %sab_tcap_ptr
  br label %sab_tcopy
sab_tcopy:
  %sab_tdp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_tdata2 = load ptr, ptr %sab_tdp2
  %sab_tdst = getelementptr i8, ptr %sab_tdata2, i64 %sab_tlen
  call void @llvm.memcpy.p0.p0.i64(ptr %sab_tdst, ptr @.str_true, i64 4, i1 false)
  store i64 %sab_tneeded, ptr %sab_tlen_ptr
  ret void
sab_false:
  %sab_flen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sab_flen = load i64, ptr %sab_flen_ptr
  %sab_fcap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sab_fcap = load i64, ptr %sab_fcap_ptr
  %sab_fneeded = add i64 %sab_flen, 5
  %sab_fneed_grow = icmp ugt i64 %sab_fneeded, %sab_fcap
  br i1 %sab_fneed_grow, label %sab_fgrow, label %sab_fcopy
sab_fgrow:
  %sab_fdblcap = mul i64 %sab_fcap, 2
  %sab_fnewcap = call i64 @llvm.smax.i64(i64 %sab_fdblcap, i64 %sab_fneeded)
  %sab_fdata_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_fdata = load ptr, ptr %sab_fdata_ptr
  %sab_fnewbuf.raw = call ptr @realloc(ptr %sab_fdata, i64 %sab_fnewcap)
  %sab_fnewbuf = call ptr @__concrete_check_oom(ptr %sab_fnewbuf.raw)
  store ptr %sab_fnewbuf, ptr %sab_fdata_ptr
  store i64 %sab_fnewcap, ptr %sab_fcap_ptr
  br label %sab_fcopy
sab_fcopy:
  %sab_fdp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_fdata2 = load ptr, ptr %sab_fdp2
  %sab_fdst = getelementptr i8, ptr %sab_fdata2, i64 %sab_flen
  call void @llvm.memcpy.p0.p0.i64(ptr %sab_fdst, ptr @.str_false, i64 5, i1 false)
  store i64 %sab_fneeded, ptr %sab_flen_ptr
  ret void
}

define void @string_reserve(ptr %s, i64 %extra) {
entry:
  %sr_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sr_cap = load i64, ptr %sr_cap_ptr
  %sr_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sr_len = load i64, ptr %sr_len_ptr
  %sr_needed = add i64 %sr_len, %extra
  %sr_need_grow = icmp ugt i64 %sr_needed, %sr_cap
  br i1 %sr_need_grow, label %sr_grow, label %sr_done
sr_grow:
  %sr_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sr_data = load ptr, ptr %sr_data_ptr
  %sr_newbuf.raw = call ptr @realloc(ptr %sr_data, i64 %sr_needed)
  %sr_newbuf = call ptr @__concrete_check_oom(ptr %sr_newbuf.raw)
  store ptr %sr_newbuf, ptr %sr_data_ptr
  store i64 %sr_needed, ptr %sr_cap_ptr
  br label %sr_done
sr_done:
  ret void
}

define i64 @clock_monotonic_ns() {
entry:
  %ts = alloca [2 x i64]
  %clk_ret = call i32 @clock_gettime(i32 6, ptr %ts)
  %sec_ptr = getelementptr i64, ptr %ts, i64 0
  %sec = load i64, ptr %sec_ptr
  %nsec_ptr = getelementptr i64, ptr %ts, i64 1
  %nsec = load i64, ptr %nsec_ptr
  %sec_ns = mul i64 %sec, 1000000000
  %total = add i64 %sec_ns, %nsec
  ret i64 %total
}

define i64 @vec_len(ptr %vec) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  ret i64 %len
}

define void @vec_free(ptr %vec) {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  call void @free(ptr %data)
  ret void
}

define %struct.Vec @vec_new_4() alwaysinline {
entry:
  %buf.raw = call ptr @malloc(i64 32)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  %v = alloca %struct.Vec
  %bp = getelementptr %struct.Vec, ptr %v, i32 0, i32 0
  store ptr %buf, ptr %bp
  %lp = getelementptr %struct.Vec, ptr %v, i32 0, i32 1
  store i64 0, ptr %lp
  %cp = getelementptr %struct.Vec, ptr %v, i32 0, i32 2
  store i64 8, ptr %cp
  %r = load %struct.Vec, ptr %v
  ret %struct.Vec %r
}

define void @vec_push_4(ptr %vec, ptr %val) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  %cp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 2
  %cap = load i64, ptr %cp
  %full = icmp eq i64 %len, %cap
  br i1 %full, label %grow, label %store
grow:
  %newcap = mul i64 %cap, 2
  %newbytes = mul i64 %newcap, 4
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %newbuf.raw = call ptr @realloc(ptr %data, i64 %newbytes)
  %newbuf = call ptr @__concrete_check_oom(ptr %newbuf.raw)
  store ptr %newbuf, ptr %dp
  store i64 %newcap, ptr %cp
  br label %store
store:
  %dp2 = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data2 = load ptr, ptr %dp2
  %offset = mul i64 %len, 4
  %slot = getelementptr i8, ptr %data2, i64 %offset
  call void @llvm.memcpy.p0.p0.i64(ptr %slot, ptr %val, i64 4, i1 false)
  %newlen = add i64 %len, 1
  store i64 %newlen, ptr %lp
  ret void
}

define ptr @vec_get_4(ptr %vec, i64 %idx) alwaysinline {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %offset = mul i64 %idx, 4
  %slot = getelementptr i8, ptr %data, i64 %offset
  ret ptr %slot
}

define void @vec_set_4(ptr %vec, i64 %idx, ptr %val) alwaysinline {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %offset = mul i64 %idx, 4
  %slot = getelementptr i8, ptr %data, i64 %offset
  call void @llvm.memcpy.p0.p0.i64(ptr %slot, ptr %val, i64 4, i1 false)
  ret void
}

define %enum.Option @vec_pop_4_4(ptr %vec) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  %empty = icmp eq i64 %len, 0
  br i1 %empty, label %none, label %some
some:
  %newlen = sub i64 %len, 1
  store i64 %newlen, ptr %lp
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %offset = mul i64 %newlen, 4
  %slot = getelementptr i8, ptr %data, i64 %offset
  %res = alloca %enum.Option
  call void @memset(ptr %res, i32 0, i64 8)
  store i32 0, ptr %res
  %payload = getelementptr i8, ptr %res, i64 4
  call void @llvm.memcpy.p0.p0.i64(ptr %payload, ptr %slot, i64 4, i1 false)
  %r = load %enum.Option, ptr %res
  ret %enum.Option %r
none:
  %res2 = alloca %enum.Option
  call void @memset(ptr %res2, i32 0, i64 8)
  store i32 1, ptr %res2
  %r2 = load %enum.Option, ptr %res2
  ret %enum.Option %r2
}

