; Generated by Concrete compiler (SSA path)
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx14.0.0"
%struct.String = type { ptr, i64, i64 }
%struct.Vec = type { ptr, i64, i64 }
%variant.Option.Some = type { i64 }
%variant.Option.None = type {}
%enum.Option = type { i32, [12 x i8] }
%variant.Result.Ok = type { i64 }
%variant.Result.Err = type { i64 }
%enum.Result = type { i32, [12 x i8] }
%struct.Transition = type { %enum.State, i32 }
%variant.State.Idle = type { i32 }
%variant.State.Running = type { i32, i32 }
%variant.State.Paused = type { i32, i32 }
%variant.State.Done = type { i32 }
%enum.State = type { i32, [8 x i8] }
%variant.Command.Start = type {}
%variant.Command.Advance = type { i32 }
%variant.Command.Pause = type {}
%variant.Command.Resume = type {}
%variant.Command.Finish = type {}
%enum.Command = type { i32, [4 x i8] }
@__concrete_argc = private global i32 0
@__concrete_argv = private global ptr null
@fmt.main = private constant [6 x i8] c"%lld\0A\00"
@.fmt_ld = private constant [4 x i8] c"%ld\00"
@.fmt_str = private constant [5 x i8] c"%.*s\00"
@.str_true = private constant [5 x i8] c"true\00"
@.str_false = private constant [6 x i8] c"false\00"
@.fmt_f = private constant [3 x i8] c"%g\00"
declare ptr @malloc(i64)
declare void @free(ptr)
declare ptr @realloc(ptr, i64)
declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
declare i64 @write(i32, ptr, i64)
declare void @abort()
declare i32 @printf(ptr, ...)
declare i64 @strlen(ptr)
declare ptr @memset(ptr, i32, i64)
declare i32 @memcmp(ptr, ptr, i64)
declare i32 @snprintf(ptr, i64, ptr, ...)
declare i64 @strtol(ptr, ptr, i32)
declare i64 @llvm.smax.i64(i64, i64)
declare i64 @llvm.smin.i64(i64, i64)
declare i32 @clock_gettime(i32, ptr)
declare i32 @putchar(i32)
define %struct.Transition @transition(ptr %state, ptr %cmd) {
entry:
  %ssa.t0 = alloca %enum.State
  %ssa.t1 = alloca %enum.State
  %ssa.t2 = alloca %enum.Command
  %t14 = alloca %struct.Transition
  %t15 = alloca %enum.State
  %ssa.t3 = alloca %enum.Command
  %t27 = alloca %struct.Transition
  %t28 = alloca %enum.State
  %t38 = alloca %struct.Transition
  %t45 = alloca %struct.Transition
  %t52 = alloca %struct.Transition
  %t53 = alloca %enum.State
  %ssa.t4 = alloca %enum.State
  %ssa.t5 = alloca %enum.Command
  %ssa.t6 = alloca %enum.Command
  %t74 = alloca %struct.Transition
  %t75 = alloca %enum.State
  %t87 = alloca %struct.Transition
  %t88 = alloca %enum.State
  %t98 = alloca %struct.Transition
  %t99 = alloca %enum.State
  %t108 = alloca %struct.Transition
  %t115 = alloca %struct.Transition
  %ssa.t7 = alloca %enum.State
  %ssa.t8 = alloca %enum.Command
  %t132 = alloca %struct.Transition
  %t133 = alloca %enum.State
  %ssa.t9 = alloca %enum.Command
  %t145 = alloca %struct.Transition
  %t146 = alloca %enum.State
  %t157 = alloca %struct.Transition
  %t158 = alloca %enum.State
  %t167 = alloca %struct.Transition
  %t174 = alloca %struct.Transition
  %ssa.t10 = alloca %enum.State
  %t183 = alloca %struct.Transition
  %t184 = alloca %enum.State
  %t0 = load %enum.State, ptr %state
  store %enum.State %t0, ptr %ssa.t0
  %t2 = load i32, ptr %ssa.t0
  %t3 = sext i32 %t2 to i64
  %t4 = icmp eq i64 %t3, 0
  br i1 %t4, label %arm01, label %check12
arm01:
  store %enum.State %t0, ptr %ssa.t1
  %t5 = getelementptr i8, ptr %ssa.t1, i64 4
  %t7 = load i32, ptr %t5
  %t8 = load %enum.Command, ptr %cmd
  store %enum.Command %t8, ptr %ssa.t2
  %t10 = load i32, ptr %ssa.t2
  %t11 = sext i32 %t10 to i64
  %t12 = icmp eq i64 %t11, 0
  br i1 %t12, label %arm04, label %check15
arm04:
  store i32 1, ptr %t15
  %t16 = getelementptr i8, ptr %t15, i64 4
  store i32 %t7, ptr %t16
  %t18 = getelementptr i8, ptr %t16, i64 4
  store i32 0, ptr %t18
  %t19 = load %enum.State, ptr %t15
  store %enum.State %t19, ptr %t14
  %t21 = getelementptr i8, ptr %t14, i64 12
  store i32 0, ptr %t21
  %t22 = load %struct.Transition, ptr %t14
  ret %struct.Transition %t22
check15:
  %t23 = icmp eq i64 %t11, 1
  br i1 %t23, label %arm16, label %check27
arm16:
  store %enum.Command %t8, ptr %ssa.t3
  %t24 = getelementptr i8, ptr %ssa.t3, i64 4
  %t26 = load i32, ptr %t24
  store i32 0, ptr %t28
  %t29 = getelementptr i8, ptr %t28, i64 4
  %t30 = add i32 %t7, %t26
  store i32 %t30, ptr %t29
  %t32 = load %enum.State, ptr %t28
  store %enum.State %t32, ptr %t27
  %t34 = getelementptr i8, ptr %t27, i64 12
  store i32 0, ptr %t34
  %t35 = load %struct.Transition, ptr %t27
  ret %struct.Transition %t35
check27:
  %t36 = icmp eq i64 %t11, 2
  br i1 %t36, label %arm28, label %check39
arm28:
  %t39 = load %enum.State, ptr %state
  store %enum.State %t39, ptr %t38
  %t41 = getelementptr i8, ptr %t38, i64 12
  store i32 0, ptr %t41
  %t42 = load %struct.Transition, ptr %t38
  ret %struct.Transition %t42
check39:
  %t43 = icmp eq i64 %t11, 3
  br i1 %t43, label %arm310, label %check411
arm310:
  %t46 = load %enum.State, ptr %state
  store %enum.State %t46, ptr %t45
  %t48 = getelementptr i8, ptr %t45, i64 12
  store i32 0, ptr %t48
  %t49 = load %struct.Transition, ptr %t45
  ret %struct.Transition %t49
check411:
  %t50 = icmp eq i64 %t11, 4
  br i1 %t50, label %arm412, label %check513
arm412:
  store i32 3, ptr %t53
  %t54 = getelementptr i8, ptr %t53, i64 4
  store i32 %t7, ptr %t54
  %t56 = load %enum.State, ptr %t53
  store %enum.State %t56, ptr %t52
  %t58 = getelementptr i8, ptr %t52, i64 12
  store i32 %t7, ptr %t58
  %t59 = load %struct.Transition, ptr %t52
  ret %struct.Transition %t59
check513:
  unreachable
check12:
  %t60 = icmp eq i64 %t3, 1
  br i1 %t60, label %arm114, label %check215
arm114:
  store %enum.State %t0, ptr %ssa.t4
  %t61 = getelementptr i8, ptr %ssa.t4, i64 4
  %t63 = load i32, ptr %t61
  %t64 = getelementptr i8, ptr %t61, i64 4
  %t65 = load i32, ptr %t64
  %t66 = load %enum.Command, ptr %cmd
  store %enum.Command %t66, ptr %ssa.t5
  %t68 = load i32, ptr %ssa.t5
  %t69 = sext i32 %t68 to i64
  %t70 = icmp eq i64 %t69, 1
  br i1 %t70, label %arm017, label %check118
arm017:
  store %enum.Command %t66, ptr %ssa.t6
  %t71 = getelementptr i8, ptr %ssa.t6, i64 4
  %t73 = load i32, ptr %t71
  store i32 1, ptr %t75
  %t76 = getelementptr i8, ptr %t75, i64 4
  %t77 = add i32 %t63, %t73
  store i32 %t77, ptr %t76
  %t79 = add i32 %t65, 1
  %t80 = getelementptr i8, ptr %t76, i64 4
  store i32 %t79, ptr %t80
  %t81 = load %enum.State, ptr %t75
  store %enum.State %t81, ptr %t74
  %t83 = getelementptr i8, ptr %t74, i64 12
  store i32 %t73, ptr %t83
  %t84 = load %struct.Transition, ptr %t74
  ret %struct.Transition %t84
check118:
  %t85 = icmp eq i64 %t69, 2
  br i1 %t85, label %arm119, label %check220
arm119:
  store i32 2, ptr %t88
  %t89 = getelementptr i8, ptr %t88, i64 4
  store i32 %t63, ptr %t89
  %t91 = getelementptr i8, ptr %t89, i64 4
  store i32 %t65, ptr %t91
  %t92 = load %enum.State, ptr %t88
  store %enum.State %t92, ptr %t87
  %t94 = getelementptr i8, ptr %t87, i64 12
  store i32 0, ptr %t94
  %t95 = load %struct.Transition, ptr %t87
  ret %struct.Transition %t95
check220:
  %t96 = icmp eq i64 %t69, 4
  br i1 %t96, label %arm221, label %check322
arm221:
  store i32 3, ptr %t99
  %t100 = getelementptr i8, ptr %t99, i64 4
  store i32 %t63, ptr %t100
  %t102 = load %enum.State, ptr %t99
  store %enum.State %t102, ptr %t98
  %t104 = getelementptr i8, ptr %t98, i64 12
  store i32 %t63, ptr %t104
  %t105 = load %struct.Transition, ptr %t98
  ret %struct.Transition %t105
check322:
  %t106 = icmp eq i64 %t69, 0
  br i1 %t106, label %arm323, label %check424
arm323:
  %t109 = load %enum.State, ptr %state
  store %enum.State %t109, ptr %t108
  %t111 = getelementptr i8, ptr %t108, i64 12
  store i32 0, ptr %t111
  %t112 = load %struct.Transition, ptr %t108
  ret %struct.Transition %t112
check424:
  %t113 = icmp eq i64 %t69, 3
  br i1 %t113, label %arm425, label %check526
arm425:
  %t116 = load %enum.State, ptr %state
  store %enum.State %t116, ptr %t115
  %t118 = getelementptr i8, ptr %t115, i64 12
  store i32 0, ptr %t118
  %t119 = load %struct.Transition, ptr %t115
  ret %struct.Transition %t119
check526:
  unreachable
check215:
  %t120 = icmp eq i64 %t3, 2
  br i1 %t120, label %arm227, label %check328
arm227:
  store %enum.State %t0, ptr %ssa.t7
  %t121 = getelementptr i8, ptr %ssa.t7, i64 4
  %t123 = load i32, ptr %t121
  %t124 = getelementptr i8, ptr %t121, i64 4
  %t125 = load i32, ptr %t124
  %t126 = load %enum.Command, ptr %cmd
  store %enum.Command %t126, ptr %ssa.t8
  %t128 = load i32, ptr %ssa.t8
  %t129 = sext i32 %t128 to i64
  %t130 = icmp eq i64 %t129, 3
  br i1 %t130, label %arm030, label %check131
arm030:
  store i32 1, ptr %t133
  %t134 = getelementptr i8, ptr %t133, i64 4
  store i32 %t123, ptr %t134
  %t136 = getelementptr i8, ptr %t134, i64 4
  store i32 %t125, ptr %t136
  %t137 = load %enum.State, ptr %t133
  store %enum.State %t137, ptr %t132
  %t139 = getelementptr i8, ptr %t132, i64 12
  store i32 0, ptr %t139
  %t140 = load %struct.Transition, ptr %t132
  ret %struct.Transition %t140
check131:
  %t141 = icmp eq i64 %t129, 1
  br i1 %t141, label %arm132, label %check233
arm132:
  store %enum.Command %t126, ptr %ssa.t9
  %t142 = getelementptr i8, ptr %ssa.t9, i64 4
  %t144 = load i32, ptr %t142
  store i32 2, ptr %t146
  %t147 = getelementptr i8, ptr %t146, i64 4
  %t148 = add i32 %t123, %t144
  store i32 %t148, ptr %t147
  %t150 = getelementptr i8, ptr %t147, i64 4
  store i32 %t125, ptr %t150
  %t151 = load %enum.State, ptr %t146
  store %enum.State %t151, ptr %t145
  %t153 = getelementptr i8, ptr %t145, i64 12
  store i32 0, ptr %t153
  %t154 = load %struct.Transition, ptr %t145
  ret %struct.Transition %t154
check233:
  %t155 = icmp eq i64 %t129, 4
  br i1 %t155, label %arm234, label %check335
arm234:
  store i32 3, ptr %t158
  %t159 = getelementptr i8, ptr %t158, i64 4
  store i32 %t123, ptr %t159
  %t161 = load %enum.State, ptr %t158
  store %enum.State %t161, ptr %t157
  %t163 = getelementptr i8, ptr %t157, i64 12
  store i32 %t123, ptr %t163
  %t164 = load %struct.Transition, ptr %t157
  ret %struct.Transition %t164
check335:
  %t165 = icmp eq i64 %t129, 0
  br i1 %t165, label %arm336, label %check437
arm336:
  %t168 = load %enum.State, ptr %state
  store %enum.State %t168, ptr %t167
  %t170 = getelementptr i8, ptr %t167, i64 12
  store i32 0, ptr %t170
  %t171 = load %struct.Transition, ptr %t167
  ret %struct.Transition %t171
check437:
  %t172 = icmp eq i64 %t129, 2
  br i1 %t172, label %arm438, label %check539
arm438:
  %t175 = load %enum.State, ptr %state
  store %enum.State %t175, ptr %t174
  %t177 = getelementptr i8, ptr %t174, i64 12
  store i32 0, ptr %t177
  %t178 = load %struct.Transition, ptr %t174
  ret %struct.Transition %t178
check539:
  unreachable
check328:
  %t179 = icmp eq i64 %t3, 3
  br i1 %t179, label %arm340, label %check441
arm340:
  store %enum.State %t0, ptr %ssa.t10
  %t180 = getelementptr i8, ptr %ssa.t10, i64 4
  %t182 = load i32, ptr %t180
  store i32 3, ptr %t184
  %t185 = getelementptr i8, ptr %t184, i64 4
  store i32 %t182, ptr %t185
  %t187 = load %enum.State, ptr %t184
  store %enum.State %t187, ptr %t183
  %t189 = getelementptr i8, ptr %t183, i64 12
  store i32 0, ptr %t189
  %t190 = load %struct.Transition, ptr %t183
  ret %struct.Transition %t190
check441:
  unreachable
}

define i32 @get_acc(ptr %state) {
entry:
  %ssa.t11 = alloca %enum.State
  %ssa.t12 = alloca %enum.State
  %ssa.t13 = alloca %enum.State
  %ssa.t14 = alloca %enum.State
  %ssa.t15 = alloca %enum.State
  %t0 = load %enum.State, ptr %state
  store %enum.State %t0, ptr %ssa.t11
  %t2 = load i32, ptr %ssa.t11
  %t3 = sext i32 %t2 to i64
  %t4 = icmp eq i64 %t3, 0
  br i1 %t4, label %arm01, label %check12
arm01:
  store %enum.State %t0, ptr %ssa.t12
  %t5 = getelementptr i8, ptr %ssa.t12, i64 4
  %t7 = load i32, ptr %t5
  ret i32 %t7
check12:
  %t8 = icmp eq i64 %t3, 1
  br i1 %t8, label %arm13, label %check24
arm13:
  store %enum.State %t0, ptr %ssa.t13
  %t9 = getelementptr i8, ptr %ssa.t13, i64 4
  %t11 = load i32, ptr %t9
  ret i32 %t11
check24:
  %t14 = icmp eq i64 %t3, 2
  br i1 %t14, label %arm25, label %check36
arm25:
  store %enum.State %t0, ptr %ssa.t14
  %t15 = getelementptr i8, ptr %ssa.t14, i64 4
  %t17 = load i32, ptr %t15
  ret i32 %t17
check36:
  %t20 = icmp eq i64 %t3, 3
  br i1 %t20, label %arm37, label %check48
arm37:
  store %enum.State %t0, ptr %ssa.t15
  %t21 = getelementptr i8, ptr %ssa.t15, i64 4
  %t23 = load i32, ptr %t21
  ret i32 %t23
check48:
  unreachable
}

define %enum.State @step(ptr %state, ptr %cmd) {
entry:
  %ssa.t16 = alloca %struct.Transition
  %t0 = call %struct.Transition @transition(ptr %state, ptr %cmd)
  store %struct.Transition %t0, ptr %ssa.t16
  %t2 = load %enum.State, ptr %ssa.t16
  ret %enum.State %t2
}

define i64 @user_main() {
entry:
  %t0 = alloca %enum.Command
  %t3 = alloca %enum.Command
  %t7 = alloca %enum.Command
  %t11 = alloca %enum.Command
  %t14 = alloca %enum.Command
  %t18 = alloca %enum.Command
  %t21 = alloca %enum.Command
  %t25 = alloca %enum.Command
  %t28 = alloca %enum.State
  %borrow.32 = alloca %enum.State
  %borrow.33 = alloca %enum.Command
  %borrow.35 = alloca %enum.State
  %borrow.36 = alloca %enum.Command
  %borrow.38 = alloca %enum.State
  %borrow.39 = alloca %enum.Command
  %borrow.41 = alloca %enum.State
  %borrow.42 = alloca %enum.Command
  %borrow.44 = alloca %enum.State
  %borrow.45 = alloca %enum.Command
  %borrow.47 = alloca %enum.State
  %borrow.48 = alloca %enum.Command
  %borrow.50 = alloca %enum.State
  %borrow.51 = alloca %enum.Command
  %borrow.53 = alloca %enum.State
  %borrow.54 = alloca %enum.Command
  %borrow.56 = alloca %enum.State
  store i32 0, ptr %t0
  %t2 = load %enum.Command, ptr %t0
  store i32 1, ptr %t3
  %t4 = getelementptr i8, ptr %t3, i64 4
  store i32 10, ptr %t4
  %t6 = load %enum.Command, ptr %t3
  store i32 1, ptr %t7
  %t8 = getelementptr i8, ptr %t7, i64 4
  store i32 5, ptr %t8
  %t10 = load %enum.Command, ptr %t7
  store i32 2, ptr %t11
  %t13 = load %enum.Command, ptr %t11
  store i32 1, ptr %t14
  %t15 = getelementptr i8, ptr %t14, i64 4
  store i32 7, ptr %t15
  %t17 = load %enum.Command, ptr %t14
  store i32 3, ptr %t18
  %t20 = load %enum.Command, ptr %t18
  store i32 1, ptr %t21
  %t22 = getelementptr i8, ptr %t21, i64 4
  store i32 20, ptr %t22
  %t24 = load %enum.Command, ptr %t21
  store i32 4, ptr %t25
  %t27 = load %enum.Command, ptr %t25
  store i32 0, ptr %t28
  %t29 = getelementptr i8, ptr %t28, i64 4
  store i32 0, ptr %t29
  %t31 = load %enum.State, ptr %t28
  store %enum.State %t31, ptr %borrow.32
  store %enum.Command %t2, ptr %borrow.33
  %t34 = call %enum.State @step(ptr %borrow.32, ptr %borrow.33)
  store %enum.State %t34, ptr %borrow.35
  store %enum.Command %t6, ptr %borrow.36
  %t37 = call %enum.State @step(ptr %borrow.35, ptr %borrow.36)
  store %enum.State %t37, ptr %borrow.38
  store %enum.Command %t10, ptr %borrow.39
  %t40 = call %enum.State @step(ptr %borrow.38, ptr %borrow.39)
  store %enum.State %t40, ptr %borrow.41
  store %enum.Command %t13, ptr %borrow.42
  %t43 = call %enum.State @step(ptr %borrow.41, ptr %borrow.42)
  store %enum.State %t43, ptr %borrow.44
  store %enum.Command %t17, ptr %borrow.45
  %t46 = call %enum.State @step(ptr %borrow.44, ptr %borrow.45)
  store %enum.State %t46, ptr %borrow.47
  store %enum.Command %t20, ptr %borrow.48
  %t49 = call %enum.State @step(ptr %borrow.47, ptr %borrow.48)
  store %enum.State %t49, ptr %borrow.50
  store %enum.Command %t24, ptr %borrow.51
  %t52 = call %enum.State @step(ptr %borrow.50, ptr %borrow.51)
  store %enum.State %t52, ptr %borrow.53
  store %enum.Command %t27, ptr %borrow.54
  %t55 = call %enum.State @step(ptr %borrow.53, ptr %borrow.54)
  store %enum.State %t55, ptr %borrow.56
  %t57 = call i32 @get_acc(ptr %borrow.56)
  %t58 = sext i32 %t57 to i64
  ret i64 %t58
}

define i32 @__concrete_get_argc() {
entry:
  %argc = load i32, ptr @__concrete_argc
  ret i32 %argc
}

define ptr @__concrete_get_argv(i32 %idx) {
entry:
  %argv = load ptr, ptr @__concrete_argv
  %idx64 = sext i32 %idx to i64
  %argp = getelementptr ptr, ptr %argv, i64 %idx64
  %arg = load ptr, ptr %argp
  ret ptr %arg
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  store i32 %argc, ptr @__concrete_argc
  store ptr %argv, ptr @__concrete_argv
  %result = call i64 @user_main()
  %fmt = getelementptr [6 x i8], ptr @fmt.main, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %fmt, i64 %result)
  ret i32 0
}

define ptr @__concrete_check_oom(ptr %p) {
entry:
  %is_null = icmp eq ptr %p, null
  br i1 %is_null, label %oom, label %ok
oom:
  call void @abort()
  unreachable
ok:
  ret ptr %p
}

define i64 @string_length(ptr %s) {
entry:
  %len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len = load i64, ptr %len_ptr
  ret i64 %len
}

define void @drop_string(ptr %s) {
entry:
  %data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data = load ptr, ptr %data_ptr
  call void @free(ptr %data)
  ret void
}

define %struct.String @string_concat(ptr %a, ptr %b) {
entry:
  %a_data_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 0
  %a_data = load ptr, ptr %a_data_ptr
  %a_len_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 1
  %a_len = load i64, ptr %a_len_ptr
  %b_data_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 0
  %b_data = load ptr, ptr %b_data_ptr
  %b_len_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 1
  %b_len = load i64, ptr %b_len_ptr
  %total_len = add i64 %a_len, %b_len
  %buf.raw = call ptr @malloc(i64 %total_len)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %buf, ptr %a_data, i64 %a_len, i1 false)
  %dst = getelementptr i8, ptr %buf, i64 %a_len
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %b_data, i64 %b_len, i1 false)
  call void @free(ptr %a_data)
  call void @free(ptr %b_data)
  %sc_alloca = alloca %struct.String
  %sc_data_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 0
  store ptr %buf, ptr %sc_data_ptr
  %sc_len_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 1
  store i64 %total_len, ptr %sc_len_ptr
  %sc_cap_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 2
  store i64 %total_len, ptr %sc_cap_ptr
  %sc_result = load %struct.String, ptr %sc_alloca
  ret %struct.String %sc_result
}

define %struct.String @string_slice(ptr %s, i64 %start, i64 %end_) {
entry:
  %len_ptr.ss = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len.ss = load i64, ptr %len_ptr.ss
  %s_clamped = call i64 @llvm.smax.i64(i64 %start, i64 0)
  %s_min = call i64 @llvm.smin.i64(i64 %s_clamped, i64 %len.ss)
  %e_clamped = call i64 @llvm.smax.i64(i64 %end_, i64 0)
  %e_min = call i64 @llvm.smin.i64(i64 %e_clamped, i64 %len.ss)
  %e_final = call i64 @llvm.smax.i64(i64 %e_min, i64 %s_min)
  %slice_len = sub i64 %e_final, %s_min
  %slice_buf.raw = call ptr @malloc(i64 %slice_len)
  %slice_buf = call ptr @__concrete_check_oom(ptr %slice_buf.raw)
  %data_ptr.ss = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data.ss = load ptr, ptr %data_ptr.ss
  %src = getelementptr i8, ptr %data.ss, i64 %s_min
  call void @llvm.memcpy.p0.p0.i64(ptr %slice_buf, ptr %src, i64 %slice_len, i1 false)
  %res.ss = alloca %struct.String
  %res_d.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 0
  store ptr %slice_buf, ptr %res_d.ss
  %res_l.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 1
  store i64 %slice_len, ptr %res_l.ss
  %res_c.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 2
  store i64 %slice_len, ptr %res_c.ss
  %result.ss = load %struct.String, ptr %res.ss
  ret %struct.String %result.ss
}

define %struct.String @string_substr(ptr %s, i64 %start, i64 %len) {
entry:
  %end_ = add i64 %start, %len
  %result.ssub = call %struct.String @string_slice(ptr %s, i64 %start, i64 %end_)
  ret %struct.String %result.ssub
}

define i64 @string_char_at(ptr %s, i64 %index) {
entry:
  %len_ptr.sca = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len.sca = load i64, ptr %len_ptr.sca
  %neg = icmp slt i64 %index, 0
  %oob = icmp sge i64 %index, %len.sca
  %bad = or i1 %neg, %oob
  br i1 %bad, label %ret_neg, label %ok_idx
ret_neg:
  ret i64 -1
ok_idx:
  %data_ptr.sca = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data.sca = load ptr, ptr %data_ptr.sca
  %char_ptr = getelementptr i8, ptr %data.sca, i64 %index
  %byte = load i8, ptr %char_ptr
  %char = zext i8 %byte to i64
  ret i64 %char
}

define i1 @string_contains(ptr %haystack, ptr %needle) {
entry:
  %h_data_ptr = getelementptr %struct.String, ptr %haystack, i32 0, i32 0
  %h_data = load ptr, ptr %h_data_ptr
  %h_len_ptr = getelementptr %struct.String, ptr %haystack, i32 0, i32 1
  %h_len = load i64, ptr %h_len_ptr
  %n_data_ptr = getelementptr %struct.String, ptr %needle, i32 0, i32 0
  %n_data = load ptr, ptr %n_data_ptr
  %n_len_ptr = getelementptr %struct.String, ptr %needle, i32 0, i32 1
  %n_len = load i64, ptr %n_len_ptr
  %n_empty = icmp eq i64 %n_len, 0
  br i1 %n_empty, label %found, label %check_len
check_len:
  %too_long = icmp ugt i64 %n_len, %h_len
  br i1 %too_long, label %not_found, label %loop_start
loop_start:
  %max_i = sub i64 %h_len, %n_len
  br label %loop
loop:
  %i = phi i64 [0, %loop_start], [%i_next, %loop_cont]
  %h_ptr = getelementptr i8, ptr %h_data, i64 %i
  %cmp = call i32 @memcmp(ptr %h_ptr, ptr %n_data, i64 %n_len)
  %match = icmp eq i32 %cmp, 0
  br i1 %match, label %found, label %loop_cont
loop_cont:
  %i_next = add i64 %i, 1
  %done = icmp ugt i64 %i_next, %max_i
  br i1 %done, label %not_found, label %loop
found:
  ret i1 1
not_found:
  ret i1 0
}

define i1 @string_eq(ptr %a, ptr %b) {
entry:
  %a_len_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 1
  %a_len = load i64, ptr %a_len_ptr
  %b_len_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 1
  %b_len = load i64, ptr %b_len_ptr
  %len_eq = icmp eq i64 %a_len, %b_len
  br i1 %len_eq, label %cmp_data, label %not_eq
cmp_data:
  %zero_len = icmp eq i64 %a_len, 0
  br i1 %zero_len, label %eq, label %do_cmp
do_cmp:
  %a_data_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 0
  %a_data = load ptr, ptr %a_data_ptr
  %b_data_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 0
  %b_data = load ptr, ptr %b_data_ptr
  %cmp_res = call i32 @memcmp(ptr %a_data, ptr %b_data, i64 %a_len)
  %eq_data = icmp eq i32 %cmp_res, 0
  br i1 %eq_data, label %eq, label %not_eq
eq:
  ret i1 1
not_eq:
  ret i1 0
}

define %struct.String @int_to_string(i64 %n) {
entry:
  %buf.raw = call ptr @malloc(i64 32)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  %fmt_its = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %buf, i64 32, ptr %fmt_its, i64 %n)
  %wext = sext i32 %written to i64
  %res.its = alloca %struct.String
  %res_d.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 0
  store ptr %buf, ptr %res_d.its
  %res_l.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 1
  store i64 %wext, ptr %res_l.its
  %res_c.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 2
  store i64 32, ptr %res_c.its
  %result.its = load %struct.String, ptr %res.its
  ret %struct.String %result.its
}

define %enum.Result @string_to_int(ptr %s) {
entry:
  %sti_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sti_data = load ptr, ptr %sti_data_ptr
  %sti_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sti_len = load i64, ptr %sti_len_ptr
  %sti_buf_sz = add i64 %sti_len, 1
  %sti_buf.raw = call ptr @malloc(i64 %sti_buf_sz)
  %sti_buf = call ptr @__concrete_check_oom(ptr %sti_buf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %sti_buf, ptr %sti_data, i64 %sti_len, i1 false)
  %sti_null = getelementptr i8, ptr %sti_buf, i64 %sti_len
  store i8 0, ptr %sti_null
  %endptr_alloca = alloca ptr
  %sti_val = call i64 @strtol(ptr %sti_buf, ptr %endptr_alloca, i32 10)
  %endptr = load ptr, ptr %endptr_alloca
  %end_expected = getelementptr i8, ptr %sti_buf, i64 %sti_len
  %valid = icmp eq ptr %endptr, %end_expected
  %empty_input = icmp eq i64 %sti_len, 0
  %not_empty = xor i1 %empty_input, 1
  %final_ok = and i1 %valid, %not_empty
  call void @free(ptr %sti_buf)
  %res.sti = alloca %enum.Result
  br i1 %final_ok, label %sti_ok, label %sti_err
sti_ok:
  store i32 0, ptr %res.sti
  %data_ptr.sti_ok = getelementptr i8, ptr %res.sti, i64 8
  store i64 %sti_val, ptr %data_ptr.sti_ok
  br label %sti_done
sti_err:
  store i32 1, ptr %res.sti
  %data_ptr.sti_err = getelementptr i8, ptr %res.sti, i64 8
  store i64 1, ptr %data_ptr.sti_err
  br label %sti_done
sti_done:
  %result.sti = load %enum.Result, ptr %res.sti
  ret %enum.Result %result.sti
}

define %struct.String @bool_to_string(i1 %b) {
entry:
  br i1 %b, label %bts_true, label %bts_false
bts_true:
  %tbuf.raw = call ptr @malloc(i64 4)
  %tbuf = call ptr @__concrete_check_oom(ptr %tbuf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %tbuf, ptr @.str_true, i64 4, i1 false)
  %tres = alloca %struct.String
  %td = getelementptr %struct.String, ptr %tres, i32 0, i32 0
  store ptr %tbuf, ptr %td
  %tl = getelementptr %struct.String, ptr %tres, i32 0, i32 1
  store i64 4, ptr %tl
  %tc = getelementptr %struct.String, ptr %tres, i32 0, i32 2
  store i64 4, ptr %tc
  %tresult = load %struct.String, ptr %tres
  ret %struct.String %tresult
bts_false:
  %fbuf.raw = call ptr @malloc(i64 5)
  %fbuf = call ptr @__concrete_check_oom(ptr %fbuf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %fbuf, ptr @.str_false, i64 5, i1 false)
  %fres = alloca %struct.String
  %fd = getelementptr %struct.String, ptr %fres, i32 0, i32 0
  store ptr %fbuf, ptr %fd
  %fl = getelementptr %struct.String, ptr %fres, i32 0, i32 1
  store i64 5, ptr %fl
  %fc = getelementptr %struct.String, ptr %fres, i32 0, i32 2
  store i64 5, ptr %fc
  %fresult = load %struct.String, ptr %fres
  ret %struct.String %fresult
}

define %struct.String @float_to_string(double %f) {
entry:
  %fbuf.fts.raw = call ptr @malloc(i64 64)
  %fbuf.fts = call ptr @__concrete_check_oom(ptr %fbuf.fts.raw)
  %fmt.fts = getelementptr [3 x i8], ptr @.fmt_f, i64 0, i64 0
  %written.fts = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %fbuf.fts, i64 64, ptr %fmt.fts, double %f)
  %wext.fts = sext i32 %written.fts to i64
  %res.fts = alloca %struct.String
  %res_d.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 0
  store ptr %fbuf.fts, ptr %res_d.fts
  %res_l.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 1
  store i64 %wext.fts, ptr %res_l.fts
  %res_c.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 2
  store i64 64, ptr %res_c.fts
  %result.fts = load %struct.String, ptr %res.fts
  ret %struct.String %result.fts
}

define %struct.String @string_trim(ptr %s) {
entry:
  %st_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %st_data = load ptr, ptr %st_data_ptr
  %st_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %st_len = load i64, ptr %st_len_ptr
  br label %trim_left
trim_left:
  %tl_i = phi i64 [0, %entry], [%tl_next, %tl_ws]
  %tl_done = icmp uge i64 %tl_i, %st_len
  br i1 %tl_done, label %trim_result, label %tl_check
tl_check:
  %tl_ptr = getelementptr i8, ptr %st_data, i64 %tl_i
  %tl_ch = load i8, ptr %tl_ptr
  %tl_is_sp = icmp eq i8 %tl_ch, 32
  %tl_is_tab = icmp eq i8 %tl_ch, 9
  %tl_is_nl = icmp eq i8 %tl_ch, 10
  %tl_is_cr = icmp eq i8 %tl_ch, 13
  %tl_w1 = or i1 %tl_is_sp, %tl_is_tab
  %tl_w2 = or i1 %tl_is_nl, %tl_is_cr
  %tl_is_ws = or i1 %tl_w1, %tl_w2
  br i1 %tl_is_ws, label %tl_ws, label %trim_right_init
tl_ws:
  %tl_next = add i64 %tl_i, 1
  br label %trim_left
trim_right_init:
  %tr_start = sub i64 %st_len, 1
  br label %trim_right
trim_right:
  %tr_i = phi i64 [%tr_start, %trim_right_init], [%tr_prev, %tr_ws]
  %tr_done = icmp ult i64 %tr_i, %tl_i
  br i1 %tr_done, label %trim_result, label %tr_check
tr_check:
  %tr_ptr = getelementptr i8, ptr %st_data, i64 %tr_i
  %tr_ch = load i8, ptr %tr_ptr
  %tr_is_sp = icmp eq i8 %tr_ch, 32
  %tr_is_tab = icmp eq i8 %tr_ch, 9
  %tr_is_nl = icmp eq i8 %tr_ch, 10
  %tr_is_cr = icmp eq i8 %tr_ch, 13
  %tr_w1 = or i1 %tr_is_sp, %tr_is_tab
  %tr_w2 = or i1 %tr_is_nl, %tr_is_cr
  %tr_is_ws = or i1 %tr_w1, %tr_w2
  br i1 %tr_is_ws, label %tr_ws, label %trim_result
tr_ws:
  %tr_prev = sub i64 %tr_i, 1
  br label %trim_right
trim_result:
  %tr_left = phi i64 [%tl_i, %trim_left], [%tl_i, %trim_right], [%tl_i, %tr_check]
  %tr_right_raw = phi i64 [0, %trim_left], [%tl_i, %trim_right], [%tr_i, %tr_check]
  %tr_right = add i64 %tr_right_raw, 1
  %tr_empty = icmp uge i64 %tr_left, %tr_right
  br i1 %tr_empty, label %trim_empty, label %trim_copy
trim_empty:
  %te_buf.raw = call ptr @malloc(i64 1)
  %te_buf = call ptr @__concrete_check_oom(ptr %te_buf.raw)
  %te_res = alloca %struct.String
  %te_d = getelementptr %struct.String, ptr %te_res, i32 0, i32 0
  store ptr %te_buf, ptr %te_d
  %te_l = getelementptr %struct.String, ptr %te_res, i32 0, i32 1
  store i64 0, ptr %te_l
  %te_c = getelementptr %struct.String, ptr %te_res, i32 0, i32 2
  store i64 1, ptr %te_c
  %te_result = load %struct.String, ptr %te_res
  ret %struct.String %te_result
trim_copy:
  %tc_len = sub i64 %tr_right, %tr_left
  %tc_buf.raw = call ptr @malloc(i64 %tc_len)
  %tc_buf = call ptr @__concrete_check_oom(ptr %tc_buf.raw)
  %tc_src = getelementptr i8, ptr %st_data, i64 %tr_left
  call void @llvm.memcpy.p0.p0.i64(ptr %tc_buf, ptr %tc_src, i64 %tc_len, i1 false)
  %tc_res = alloca %struct.String
  %tc_d = getelementptr %struct.String, ptr %tc_res, i32 0, i32 0
  store ptr %tc_buf, ptr %tc_d
  %tc_l = getelementptr %struct.String, ptr %tc_res, i32 0, i32 1
  store i64 %tc_len, ptr %tc_l
  %tc_c = getelementptr %struct.String, ptr %tc_res, i32 0, i32 2
  store i64 %tc_len, ptr %tc_c
  %tc_result = load %struct.String, ptr %tc_res
  ret %struct.String %tc_result
}

define void @print_string(ptr %s) {
entry:
  %ps_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %ps_data = load ptr, ptr %ps_data_ptr
  %ps_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %ps_len = load i64, ptr %ps_len_ptr
  %ps_fmt = getelementptr [5 x i8], ptr @.fmt_str, i64 0, i64 0
  %ps_len32 = trunc i64 %ps_len to i32
  %ps_written = call i32 (ptr, ...) @printf(ptr %ps_fmt, i32 %ps_len32, ptr %ps_data)
  ret void
}

define void @print_int(i64 %n) {
entry:
  %pi_fmt = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %pi_written = call i32 (ptr, ...) @printf(ptr %pi_fmt, i64 %n)
  ret void
}

define void @print_char(i64 %c) {
entry:
  %pc_int = trunc i64 %c to i32
  %pc_wr = call i32 @putchar(i32 %pc_int)
  ret void
}

define void @print_bool(i1 %b) {
entry:
  %is_true = icmp eq i1 %b, 1
  br i1 %is_true, label %print_true, label %print_false
print_true:
  %true_ptr = getelementptr [5 x i8], ptr @.str_true, i64 0, i64 0
  %tw = call i32 (ptr, ...) @printf(ptr %true_ptr)
  ret void
print_false:
  %false_ptr = getelementptr [6 x i8], ptr @.str_false, i64 0, i64 0
  %fw = call i32 (ptr, ...) @printf(ptr %false_ptr)
  ret void
}

define void @string_push_char(ptr %s, i64 %c) {
entry:
  %spc_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %spc_len = load i64, ptr %spc_len_ptr
  %spc_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %spc_cap = load i64, ptr %spc_cap_ptr
  %spc_full = icmp eq i64 %spc_len, %spc_cap
  br i1 %spc_full, label %spc_grow, label %spc_store
spc_grow:
  %spc_newcap = mul i64 %spc_cap, 2
  %spc_nc_clamped = call i64 @llvm.smax.i64(i64 %spc_newcap, i64 8)
  %spc_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %spc_data = load ptr, ptr %spc_data_ptr
  %spc_newbuf.raw = call ptr @realloc(ptr %spc_data, i64 %spc_nc_clamped)
  %spc_newbuf = call ptr @__concrete_check_oom(ptr %spc_newbuf.raw)
  store ptr %spc_newbuf, ptr %spc_data_ptr
  store i64 %spc_nc_clamped, ptr %spc_cap_ptr
  br label %spc_store
spc_store:
  %spc_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %spc_data2 = load ptr, ptr %spc_dp2
  %spc_slot = getelementptr i8, ptr %spc_data2, i64 %spc_len
  %spc_byte = trunc i64 %c to i8
  store i8 %spc_byte, ptr %spc_slot
  %spc_newlen = add i64 %spc_len, 1
  store i64 %spc_newlen, ptr %spc_len_ptr
  ret void
}

define void @string_append(ptr %s, ptr %other) {
entry:
  %sa_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sa_len = load i64, ptr %sa_len_ptr
  %sa_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sa_cap = load i64, ptr %sa_cap_ptr
  %sa_olen_ptr = getelementptr %struct.String, ptr %other, i32 0, i32 1
  %sa_olen = load i64, ptr %sa_olen_ptr
  %sa_needed = add i64 %sa_len, %sa_olen
  %sa_need_grow = icmp ugt i64 %sa_needed, %sa_cap
  br i1 %sa_need_grow, label %sa_grow, label %sa_copy
sa_grow:
  %sa_dblcap = mul i64 %sa_cap, 2
  %sa_newcap = call i64 @llvm.smax.i64(i64 %sa_dblcap, i64 %sa_needed)
  %sa_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sa_data = load ptr, ptr %sa_data_ptr
  %sa_newbuf.raw = call ptr @realloc(ptr %sa_data, i64 %sa_newcap)
  %sa_newbuf = call ptr @__concrete_check_oom(ptr %sa_newbuf.raw)
  store ptr %sa_newbuf, ptr %sa_data_ptr
  store i64 %sa_newcap, ptr %sa_cap_ptr
  br label %sa_copy
sa_copy:
  %sa_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sa_data2 = load ptr, ptr %sa_dp2
  %sa_dst = getelementptr i8, ptr %sa_data2, i64 %sa_len
  %sa_odata_ptr = getelementptr %struct.String, ptr %other, i32 0, i32 0
  %sa_odata = load ptr, ptr %sa_odata_ptr
  call void @llvm.memcpy.p0.p0.i64(ptr %sa_dst, ptr %sa_odata, i64 %sa_olen, i1 false)
  store i64 %sa_needed, ptr %sa_len_ptr
  ret void
}

define void @string_append_int(ptr %s, i64 %n) {
entry:
  %sai_buf = alloca [32 x i8]
  %sai_fmt = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %sai_written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %sai_buf, i64 32, ptr %sai_fmt, i64 %n)
  %sai_len = sext i32 %sai_written to i64
  %sai_slen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sai_slen = load i64, ptr %sai_slen_ptr
  %sai_scap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sai_scap = load i64, ptr %sai_scap_ptr
  %sai_needed = add i64 %sai_slen, %sai_len
  %sai_need_grow = icmp ugt i64 %sai_needed, %sai_scap
  br i1 %sai_need_grow, label %sai_grow, label %sai_copy
sai_grow:
  %sai_dblcap = mul i64 %sai_scap, 2
  %sai_newcap = call i64 @llvm.smax.i64(i64 %sai_dblcap, i64 %sai_needed)
  %sai_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sai_data = load ptr, ptr %sai_data_ptr
  %sai_newbuf.raw = call ptr @realloc(ptr %sai_data, i64 %sai_newcap)
  %sai_newbuf = call ptr @__concrete_check_oom(ptr %sai_newbuf.raw)
  store ptr %sai_newbuf, ptr %sai_data_ptr
  store i64 %sai_newcap, ptr %sai_scap_ptr
  br label %sai_copy
sai_copy:
  %sai_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sai_data2 = load ptr, ptr %sai_dp2
  %sai_dst = getelementptr i8, ptr %sai_data2, i64 %sai_slen
  call void @llvm.memcpy.p0.p0.i64(ptr %sai_dst, ptr %sai_buf, i64 %sai_len, i1 false)
  store i64 %sai_needed, ptr %sai_slen_ptr
  ret void
}

define void @string_append_bool(ptr %s, i1 %b) {
entry:
  br i1 %b, label %sab_true, label %sab_false
sab_true:
  %sab_tlen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sab_tlen = load i64, ptr %sab_tlen_ptr
  %sab_tcap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sab_tcap = load i64, ptr %sab_tcap_ptr
  %sab_tneeded = add i64 %sab_tlen, 4
  %sab_tneed_grow = icmp ugt i64 %sab_tneeded, %sab_tcap
  br i1 %sab_tneed_grow, label %sab_tgrow, label %sab_tcopy
sab_tgrow:
  %sab_tdblcap = mul i64 %sab_tcap, 2
  %sab_tnewcap = call i64 @llvm.smax.i64(i64 %sab_tdblcap, i64 %sab_tneeded)
  %sab_tdata_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_tdata = load ptr, ptr %sab_tdata_ptr
  %sab_tnewbuf.raw = call ptr @realloc(ptr %sab_tdata, i64 %sab_tnewcap)
  %sab_tnewbuf = call ptr @__concrete_check_oom(ptr %sab_tnewbuf.raw)
  store ptr %sab_tnewbuf, ptr %sab_tdata_ptr
  store i64 %sab_tnewcap, ptr %sab_tcap_ptr
  br label %sab_tcopy
sab_tcopy:
  %sab_tdp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_tdata2 = load ptr, ptr %sab_tdp2
  %sab_tdst = getelementptr i8, ptr %sab_tdata2, i64 %sab_tlen
  call void @llvm.memcpy.p0.p0.i64(ptr %sab_tdst, ptr @.str_true, i64 4, i1 false)
  store i64 %sab_tneeded, ptr %sab_tlen_ptr
  ret void
sab_false:
  %sab_flen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sab_flen = load i64, ptr %sab_flen_ptr
  %sab_fcap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sab_fcap = load i64, ptr %sab_fcap_ptr
  %sab_fneeded = add i64 %sab_flen, 5
  %sab_fneed_grow = icmp ugt i64 %sab_fneeded, %sab_fcap
  br i1 %sab_fneed_grow, label %sab_fgrow, label %sab_fcopy
sab_fgrow:
  %sab_fdblcap = mul i64 %sab_fcap, 2
  %sab_fnewcap = call i64 @llvm.smax.i64(i64 %sab_fdblcap, i64 %sab_fneeded)
  %sab_fdata_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_fdata = load ptr, ptr %sab_fdata_ptr
  %sab_fnewbuf.raw = call ptr @realloc(ptr %sab_fdata, i64 %sab_fnewcap)
  %sab_fnewbuf = call ptr @__concrete_check_oom(ptr %sab_fnewbuf.raw)
  store ptr %sab_fnewbuf, ptr %sab_fdata_ptr
  store i64 %sab_fnewcap, ptr %sab_fcap_ptr
  br label %sab_fcopy
sab_fcopy:
  %sab_fdp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_fdata2 = load ptr, ptr %sab_fdp2
  %sab_fdst = getelementptr i8, ptr %sab_fdata2, i64 %sab_flen
  call void @llvm.memcpy.p0.p0.i64(ptr %sab_fdst, ptr @.str_false, i64 5, i1 false)
  store i64 %sab_fneeded, ptr %sab_flen_ptr
  ret void
}

define void @string_reserve(ptr %s, i64 %extra) {
entry:
  %sr_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sr_cap = load i64, ptr %sr_cap_ptr
  %sr_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sr_len = load i64, ptr %sr_len_ptr
  %sr_needed = add i64 %sr_len, %extra
  %sr_need_grow = icmp ugt i64 %sr_needed, %sr_cap
  br i1 %sr_need_grow, label %sr_grow, label %sr_done
sr_grow:
  %sr_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sr_data = load ptr, ptr %sr_data_ptr
  %sr_newbuf.raw = call ptr @realloc(ptr %sr_data, i64 %sr_needed)
  %sr_newbuf = call ptr @__concrete_check_oom(ptr %sr_newbuf.raw)
  store ptr %sr_newbuf, ptr %sr_data_ptr
  store i64 %sr_needed, ptr %sr_cap_ptr
  br label %sr_done
sr_done:
  ret void
}

define i64 @clock_monotonic_ns() {
entry:
  %ts = alloca [2 x i64]
  %clk_ret = call i32 @clock_gettime(i32 6, ptr %ts)
  %sec_ptr = getelementptr i64, ptr %ts, i64 0
  %sec = load i64, ptr %sec_ptr
  %nsec_ptr = getelementptr i64, ptr %ts, i64 1
  %nsec = load i64, ptr %nsec_ptr
  %sec_ns = mul i64 %sec, 1000000000
  %total = add i64 %sec_ns, %nsec
  ret i64 %total
}

define i64 @vec_len(ptr %vec) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  ret i64 %len
}

define void @vec_free(ptr %vec) {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  call void @free(ptr %data)
  ret void
}

