; Generated by Concrete compiler (SSA path)
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx14.0.0"
%struct.String = type { ptr, i64, i64 }
%struct.Vec = type { ptr, i64, i64 }
%variant.Option.Some = type { i64 }
%variant.Option.None = type {}
%enum.Option = type { i32, [12 x i8] }
%variant.Result.Ok = type { i64 }
%variant.Result.Err = type { i64 }
%enum.Result = type { i32, [12 x i8] }
%struct.ExprStats = type { i32, i32 }
@__concrete_argc = private global i32 0
@__concrete_argv = private global ptr null
@fmt.main = private constant [6 x i8] c"%lld\0A\00"
@.fmt_ld = private constant [4 x i8] c"%ld\00"
@.fmt_str = private constant [5 x i8] c"%.*s\00"
@.str_true = private constant [5 x i8] c"true\00"
@.str_false = private constant [6 x i8] c"false\00"
@.fmt_f = private constant [3 x i8] c"%g\00"
declare ptr @malloc(i64)
declare void @free(ptr)
declare ptr @realloc(ptr, i64)
declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
declare i64 @write(i32, ptr, i64)
declare void @abort()
declare i32 @printf(ptr, ...)
declare i64 @strlen(ptr)
declare ptr @memset(ptr, i32, i64)
declare i32 @memcmp(ptr, ptr, i64)
declare i32 @snprintf(ptr, i64, ptr, ...)
declare i64 @strtol(ptr, ptr, i32)
declare i64 @llvm.smax.i64(i64, i64)
declare i64 @llvm.smin.i64(i64, i64)
declare i32 @clock_gettime(i32, ptr)
declare i32 @putchar(i32)
define void @stack_push(ptr %stack, ptr %sp, i32 %val) {
entry:
  %ssa.t0 = alloca i32
  %ssa.t1 = alloca i32
  %t0 = load i32, ptr %sp
  %t1 = sext i32 %t0 to i64
  %t2 = call i64 @vec_len(ptr %stack)
  %t3 = icmp sge i64 %t1, %t2
  br i1 %t3, label %then0, label %else1
then0:
  store i32 %val, ptr %ssa.t0
  call void @vec_push_4(ptr %stack, ptr %ssa.t0)
  br label %merge2
else1:
  store i32 %val, ptr %ssa.t1
  call void @vec_set_4(ptr %stack, i64 %t1, ptr %ssa.t1)
  br label %merge2
merge2:
  %t4 = load i32, ptr %sp
  %t5 = add i32 %t4, 1
  store i32 %t5, ptr %sp
  ret void
}

define i32 @stack_pop(ptr %stack, ptr %sp) {
entry:
  %t0 = load i32, ptr %sp
  %t1 = sub i32 %t0, 1
  store i32 %t1, ptr %sp
  %t3 = sext i32 %t1 to i64
  %ssa.t2 = call ptr @vec_get_4(ptr %stack, i64 %t3)
  %t4 = load i32, ptr %ssa.t2
  ret i32 %t4
}

define i32 @evaluate(ptr %program, i32 %prog_len) {
entry:
  %agg.1 = alloca %struct.Vec
  %mutref.15 = alloca %struct.Vec
  %mutref.16 = alloca i32
  %mutref.22 = alloca i32
  %mutref.27 = alloca i32
  %mutref.31 = alloca %struct.Vec
  %mutref.32 = alloca i32
  %mutref.39 = alloca i32
  %mutref.44 = alloca i32
  %mutref.48 = alloca %struct.Vec
  %mutref.49 = alloca i32
  %mutref.55 = alloca i32
  %mutref.60 = alloca i32
  %mutref.64 = alloca %struct.Vec
  %mutref.65 = alloca i32
  %borrow.21 = alloca %struct.Vec
  %borrow.26 = alloca %struct.Vec
  %borrow.38 = alloca %struct.Vec
  %borrow.43 = alloca %struct.Vec
  %borrow.54 = alloca %struct.Vec
  %borrow.59 = alloca %struct.Vec
  %borrow.75 = alloca %struct.Vec
  %ssa.t6 = alloca %struct.Vec
  %t0 = call %struct.Vec @vec_new_4()
  store %struct.Vec %t0, ptr %agg.1
  br label %while.hdr0
while.hdr0:
  %phi.4 = phi i32 [0, %entry], [%if.phi.71, %merge5]
  %phi.6 = phi i32 [0, %entry], [%t73, %merge5]
  %t7 = icmp slt i32 %phi.6, %prog_len
  br i1 %t7, label %while.body1, label %while.exit2
while.body1:
  %t8 = sext i32 %phi.6 to i64
  %ssa.t3 = call ptr @vec_get_4(ptr %program, i64 %t8)
  %t9 = load i32, ptr %ssa.t3
  %t10 = icmp eq i32 %t9, 0
  br i1 %t10, label %then3, label %else4
then3:
  %t11 = add i32 %phi.6, 1
  %t12 = sext i32 %t11 to i64
  %ssa.t4 = call ptr @vec_get_4(ptr %program, i64 %t12)
  %t13 = load i32, ptr %ssa.t4
  %pload.14 = load %struct.Vec, ptr %agg.1
  store %struct.Vec %pload.14, ptr %mutref.15
  store i32 %phi.4, ptr %mutref.16
  call void @stack_push(ptr %mutref.15, ptr %mutref.16, i32 %t13)
  %wb.17 = load %struct.Vec, ptr %mutref.15
  store %struct.Vec %wb.17, ptr %agg.1
  %wb.18 = load i32, ptr %mutref.16
  br label %merge5
else4:
  %t19 = icmp eq i32 %t9, 1
  br i1 %t19, label %then6, label %else7
then6:
  %pload.20 = load %struct.Vec, ptr %agg.1
  store %struct.Vec %pload.20, ptr %borrow.21
  store i32 %phi.4, ptr %mutref.22
  %t23 = call i32 @stack_pop(ptr %borrow.21, ptr %mutref.22)
  %wb.24 = load i32, ptr %mutref.22
  %pload.25 = load %struct.Vec, ptr %agg.1
  store %struct.Vec %pload.25, ptr %borrow.26
  store i32 %wb.24, ptr %mutref.27
  %t28 = call i32 @stack_pop(ptr %borrow.26, ptr %mutref.27)
  %wb.29 = load i32, ptr %mutref.27
  %pload.30 = load %struct.Vec, ptr %agg.1
  store %struct.Vec %pload.30, ptr %mutref.31
  store i32 %wb.29, ptr %mutref.32
  %t33 = add i32 %t28, %t23
  call void @stack_push(ptr %mutref.31, ptr %mutref.32, i32 %t33)
  %wb.34 = load %struct.Vec, ptr %mutref.31
  store %struct.Vec %wb.34, ptr %agg.1
  %wb.35 = load i32, ptr %mutref.32
  br label %merge8
else7:
  %t36 = icmp eq i32 %t9, 2
  br i1 %t36, label %then9, label %else10
then9:
  %pload.37 = load %struct.Vec, ptr %agg.1
  store %struct.Vec %pload.37, ptr %borrow.38
  store i32 %phi.4, ptr %mutref.39
  %t40 = call i32 @stack_pop(ptr %borrow.38, ptr %mutref.39)
  %wb.41 = load i32, ptr %mutref.39
  %pload.42 = load %struct.Vec, ptr %agg.1
  store %struct.Vec %pload.42, ptr %borrow.43
  store i32 %wb.41, ptr %mutref.44
  %t45 = call i32 @stack_pop(ptr %borrow.43, ptr %mutref.44)
  %wb.46 = load i32, ptr %mutref.44
  %pload.47 = load %struct.Vec, ptr %agg.1
  store %struct.Vec %pload.47, ptr %mutref.48
  store i32 %wb.46, ptr %mutref.49
  %t50 = sub i32 %t45, %t40
  call void @stack_push(ptr %mutref.48, ptr %mutref.49, i32 %t50)
  %wb.51 = load %struct.Vec, ptr %mutref.48
  store %struct.Vec %wb.51, ptr %agg.1
  %wb.52 = load i32, ptr %mutref.49
  br label %merge11
else10:
  %pload.53 = load %struct.Vec, ptr %agg.1
  store %struct.Vec %pload.53, ptr %borrow.54
  store i32 %phi.4, ptr %mutref.55
  %t56 = call i32 @stack_pop(ptr %borrow.54, ptr %mutref.55)
  %wb.57 = load i32, ptr %mutref.55
  %pload.58 = load %struct.Vec, ptr %agg.1
  store %struct.Vec %pload.58, ptr %borrow.59
  store i32 %wb.57, ptr %mutref.60
  %t61 = call i32 @stack_pop(ptr %borrow.59, ptr %mutref.60)
  %wb.62 = load i32, ptr %mutref.60
  %pload.63 = load %struct.Vec, ptr %agg.1
  store %struct.Vec %pload.63, ptr %mutref.64
  store i32 %wb.62, ptr %mutref.65
  %t66 = mul i32 %t61, %t56
  call void @stack_push(ptr %mutref.64, ptr %mutref.65, i32 %t66)
  %wb.67 = load %struct.Vec, ptr %mutref.64
  store %struct.Vec %wb.67, ptr %agg.1
  %wb.68 = load i32, ptr %mutref.65
  br label %merge11
merge11:
  %if.phi.69 = phi i32 [%wb.52, %then9], [%wb.68, %else10]
  br label %merge8
merge8:
  %if.phi.70 = phi i32 [%wb.35, %then6], [%if.phi.69, %merge11]
  br label %merge5
merge5:
  %if.phi.71 = phi i32 [%wb.18, %then3], [%if.phi.70, %merge8]
  %if.phi.72 = phi i32 [%t11, %then3], [%phi.6, %merge8]
  %t73 = add i32 %if.phi.72, 1
  br label %while.hdr0
while.exit2:
  %unpro.74 = load %struct.Vec, ptr %agg.1
  store %struct.Vec %unpro.74, ptr %borrow.75
  %t76 = sub i32 %phi.4, 1
  %t77 = sext i32 %t76 to i64
  %ssa.t5 = call ptr @vec_get_4(ptr %borrow.75, i64 %t77)
  %t78 = load i32, ptr %ssa.t5
  store %struct.Vec %unpro.74, ptr %ssa.t6
  call void @vec_free(ptr %ssa.t6)
  ret i32 %t78
}

define %struct.ExprStats @analyze(ptr %program, i32 %prog_len) {
entry:
  %t16 = alloca %struct.ExprStats
  br label %while.hdr0
while.hdr0:
  %phi.2 = phi i32 [0, %entry], [%if.phi.13, %merge5]
  %phi.3 = phi i32 [0, %entry], [%if.phi.14, %merge5]
  %phi.4 = phi i32 [0, %entry], [%if.phi.15, %merge5]
  %t5 = icmp slt i32 %phi.4, %prog_len
  br i1 %t5, label %while.body1, label %while.exit2
while.body1:
  %t6 = sext i32 %phi.4 to i64
  %ssa.t7 = call ptr @vec_get_4(ptr %program, i64 %t6)
  %t7 = load i32, ptr %ssa.t7
  %t8 = icmp eq i32 %t7, 0
  br i1 %t8, label %then3, label %else4
then3:
  %t9 = add i32 %phi.3, 1
  %t10 = add i32 %phi.4, 2
  br label %merge5
else4:
  %t11 = add i32 %phi.2, 1
  %t12 = add i32 %phi.4, 1
  br label %merge5
merge5:
  %if.phi.13 = phi i32 [%phi.2, %then3], [%t11, %else4]
  %if.phi.14 = phi i32 [%t9, %then3], [%phi.3, %else4]
  %if.phi.15 = phi i32 [%t10, %then3], [%t12, %else4]
  br label %while.hdr0
while.exit2:
  store i32 %phi.2, ptr %t16
  %t18 = getelementptr i8, ptr %t16, i64 4
  store i32 %phi.3, ptr %t18
  %t19 = load %struct.ExprStats, ptr %t16
  ret %struct.ExprStats %t19
}

define i32 @build_expr1(ptr %p) {
entry:
  %ssa.t8 = alloca i32
  %ssa.t9 = alloca i32
  %ssa.t10 = alloca i32
  %ssa.t11 = alloca i32
  %ssa.t12 = alloca i32
  %ssa.t13 = alloca i32
  %ssa.t14 = alloca i32
  %ssa.t15 = alloca i32
  %ssa.t16 = alloca i32
  %ssa.t17 = alloca i32
  %ssa.t18 = alloca i32
  store i32 0, ptr %ssa.t8
  call void @vec_push_4(ptr %p, ptr %ssa.t8)
  store i32 3, ptr %ssa.t9
  call void @vec_push_4(ptr %p, ptr %ssa.t9)
  store i32 0, ptr %ssa.t10
  call void @vec_push_4(ptr %p, ptr %ssa.t10)
  store i32 4, ptr %ssa.t11
  call void @vec_push_4(ptr %p, ptr %ssa.t11)
  store i32 1, ptr %ssa.t12
  call void @vec_push_4(ptr %p, ptr %ssa.t12)
  store i32 0, ptr %ssa.t13
  call void @vec_push_4(ptr %p, ptr %ssa.t13)
  store i32 10, ptr %ssa.t14
  call void @vec_push_4(ptr %p, ptr %ssa.t14)
  store i32 0, ptr %ssa.t15
  call void @vec_push_4(ptr %p, ptr %ssa.t15)
  store i32 2, ptr %ssa.t16
  call void @vec_push_4(ptr %p, ptr %ssa.t16)
  store i32 2, ptr %ssa.t17
  call void @vec_push_4(ptr %p, ptr %ssa.t17)
  store i32 3, ptr %ssa.t18
  call void @vec_push_4(ptr %p, ptr %ssa.t18)
  ret i32 11
}

define i32 @build_expr2(ptr %p) {
entry:
  %ssa.t19 = alloca i32
  %ssa.t20 = alloca i32
  %ssa.t21 = alloca i32
  %ssa.t22 = alloca i32
  %ssa.t23 = alloca i32
  store i32 0, ptr %ssa.t19
  call void @vec_push_4(ptr %p, ptr %ssa.t19)
  store i32 5, ptr %ssa.t20
  call void @vec_push_4(ptr %p, ptr %ssa.t20)
  store i32 0, ptr %ssa.t21
  call void @vec_push_4(ptr %p, ptr %ssa.t21)
  store i32 9, ptr %ssa.t22
  call void @vec_push_4(ptr %p, ptr %ssa.t22)
  store i32 1, ptr %ssa.t23
  call void @vec_push_4(ptr %p, ptr %ssa.t23)
  ret i32 5
}

define i32 @build_expr3(ptr %p) {
entry:
  %ssa.t24 = alloca i32
  %ssa.t25 = alloca i32
  %ssa.t26 = alloca i32
  %ssa.t27 = alloca i32
  %ssa.t28 = alloca i32
  %ssa.t29 = alloca i32
  %ssa.t30 = alloca i32
  %ssa.t31 = alloca i32
  %ssa.t32 = alloca i32
  %ssa.t33 = alloca i32
  %ssa.t34 = alloca i32
  %ssa.t35 = alloca i32
  %ssa.t36 = alloca i32
  %ssa.t37 = alloca i32
  store i32 0, ptr %ssa.t24
  call void @vec_push_4(ptr %p, ptr %ssa.t24)
  store i32 6, ptr %ssa.t25
  call void @vec_push_4(ptr %p, ptr %ssa.t25)
  store i32 0, ptr %ssa.t26
  call void @vec_push_4(ptr %p, ptr %ssa.t26)
  store i32 7, ptr %ssa.t27
  call void @vec_push_4(ptr %p, ptr %ssa.t27)
  store i32 3, ptr %ssa.t28
  call void @vec_push_4(ptr %p, ptr %ssa.t28)
  store i32 0, ptr %ssa.t29
  call void @vec_push_4(ptr %p, ptr %ssa.t29)
  store i32 2, ptr %ssa.t30
  call void @vec_push_4(ptr %p, ptr %ssa.t30)
  store i32 0, ptr %ssa.t31
  call void @vec_push_4(ptr %p, ptr %ssa.t31)
  store i32 3, ptr %ssa.t32
  call void @vec_push_4(ptr %p, ptr %ssa.t32)
  store i32 3, ptr %ssa.t33
  call void @vec_push_4(ptr %p, ptr %ssa.t33)
  store i32 2, ptr %ssa.t34
  call void @vec_push_4(ptr %p, ptr %ssa.t34)
  store i32 0, ptr %ssa.t35
  call void @vec_push_4(ptr %p, ptr %ssa.t35)
  store i32 4, ptr %ssa.t36
  call void @vec_push_4(ptr %p, ptr %ssa.t36)
  store i32 1, ptr %ssa.t37
  call void @vec_push_4(ptr %p, ptr %ssa.t37)
  ret i32 14
}

define i32 @build_expr4(ptr %p) {
entry:
  %ssa.t38 = alloca i32
  %ssa.t39 = alloca i32
  %ssa.t40 = alloca i32
  %ssa.t41 = alloca i32
  %ssa.t42 = alloca i32
  %ssa.t43 = alloca i32
  %ssa.t44 = alloca i32
  %ssa.t45 = alloca i32
  store i32 0, ptr %ssa.t38
  call void @vec_push_4(ptr %p, ptr %ssa.t38)
  store i32 2, ptr %ssa.t39
  call void @vec_push_4(ptr %p, ptr %ssa.t39)
  store i32 0, ptr %ssa.t40
  call void @vec_push_4(ptr %p, ptr %ssa.t40)
  store i32 3, ptr %ssa.t41
  call void @vec_push_4(ptr %p, ptr %ssa.t41)
  store i32 0, ptr %ssa.t42
  call void @vec_push_4(ptr %p, ptr %ssa.t42)
  store i32 8, ptr %ssa.t43
  call void @vec_push_4(ptr %p, ptr %ssa.t43)
  store i32 1, ptr %ssa.t44
  call void @vec_push_4(ptr %p, ptr %ssa.t44)
  store i32 3, ptr %ssa.t45
  call void @vec_push_4(ptr %p, ptr %ssa.t45)
  ret i32 8
}

define i64 @user_main() {
entry:
  %mutref.1 = alloca %struct.Vec
  %mutref.19 = alloca %struct.Vec
  %mutref.26 = alloca %struct.Vec
  %mutref.33 = alloca %struct.Vec
  %borrow.4 = alloca %struct.Vec
  %ssa.t46 = alloca %struct.Vec
  %borrow.7 = alloca %struct.Vec
  %ssa.t47 = alloca %struct.ExprStats
  %ssa.t48 = alloca %struct.Vec
  %ssa.t49 = alloca %struct.ExprStats
  %ssa.t50 = alloca %struct.Vec
  %borrow.15 = alloca %struct.ExprStats
  %ssa.t51 = alloca %struct.Vec
  %ssa.t52 = alloca %struct.Vec
  %borrow.22 = alloca %struct.Vec
  %ssa.t53 = alloca %struct.Vec
  %ssa.t54 = alloca %struct.Vec
  %borrow.29 = alloca %struct.Vec
  %ssa.t55 = alloca %struct.Vec
  %ssa.t56 = alloca %struct.Vec
  %borrow.36 = alloca %struct.Vec
  %ssa.t57 = alloca %struct.Vec
  %ssa.t58 = alloca %struct.Vec
  %t0 = call %struct.Vec @vec_new_4()
  store %struct.Vec %t0, ptr %mutref.1
  %t2 = call i32 @build_expr1(ptr %mutref.1)
  %wb.3 = load %struct.Vec, ptr %mutref.1
  store %struct.Vec %wb.3, ptr %borrow.4
  %t5 = call i32 @evaluate(ptr %borrow.4, i32 %t2)
  %t6 = icmp ne i32 %t5, 56
  br i1 %t6, label %then0, label %merge2
then0:
  store %struct.Vec %wb.3, ptr %ssa.t46
  call void @vec_free(ptr %ssa.t46)
  ret i64 1
merge2:
  store %struct.Vec %wb.3, ptr %borrow.7
  %t8 = call %struct.ExprStats @analyze(ptr %borrow.7, i32 %t2)
  store %struct.ExprStats %t8, ptr %ssa.t47
  %t9 = getelementptr i8, ptr %ssa.t47, i64 4
  %t10 = load i32, ptr %t9
  %t11 = icmp ne i32 %t10, 4
  br i1 %t11, label %then3, label %merge5
then3:
  store %struct.Vec %wb.3, ptr %ssa.t48
  call void @vec_free(ptr %ssa.t48)
  ret i64 2
merge5:
  store %struct.ExprStats %t8, ptr %ssa.t49
  %t13 = load i32, ptr %ssa.t49
  %t14 = icmp ne i32 %t13, 3
  br i1 %t14, label %then6, label %merge8
then6:
  store %struct.Vec %wb.3, ptr %ssa.t50
  call void @vec_free(ptr %ssa.t50)
  ret i64 3
merge8:
  store %struct.ExprStats %t8, ptr %borrow.15
  %t16 = call i32 @compute_complexity_for_ExprStats(ptr %borrow.15)
  %t17 = icmp ne i32 %t16, 10
  br i1 %t17, label %then9, label %merge11
then9:
  store %struct.Vec %wb.3, ptr %ssa.t51
  call void @vec_free(ptr %ssa.t51)
  ret i64 4
merge11:
  store %struct.Vec %wb.3, ptr %ssa.t52
  call void @vec_free(ptr %ssa.t52)
  %t18 = call %struct.Vec @vec_new_4()
  store %struct.Vec %t18, ptr %mutref.19
  %t20 = call i32 @build_expr2(ptr %mutref.19)
  %wb.21 = load %struct.Vec, ptr %mutref.19
  store %struct.Vec %wb.21, ptr %borrow.22
  %t23 = call i32 @evaluate(ptr %borrow.22, i32 %t20)
  %t24 = icmp ne i32 %t23, 14
  br i1 %t24, label %then12, label %merge14
then12:
  store %struct.Vec %wb.21, ptr %ssa.t53
  call void @vec_free(ptr %ssa.t53)
  ret i64 5
merge14:
  store %struct.Vec %wb.21, ptr %ssa.t54
  call void @vec_free(ptr %ssa.t54)
  %t25 = call %struct.Vec @vec_new_4()
  store %struct.Vec %t25, ptr %mutref.26
  %t27 = call i32 @build_expr3(ptr %mutref.26)
  %wb.28 = load %struct.Vec, ptr %mutref.26
  store %struct.Vec %wb.28, ptr %borrow.29
  %t30 = call i32 @evaluate(ptr %borrow.29, i32 %t27)
  %t31 = icmp ne i32 %t30, 40
  br i1 %t31, label %then15, label %merge17
then15:
  store %struct.Vec %wb.28, ptr %ssa.t55
  call void @vec_free(ptr %ssa.t55)
  ret i64 6
merge17:
  store %struct.Vec %wb.28, ptr %ssa.t56
  call void @vec_free(ptr %ssa.t56)
  %t32 = call %struct.Vec @vec_new_4()
  store %struct.Vec %t32, ptr %mutref.33
  %t34 = call i32 @build_expr4(ptr %mutref.33)
  %wb.35 = load %struct.Vec, ptr %mutref.33
  store %struct.Vec %wb.35, ptr %borrow.36
  %t37 = call i32 @evaluate(ptr %borrow.36, i32 %t34)
  %t38 = icmp ne i32 %t37, 22
  br i1 %t38, label %then18, label %merge20
then18:
  store %struct.Vec %wb.35, ptr %ssa.t57
  call void @vec_free(ptr %ssa.t57)
  ret i64 7
merge20:
  store %struct.Vec %wb.35, ptr %ssa.t58
  call void @vec_free(ptr %ssa.t58)
  %t39 = sub i32 %t5, %t30
  %t40 = add i32 %t39, %t23
  %t41 = add i32 %t40, 12
  %t42 = icmp ne i32 %t41, 42
  br i1 %t42, label %then21, label %merge23
then21:
  ret i64 8
merge23:
  %t43 = add i32 %t37, %t23
  %t44 = add i32 %t43, 6
  %t45 = icmp ne i32 %t44, 42
  br i1 %t45, label %then24, label %merge26
then24:
  ret i64 9
merge26:
  %t46 = sext i32 %t41 to i64
  ret i64 %t46
}

define i32 @ExprStats_complexity(ptr %self) {
entry:
  %t1 = load i32, ptr %self
  %t2 = shl i32 %t1, 1
  %t3 = getelementptr i8, ptr %self, i64 4
  %t4 = load i32, ptr %t3
  %t5 = add i32 %t2, %t4
  ret i32 %t5
}

define i32 @compute_complexity_for_ExprStats(ptr %item) {
entry:
  %t0 = call i32 @ExprStats_complexity(ptr %item)
  ret i32 %t0
}

define i32 @__concrete_get_argc() {
entry:
  %argc = load i32, ptr @__concrete_argc
  ret i32 %argc
}

define ptr @__concrete_get_argv(i32 %idx) {
entry:
  %argv = load ptr, ptr @__concrete_argv
  %idx64 = sext i32 %idx to i64
  %argp = getelementptr ptr, ptr %argv, i64 %idx64
  %arg = load ptr, ptr %argp
  ret ptr %arg
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  store i32 %argc, ptr @__concrete_argc
  store ptr %argv, ptr @__concrete_argv
  %result = call i64 @user_main()
  %fmt = getelementptr [6 x i8], ptr @fmt.main, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %fmt, i64 %result)
  ret i32 0
}

define ptr @__concrete_check_oom(ptr %p) {
entry:
  %is_null = icmp eq ptr %p, null
  br i1 %is_null, label %oom, label %ok
oom:
  call void @abort()
  unreachable
ok:
  ret ptr %p
}

define i64 @string_length(ptr %s) {
entry:
  %len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len = load i64, ptr %len_ptr
  ret i64 %len
}

define void @drop_string(ptr %s) {
entry:
  %data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data = load ptr, ptr %data_ptr
  call void @free(ptr %data)
  ret void
}

define %struct.String @string_concat(ptr %a, ptr %b) {
entry:
  %a_data_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 0
  %a_data = load ptr, ptr %a_data_ptr
  %a_len_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 1
  %a_len = load i64, ptr %a_len_ptr
  %b_data_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 0
  %b_data = load ptr, ptr %b_data_ptr
  %b_len_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 1
  %b_len = load i64, ptr %b_len_ptr
  %total_len = add i64 %a_len, %b_len
  %buf.raw = call ptr @malloc(i64 %total_len)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %buf, ptr %a_data, i64 %a_len, i1 false)
  %dst = getelementptr i8, ptr %buf, i64 %a_len
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %b_data, i64 %b_len, i1 false)
  call void @free(ptr %a_data)
  call void @free(ptr %b_data)
  %sc_alloca = alloca %struct.String
  %sc_data_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 0
  store ptr %buf, ptr %sc_data_ptr
  %sc_len_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 1
  store i64 %total_len, ptr %sc_len_ptr
  %sc_cap_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 2
  store i64 %total_len, ptr %sc_cap_ptr
  %sc_result = load %struct.String, ptr %sc_alloca
  ret %struct.String %sc_result
}

define %struct.String @string_slice(ptr %s, i64 %start, i64 %end_) {
entry:
  %len_ptr.ss = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len.ss = load i64, ptr %len_ptr.ss
  %s_clamped = call i64 @llvm.smax.i64(i64 %start, i64 0)
  %s_min = call i64 @llvm.smin.i64(i64 %s_clamped, i64 %len.ss)
  %e_clamped = call i64 @llvm.smax.i64(i64 %end_, i64 0)
  %e_min = call i64 @llvm.smin.i64(i64 %e_clamped, i64 %len.ss)
  %e_final = call i64 @llvm.smax.i64(i64 %e_min, i64 %s_min)
  %slice_len = sub i64 %e_final, %s_min
  %slice_buf.raw = call ptr @malloc(i64 %slice_len)
  %slice_buf = call ptr @__concrete_check_oom(ptr %slice_buf.raw)
  %data_ptr.ss = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data.ss = load ptr, ptr %data_ptr.ss
  %src = getelementptr i8, ptr %data.ss, i64 %s_min
  call void @llvm.memcpy.p0.p0.i64(ptr %slice_buf, ptr %src, i64 %slice_len, i1 false)
  %res.ss = alloca %struct.String
  %res_d.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 0
  store ptr %slice_buf, ptr %res_d.ss
  %res_l.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 1
  store i64 %slice_len, ptr %res_l.ss
  %res_c.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 2
  store i64 %slice_len, ptr %res_c.ss
  %result.ss = load %struct.String, ptr %res.ss
  ret %struct.String %result.ss
}

define %struct.String @string_substr(ptr %s, i64 %start, i64 %len) {
entry:
  %end_ = add i64 %start, %len
  %result.ssub = call %struct.String @string_slice(ptr %s, i64 %start, i64 %end_)
  ret %struct.String %result.ssub
}

define i64 @string_char_at(ptr %s, i64 %index) {
entry:
  %len_ptr.sca = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len.sca = load i64, ptr %len_ptr.sca
  %neg = icmp slt i64 %index, 0
  %oob = icmp sge i64 %index, %len.sca
  %bad = or i1 %neg, %oob
  br i1 %bad, label %ret_neg, label %ok_idx
ret_neg:
  ret i64 -1
ok_idx:
  %data_ptr.sca = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data.sca = load ptr, ptr %data_ptr.sca
  %char_ptr = getelementptr i8, ptr %data.sca, i64 %index
  %byte = load i8, ptr %char_ptr
  %char = zext i8 %byte to i64
  ret i64 %char
}

define i1 @string_contains(ptr %haystack, ptr %needle) {
entry:
  %h_data_ptr = getelementptr %struct.String, ptr %haystack, i32 0, i32 0
  %h_data = load ptr, ptr %h_data_ptr
  %h_len_ptr = getelementptr %struct.String, ptr %haystack, i32 0, i32 1
  %h_len = load i64, ptr %h_len_ptr
  %n_data_ptr = getelementptr %struct.String, ptr %needle, i32 0, i32 0
  %n_data = load ptr, ptr %n_data_ptr
  %n_len_ptr = getelementptr %struct.String, ptr %needle, i32 0, i32 1
  %n_len = load i64, ptr %n_len_ptr
  %n_empty = icmp eq i64 %n_len, 0
  br i1 %n_empty, label %found, label %check_len
check_len:
  %too_long = icmp ugt i64 %n_len, %h_len
  br i1 %too_long, label %not_found, label %loop_start
loop_start:
  %max_i = sub i64 %h_len, %n_len
  br label %loop
loop:
  %i = phi i64 [0, %loop_start], [%i_next, %loop_cont]
  %h_ptr = getelementptr i8, ptr %h_data, i64 %i
  %cmp = call i32 @memcmp(ptr %h_ptr, ptr %n_data, i64 %n_len)
  %match = icmp eq i32 %cmp, 0
  br i1 %match, label %found, label %loop_cont
loop_cont:
  %i_next = add i64 %i, 1
  %done = icmp ugt i64 %i_next, %max_i
  br i1 %done, label %not_found, label %loop
found:
  ret i1 1
not_found:
  ret i1 0
}

define i1 @string_eq(ptr %a, ptr %b) {
entry:
  %a_len_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 1
  %a_len = load i64, ptr %a_len_ptr
  %b_len_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 1
  %b_len = load i64, ptr %b_len_ptr
  %len_eq = icmp eq i64 %a_len, %b_len
  br i1 %len_eq, label %cmp_data, label %not_eq
cmp_data:
  %zero_len = icmp eq i64 %a_len, 0
  br i1 %zero_len, label %eq, label %do_cmp
do_cmp:
  %a_data_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 0
  %a_data = load ptr, ptr %a_data_ptr
  %b_data_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 0
  %b_data = load ptr, ptr %b_data_ptr
  %cmp_res = call i32 @memcmp(ptr %a_data, ptr %b_data, i64 %a_len)
  %eq_data = icmp eq i32 %cmp_res, 0
  br i1 %eq_data, label %eq, label %not_eq
eq:
  ret i1 1
not_eq:
  ret i1 0
}

define %struct.String @int_to_string(i64 %n) {
entry:
  %buf.raw = call ptr @malloc(i64 32)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  %fmt_its = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %buf, i64 32, ptr %fmt_its, i64 %n)
  %wext = sext i32 %written to i64
  %res.its = alloca %struct.String
  %res_d.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 0
  store ptr %buf, ptr %res_d.its
  %res_l.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 1
  store i64 %wext, ptr %res_l.its
  %res_c.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 2
  store i64 32, ptr %res_c.its
  %result.its = load %struct.String, ptr %res.its
  ret %struct.String %result.its
}

define %enum.Result @string_to_int(ptr %s) {
entry:
  %sti_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sti_data = load ptr, ptr %sti_data_ptr
  %sti_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sti_len = load i64, ptr %sti_len_ptr
  %sti_buf_sz = add i64 %sti_len, 1
  %sti_buf.raw = call ptr @malloc(i64 %sti_buf_sz)
  %sti_buf = call ptr @__concrete_check_oom(ptr %sti_buf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %sti_buf, ptr %sti_data, i64 %sti_len, i1 false)
  %sti_null = getelementptr i8, ptr %sti_buf, i64 %sti_len
  store i8 0, ptr %sti_null
  %endptr_alloca = alloca ptr
  %sti_val = call i64 @strtol(ptr %sti_buf, ptr %endptr_alloca, i32 10)
  %endptr = load ptr, ptr %endptr_alloca
  %end_expected = getelementptr i8, ptr %sti_buf, i64 %sti_len
  %valid = icmp eq ptr %endptr, %end_expected
  %empty_input = icmp eq i64 %sti_len, 0
  %not_empty = xor i1 %empty_input, 1
  %final_ok = and i1 %valid, %not_empty
  call void @free(ptr %sti_buf)
  %res.sti = alloca %enum.Result
  br i1 %final_ok, label %sti_ok, label %sti_err
sti_ok:
  store i32 0, ptr %res.sti
  %data_ptr.sti_ok = getelementptr i8, ptr %res.sti, i64 8
  store i64 %sti_val, ptr %data_ptr.sti_ok
  br label %sti_done
sti_err:
  store i32 1, ptr %res.sti
  %data_ptr.sti_err = getelementptr i8, ptr %res.sti, i64 8
  store i64 1, ptr %data_ptr.sti_err
  br label %sti_done
sti_done:
  %result.sti = load %enum.Result, ptr %res.sti
  ret %enum.Result %result.sti
}

define %struct.String @bool_to_string(i1 %b) {
entry:
  br i1 %b, label %bts_true, label %bts_false
bts_true:
  %tbuf.raw = call ptr @malloc(i64 4)
  %tbuf = call ptr @__concrete_check_oom(ptr %tbuf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %tbuf, ptr @.str_true, i64 4, i1 false)
  %tres = alloca %struct.String
  %td = getelementptr %struct.String, ptr %tres, i32 0, i32 0
  store ptr %tbuf, ptr %td
  %tl = getelementptr %struct.String, ptr %tres, i32 0, i32 1
  store i64 4, ptr %tl
  %tc = getelementptr %struct.String, ptr %tres, i32 0, i32 2
  store i64 4, ptr %tc
  %tresult = load %struct.String, ptr %tres
  ret %struct.String %tresult
bts_false:
  %fbuf.raw = call ptr @malloc(i64 5)
  %fbuf = call ptr @__concrete_check_oom(ptr %fbuf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %fbuf, ptr @.str_false, i64 5, i1 false)
  %fres = alloca %struct.String
  %fd = getelementptr %struct.String, ptr %fres, i32 0, i32 0
  store ptr %fbuf, ptr %fd
  %fl = getelementptr %struct.String, ptr %fres, i32 0, i32 1
  store i64 5, ptr %fl
  %fc = getelementptr %struct.String, ptr %fres, i32 0, i32 2
  store i64 5, ptr %fc
  %fresult = load %struct.String, ptr %fres
  ret %struct.String %fresult
}

define %struct.String @float_to_string(double %f) {
entry:
  %fbuf.fts.raw = call ptr @malloc(i64 64)
  %fbuf.fts = call ptr @__concrete_check_oom(ptr %fbuf.fts.raw)
  %fmt.fts = getelementptr [3 x i8], ptr @.fmt_f, i64 0, i64 0
  %written.fts = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %fbuf.fts, i64 64, ptr %fmt.fts, double %f)
  %wext.fts = sext i32 %written.fts to i64
  %res.fts = alloca %struct.String
  %res_d.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 0
  store ptr %fbuf.fts, ptr %res_d.fts
  %res_l.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 1
  store i64 %wext.fts, ptr %res_l.fts
  %res_c.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 2
  store i64 64, ptr %res_c.fts
  %result.fts = load %struct.String, ptr %res.fts
  ret %struct.String %result.fts
}

define %struct.String @string_trim(ptr %s) {
entry:
  %st_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %st_data = load ptr, ptr %st_data_ptr
  %st_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %st_len = load i64, ptr %st_len_ptr
  br label %trim_left
trim_left:
  %tl_i = phi i64 [0, %entry], [%tl_next, %tl_ws]
  %tl_done = icmp uge i64 %tl_i, %st_len
  br i1 %tl_done, label %trim_result, label %tl_check
tl_check:
  %tl_ptr = getelementptr i8, ptr %st_data, i64 %tl_i
  %tl_ch = load i8, ptr %tl_ptr
  %tl_is_sp = icmp eq i8 %tl_ch, 32
  %tl_is_tab = icmp eq i8 %tl_ch, 9
  %tl_is_nl = icmp eq i8 %tl_ch, 10
  %tl_is_cr = icmp eq i8 %tl_ch, 13
  %tl_w1 = or i1 %tl_is_sp, %tl_is_tab
  %tl_w2 = or i1 %tl_is_nl, %tl_is_cr
  %tl_is_ws = or i1 %tl_w1, %tl_w2
  br i1 %tl_is_ws, label %tl_ws, label %trim_right_init
tl_ws:
  %tl_next = add i64 %tl_i, 1
  br label %trim_left
trim_right_init:
  %tr_start = sub i64 %st_len, 1
  br label %trim_right
trim_right:
  %tr_i = phi i64 [%tr_start, %trim_right_init], [%tr_prev, %tr_ws]
  %tr_done = icmp ult i64 %tr_i, %tl_i
  br i1 %tr_done, label %trim_result, label %tr_check
tr_check:
  %tr_ptr = getelementptr i8, ptr %st_data, i64 %tr_i
  %tr_ch = load i8, ptr %tr_ptr
  %tr_is_sp = icmp eq i8 %tr_ch, 32
  %tr_is_tab = icmp eq i8 %tr_ch, 9
  %tr_is_nl = icmp eq i8 %tr_ch, 10
  %tr_is_cr = icmp eq i8 %tr_ch, 13
  %tr_w1 = or i1 %tr_is_sp, %tr_is_tab
  %tr_w2 = or i1 %tr_is_nl, %tr_is_cr
  %tr_is_ws = or i1 %tr_w1, %tr_w2
  br i1 %tr_is_ws, label %tr_ws, label %trim_result
tr_ws:
  %tr_prev = sub i64 %tr_i, 1
  br label %trim_right
trim_result:
  %tr_left = phi i64 [%tl_i, %trim_left], [%tl_i, %trim_right], [%tl_i, %tr_check]
  %tr_right_raw = phi i64 [0, %trim_left], [%tl_i, %trim_right], [%tr_i, %tr_check]
  %tr_right = add i64 %tr_right_raw, 1
  %tr_empty = icmp uge i64 %tr_left, %tr_right
  br i1 %tr_empty, label %trim_empty, label %trim_copy
trim_empty:
  %te_buf.raw = call ptr @malloc(i64 1)
  %te_buf = call ptr @__concrete_check_oom(ptr %te_buf.raw)
  %te_res = alloca %struct.String
  %te_d = getelementptr %struct.String, ptr %te_res, i32 0, i32 0
  store ptr %te_buf, ptr %te_d
  %te_l = getelementptr %struct.String, ptr %te_res, i32 0, i32 1
  store i64 0, ptr %te_l
  %te_c = getelementptr %struct.String, ptr %te_res, i32 0, i32 2
  store i64 1, ptr %te_c
  %te_result = load %struct.String, ptr %te_res
  ret %struct.String %te_result
trim_copy:
  %tc_len = sub i64 %tr_right, %tr_left
  %tc_buf.raw = call ptr @malloc(i64 %tc_len)
  %tc_buf = call ptr @__concrete_check_oom(ptr %tc_buf.raw)
  %tc_src = getelementptr i8, ptr %st_data, i64 %tr_left
  call void @llvm.memcpy.p0.p0.i64(ptr %tc_buf, ptr %tc_src, i64 %tc_len, i1 false)
  %tc_res = alloca %struct.String
  %tc_d = getelementptr %struct.String, ptr %tc_res, i32 0, i32 0
  store ptr %tc_buf, ptr %tc_d
  %tc_l = getelementptr %struct.String, ptr %tc_res, i32 0, i32 1
  store i64 %tc_len, ptr %tc_l
  %tc_c = getelementptr %struct.String, ptr %tc_res, i32 0, i32 2
  store i64 %tc_len, ptr %tc_c
  %tc_result = load %struct.String, ptr %tc_res
  ret %struct.String %tc_result
}

define void @print_string(ptr %s) {
entry:
  %ps_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %ps_data = load ptr, ptr %ps_data_ptr
  %ps_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %ps_len = load i64, ptr %ps_len_ptr
  %ps_fmt = getelementptr [5 x i8], ptr @.fmt_str, i64 0, i64 0
  %ps_len32 = trunc i64 %ps_len to i32
  %ps_written = call i32 (ptr, ...) @printf(ptr %ps_fmt, i32 %ps_len32, ptr %ps_data)
  ret void
}

define void @print_int(i64 %n) {
entry:
  %pi_fmt = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %pi_written = call i32 (ptr, ...) @printf(ptr %pi_fmt, i64 %n)
  ret void
}

define void @print_char(i64 %c) {
entry:
  %pc_int = trunc i64 %c to i32
  %pc_wr = call i32 @putchar(i32 %pc_int)
  ret void
}

define void @print_bool(i1 %b) {
entry:
  %is_true = icmp eq i1 %b, 1
  br i1 %is_true, label %print_true, label %print_false
print_true:
  %true_ptr = getelementptr [5 x i8], ptr @.str_true, i64 0, i64 0
  %tw = call i32 (ptr, ...) @printf(ptr %true_ptr)
  ret void
print_false:
  %false_ptr = getelementptr [6 x i8], ptr @.str_false, i64 0, i64 0
  %fw = call i32 (ptr, ...) @printf(ptr %false_ptr)
  ret void
}

define void @string_push_char(ptr %s, i64 %c) {
entry:
  %spc_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %spc_len = load i64, ptr %spc_len_ptr
  %spc_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %spc_cap = load i64, ptr %spc_cap_ptr
  %spc_full = icmp eq i64 %spc_len, %spc_cap
  br i1 %spc_full, label %spc_grow, label %spc_store
spc_grow:
  %spc_newcap = mul i64 %spc_cap, 2
  %spc_nc_clamped = call i64 @llvm.smax.i64(i64 %spc_newcap, i64 8)
  %spc_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %spc_data = load ptr, ptr %spc_data_ptr
  %spc_newbuf.raw = call ptr @realloc(ptr %spc_data, i64 %spc_nc_clamped)
  %spc_newbuf = call ptr @__concrete_check_oom(ptr %spc_newbuf.raw)
  store ptr %spc_newbuf, ptr %spc_data_ptr
  store i64 %spc_nc_clamped, ptr %spc_cap_ptr
  br label %spc_store
spc_store:
  %spc_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %spc_data2 = load ptr, ptr %spc_dp2
  %spc_slot = getelementptr i8, ptr %spc_data2, i64 %spc_len
  %spc_byte = trunc i64 %c to i8
  store i8 %spc_byte, ptr %spc_slot
  %spc_newlen = add i64 %spc_len, 1
  store i64 %spc_newlen, ptr %spc_len_ptr
  ret void
}

define void @string_append(ptr %s, ptr %other) {
entry:
  %sa_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sa_len = load i64, ptr %sa_len_ptr
  %sa_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sa_cap = load i64, ptr %sa_cap_ptr
  %sa_olen_ptr = getelementptr %struct.String, ptr %other, i32 0, i32 1
  %sa_olen = load i64, ptr %sa_olen_ptr
  %sa_needed = add i64 %sa_len, %sa_olen
  %sa_need_grow = icmp ugt i64 %sa_needed, %sa_cap
  br i1 %sa_need_grow, label %sa_grow, label %sa_copy
sa_grow:
  %sa_dblcap = mul i64 %sa_cap, 2
  %sa_newcap = call i64 @llvm.smax.i64(i64 %sa_dblcap, i64 %sa_needed)
  %sa_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sa_data = load ptr, ptr %sa_data_ptr
  %sa_newbuf.raw = call ptr @realloc(ptr %sa_data, i64 %sa_newcap)
  %sa_newbuf = call ptr @__concrete_check_oom(ptr %sa_newbuf.raw)
  store ptr %sa_newbuf, ptr %sa_data_ptr
  store i64 %sa_newcap, ptr %sa_cap_ptr
  br label %sa_copy
sa_copy:
  %sa_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sa_data2 = load ptr, ptr %sa_dp2
  %sa_dst = getelementptr i8, ptr %sa_data2, i64 %sa_len
  %sa_odata_ptr = getelementptr %struct.String, ptr %other, i32 0, i32 0
  %sa_odata = load ptr, ptr %sa_odata_ptr
  call void @llvm.memcpy.p0.p0.i64(ptr %sa_dst, ptr %sa_odata, i64 %sa_olen, i1 false)
  store i64 %sa_needed, ptr %sa_len_ptr
  ret void
}

define void @string_append_int(ptr %s, i64 %n) {
entry:
  %sai_buf = alloca [32 x i8]
  %sai_fmt = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %sai_written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %sai_buf, i64 32, ptr %sai_fmt, i64 %n)
  %sai_len = sext i32 %sai_written to i64
  %sai_slen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sai_slen = load i64, ptr %sai_slen_ptr
  %sai_scap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sai_scap = load i64, ptr %sai_scap_ptr
  %sai_needed = add i64 %sai_slen, %sai_len
  %sai_need_grow = icmp ugt i64 %sai_needed, %sai_scap
  br i1 %sai_need_grow, label %sai_grow, label %sai_copy
sai_grow:
  %sai_dblcap = mul i64 %sai_scap, 2
  %sai_newcap = call i64 @llvm.smax.i64(i64 %sai_dblcap, i64 %sai_needed)
  %sai_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sai_data = load ptr, ptr %sai_data_ptr
  %sai_newbuf.raw = call ptr @realloc(ptr %sai_data, i64 %sai_newcap)
  %sai_newbuf = call ptr @__concrete_check_oom(ptr %sai_newbuf.raw)
  store ptr %sai_newbuf, ptr %sai_data_ptr
  store i64 %sai_newcap, ptr %sai_scap_ptr
  br label %sai_copy
sai_copy:
  %sai_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sai_data2 = load ptr, ptr %sai_dp2
  %sai_dst = getelementptr i8, ptr %sai_data2, i64 %sai_slen
  call void @llvm.memcpy.p0.p0.i64(ptr %sai_dst, ptr %sai_buf, i64 %sai_len, i1 false)
  store i64 %sai_needed, ptr %sai_slen_ptr
  ret void
}

define void @string_append_bool(ptr %s, i1 %b) {
entry:
  br i1 %b, label %sab_true, label %sab_false
sab_true:
  %sab_tlen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sab_tlen = load i64, ptr %sab_tlen_ptr
  %sab_tcap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sab_tcap = load i64, ptr %sab_tcap_ptr
  %sab_tneeded = add i64 %sab_tlen, 4
  %sab_tneed_grow = icmp ugt i64 %sab_tneeded, %sab_tcap
  br i1 %sab_tneed_grow, label %sab_tgrow, label %sab_tcopy
sab_tgrow:
  %sab_tdblcap = mul i64 %sab_tcap, 2
  %sab_tnewcap = call i64 @llvm.smax.i64(i64 %sab_tdblcap, i64 %sab_tneeded)
  %sab_tdata_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_tdata = load ptr, ptr %sab_tdata_ptr
  %sab_tnewbuf.raw = call ptr @realloc(ptr %sab_tdata, i64 %sab_tnewcap)
  %sab_tnewbuf = call ptr @__concrete_check_oom(ptr %sab_tnewbuf.raw)
  store ptr %sab_tnewbuf, ptr %sab_tdata_ptr
  store i64 %sab_tnewcap, ptr %sab_tcap_ptr
  br label %sab_tcopy
sab_tcopy:
  %sab_tdp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_tdata2 = load ptr, ptr %sab_tdp2
  %sab_tdst = getelementptr i8, ptr %sab_tdata2, i64 %sab_tlen
  call void @llvm.memcpy.p0.p0.i64(ptr %sab_tdst, ptr @.str_true, i64 4, i1 false)
  store i64 %sab_tneeded, ptr %sab_tlen_ptr
  ret void
sab_false:
  %sab_flen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sab_flen = load i64, ptr %sab_flen_ptr
  %sab_fcap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sab_fcap = load i64, ptr %sab_fcap_ptr
  %sab_fneeded = add i64 %sab_flen, 5
  %sab_fneed_grow = icmp ugt i64 %sab_fneeded, %sab_fcap
  br i1 %sab_fneed_grow, label %sab_fgrow, label %sab_fcopy
sab_fgrow:
  %sab_fdblcap = mul i64 %sab_fcap, 2
  %sab_fnewcap = call i64 @llvm.smax.i64(i64 %sab_fdblcap, i64 %sab_fneeded)
  %sab_fdata_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_fdata = load ptr, ptr %sab_fdata_ptr
  %sab_fnewbuf.raw = call ptr @realloc(ptr %sab_fdata, i64 %sab_fnewcap)
  %sab_fnewbuf = call ptr @__concrete_check_oom(ptr %sab_fnewbuf.raw)
  store ptr %sab_fnewbuf, ptr %sab_fdata_ptr
  store i64 %sab_fnewcap, ptr %sab_fcap_ptr
  br label %sab_fcopy
sab_fcopy:
  %sab_fdp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_fdata2 = load ptr, ptr %sab_fdp2
  %sab_fdst = getelementptr i8, ptr %sab_fdata2, i64 %sab_flen
  call void @llvm.memcpy.p0.p0.i64(ptr %sab_fdst, ptr @.str_false, i64 5, i1 false)
  store i64 %sab_fneeded, ptr %sab_flen_ptr
  ret void
}

define void @string_reserve(ptr %s, i64 %extra) {
entry:
  %sr_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sr_cap = load i64, ptr %sr_cap_ptr
  %sr_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sr_len = load i64, ptr %sr_len_ptr
  %sr_needed = add i64 %sr_len, %extra
  %sr_need_grow = icmp ugt i64 %sr_needed, %sr_cap
  br i1 %sr_need_grow, label %sr_grow, label %sr_done
sr_grow:
  %sr_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sr_data = load ptr, ptr %sr_data_ptr
  %sr_newbuf.raw = call ptr @realloc(ptr %sr_data, i64 %sr_needed)
  %sr_newbuf = call ptr @__concrete_check_oom(ptr %sr_newbuf.raw)
  store ptr %sr_newbuf, ptr %sr_data_ptr
  store i64 %sr_needed, ptr %sr_cap_ptr
  br label %sr_done
sr_done:
  ret void
}

define i64 @clock_monotonic_ns() {
entry:
  %ts = alloca [2 x i64]
  %clk_ret = call i32 @clock_gettime(i32 6, ptr %ts)
  %sec_ptr = getelementptr i64, ptr %ts, i64 0
  %sec = load i64, ptr %sec_ptr
  %nsec_ptr = getelementptr i64, ptr %ts, i64 1
  %nsec = load i64, ptr %nsec_ptr
  %sec_ns = mul i64 %sec, 1000000000
  %total = add i64 %sec_ns, %nsec
  ret i64 %total
}

define i64 @vec_len(ptr %vec) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  ret i64 %len
}

define void @vec_free(ptr %vec) {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  call void @free(ptr %data)
  ret void
}

define %struct.Vec @vec_new_4() alwaysinline {
entry:
  %buf.raw = call ptr @malloc(i64 32)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  %v = alloca %struct.Vec
  %bp = getelementptr %struct.Vec, ptr %v, i32 0, i32 0
  store ptr %buf, ptr %bp
  %lp = getelementptr %struct.Vec, ptr %v, i32 0, i32 1
  store i64 0, ptr %lp
  %cp = getelementptr %struct.Vec, ptr %v, i32 0, i32 2
  store i64 8, ptr %cp
  %r = load %struct.Vec, ptr %v
  ret %struct.Vec %r
}

define void @vec_push_4(ptr %vec, ptr %val) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  %cp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 2
  %cap = load i64, ptr %cp
  %full = icmp eq i64 %len, %cap
  br i1 %full, label %grow, label %store
grow:
  %newcap = mul i64 %cap, 2
  %newbytes = mul i64 %newcap, 4
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %newbuf.raw = call ptr @realloc(ptr %data, i64 %newbytes)
  %newbuf = call ptr @__concrete_check_oom(ptr %newbuf.raw)
  store ptr %newbuf, ptr %dp
  store i64 %newcap, ptr %cp
  br label %store
store:
  %dp2 = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data2 = load ptr, ptr %dp2
  %offset = mul i64 %len, 4
  %slot = getelementptr i8, ptr %data2, i64 %offset
  call void @llvm.memcpy.p0.p0.i64(ptr %slot, ptr %val, i64 4, i1 false)
  %newlen = add i64 %len, 1
  store i64 %newlen, ptr %lp
  ret void
}

define ptr @vec_get_4(ptr %vec, i64 %idx) alwaysinline {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %offset = mul i64 %idx, 4
  %slot = getelementptr i8, ptr %data, i64 %offset
  ret ptr %slot
}

define void @vec_set_4(ptr %vec, i64 %idx, ptr %val) alwaysinline {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %offset = mul i64 %idx, 4
  %slot = getelementptr i8, ptr %data, i64 %offset
  call void @llvm.memcpy.p0.p0.i64(ptr %slot, ptr %val, i64 4, i1 false)
  ret void
}

define %enum.Option @vec_pop_4_4(ptr %vec) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  %empty = icmp eq i64 %len, 0
  br i1 %empty, label %none, label %some
some:
  %newlen = sub i64 %len, 1
  store i64 %newlen, ptr %lp
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %offset = mul i64 %newlen, 4
  %slot = getelementptr i8, ptr %data, i64 %offset
  %res = alloca %enum.Option
  call void @memset(ptr %res, i32 0, i64 8)
  store i32 0, ptr %res
  %payload = getelementptr i8, ptr %res, i64 4
  call void @llvm.memcpy.p0.p0.i64(ptr %payload, ptr %slot, i64 4, i1 false)
  %r = load %enum.Option, ptr %res
  ret %enum.Option %r
none:
  %res2 = alloca %enum.Option
  call void @memset(ptr %res2, i32 0, i64 8)
  store i32 1, ptr %res2
  %r2 = load %enum.Option, ptr %res2
  ret %enum.Option %r2
}

