; Generated by Concrete compiler (SSA path)
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx14.0.0"
%struct.String = type { ptr, i64, i64 }
%struct.Vec = type { ptr, i64, i64 }
%variant.Option.Some = type { i64 }
%variant.Option.None = type {}
%enum.Option = type { i32, [12 x i8] }
%variant.Result.Ok = type { i64 }
%variant.Result.Err = type { i64 }
%enum.Result = type { i32, [12 x i8] }
%struct.TransResult = type { %enum.State, %enum.Action }
%variant.State.Listen = type {}
%variant.State.SynReceived = type { i32 }
%variant.State.Established = type { i32 }
%variant.State.Closing = type { i32 }
%variant.State.Closed = type {}
%enum.State = type { i32, [4 x i8] }
%variant.Event.Connect = type {}
%variant.Event.Accept = type {}
%variant.Event.Send = type { i32 }
%variant.Event.Close = type {}
%variant.Event.Timeout = type {}
%enum.Event = type { i32, [4 x i8] }
%variant.Action.NoAction = type {}
%variant.Action.Transmit = type { i32 }
%variant.Action.Reset = type {}
%enum.Action = type { i32, [4 x i8] }
%struct.RawCounter = type { i32 }
@__concrete_argc = private global i32 0
@__concrete_argv = private global ptr null
@fmt.main = private constant [6 x i8] c"%lld\0A\00"
@.fmt_ld = private constant [4 x i8] c"%ld\00"
@.fmt_str = private constant [5 x i8] c"%.*s\00"
@.str_true = private constant [5 x i8] c"true\00"
@.str_false = private constant [6 x i8] c"false\00"
@.fmt_f = private constant [3 x i8] c"%g\00"
declare ptr @malloc(i64)
declare void @free(ptr)
declare ptr @realloc(ptr, i64)
declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
declare i64 @write(i32, ptr, i64)
declare void @abort()
declare i32 @printf(ptr, ...)
declare i64 @strlen(ptr)
declare ptr @memset(ptr, i32, i64)
declare i32 @memcmp(ptr, ptr, i64)
declare i32 @snprintf(ptr, i64, ptr, ...)
declare i64 @strtol(ptr, ptr, i32)
declare i64 @llvm.smax.i64(i64, i64)
declare i64 @llvm.smin.i64(i64, i64)
declare i32 @clock_gettime(i32, ptr)
declare i32 @putchar(i32)
define i32 @state_code(ptr %s) {
entry:
  %ssa.t0 = alloca %enum.State
  %t0 = load %enum.State, ptr %s
  store %enum.State %t0, ptr %ssa.t0
  %t2 = load i32, ptr %ssa.t0
  %t3 = sext i32 %t2 to i64
  %t4 = icmp eq i64 %t3, 0
  br i1 %t4, label %arm01, label %check12
arm01:
  ret i32 0
check12:
  %t6 = icmp eq i64 %t3, 1
  br i1 %t6, label %arm13, label %check24
arm13:
  ret i32 1
check24:
  %t10 = icmp eq i64 %t3, 2
  br i1 %t10, label %arm25, label %check36
arm25:
  ret i32 2
check36:
  %t14 = icmp eq i64 %t3, 3
  br i1 %t14, label %arm37, label %check48
arm37:
  ret i32 3
check48:
  %t18 = icmp eq i64 %t3, 4
  br i1 %t18, label %arm49, label %check510
arm49:
  ret i32 4
check510:
  unreachable
}

define %struct.TransResult @transition(ptr %state, ptr %event) {
entry:
  %ssa.t1 = alloca %enum.State
  %ssa.t2 = alloca %enum.Event
  %t12 = alloca %struct.TransResult
  %t13 = alloca %enum.State
  %t18 = alloca %enum.Action
  %t26 = alloca %struct.TransResult
  %t27 = alloca %enum.State
  %t31 = alloca %enum.Action
  %t40 = alloca %struct.TransResult
  %t41 = alloca %enum.State
  %t45 = alloca %enum.Action
  %t52 = alloca %struct.TransResult
  %t53 = alloca %enum.State
  %t57 = alloca %enum.Action
  %t64 = alloca %struct.TransResult
  %t65 = alloca %enum.State
  %t69 = alloca %enum.Action
  %ssa.t3 = alloca %enum.State
  %ssa.t4 = alloca %enum.Event
  %t84 = alloca %struct.TransResult
  %t85 = alloca %enum.State
  %t90 = alloca %enum.Action
  %t99 = alloca %struct.TransResult
  %t100 = alloca %enum.State
  %t106 = alloca %enum.Action
  %t112 = alloca %struct.TransResult
  %t113 = alloca %enum.State
  %t117 = alloca %enum.Action
  %t124 = alloca %struct.TransResult
  %t125 = alloca %enum.State
  %t129 = alloca %enum.Action
  %t136 = alloca %struct.TransResult
  %t139 = alloca %enum.Action
  %t148 = alloca %struct.TransResult
  %t151 = alloca %enum.Action
  %ssa.t5 = alloca %enum.State
  %ssa.t6 = alloca %enum.Event
  %ssa.t7 = alloca %enum.Event
  %t168 = alloca %struct.TransResult
  %t169 = alloca %enum.State
  %t175 = alloca %enum.Action
  %t183 = alloca %struct.TransResult
  %t184 = alloca %enum.State
  %t189 = alloca %enum.Action
  %t197 = alloca %struct.TransResult
  %t198 = alloca %enum.State
  %t203 = alloca %enum.Action
  %t210 = alloca %struct.TransResult
  %t213 = alloca %enum.Action
  %t220 = alloca %struct.TransResult
  %t223 = alloca %enum.Action
  %ssa.t8 = alloca %enum.Event
  %t238 = alloca %struct.TransResult
  %t239 = alloca %enum.State
  %t243 = alloca %enum.Action
  %t251 = alloca %struct.TransResult
  %t252 = alloca %enum.State
  %t256 = alloca %enum.Action
  %t263 = alloca %struct.TransResult
  %t266 = alloca %enum.Action
  %t275 = alloca %struct.TransResult
  %t278 = alloca %enum.Action
  %t285 = alloca %struct.TransResult
  %t288 = alloca %enum.Action
  %t295 = alloca %struct.TransResult
  %t296 = alloca %enum.State
  %t300 = alloca %enum.Action
  %t0 = load %enum.State, ptr %state
  store %enum.State %t0, ptr %ssa.t1
  %t2 = load i32, ptr %ssa.t1
  %t3 = sext i32 %t2 to i64
  %t4 = icmp eq i64 %t3, 0
  br i1 %t4, label %arm01, label %check12
arm01:
  %t6 = load %enum.Event, ptr %event
  store %enum.Event %t6, ptr %ssa.t2
  %t8 = load i32, ptr %ssa.t2
  %t9 = sext i32 %t8 to i64
  %t10 = icmp eq i64 %t9, 0
  br i1 %t10, label %arm04, label %check15
arm04:
  store i32 1, ptr %t13
  %t14 = getelementptr i8, ptr %t13, i64 4
  store i32 1, ptr %t14
  %t16 = load %enum.State, ptr %t13
  store %enum.State %t16, ptr %t12
  store i32 1, ptr %t18
  %t19 = getelementptr i8, ptr %t18, i64 4
  store i32 1, ptr %t19
  %t21 = load %enum.Action, ptr %t18
  %t22 = getelementptr i8, ptr %t12, i64 8
  store %enum.Action %t21, ptr %t22
  %t23 = load %struct.TransResult, ptr %t12
  ret %struct.TransResult %t23
check15:
  %t24 = icmp eq i64 %t9, 1
  br i1 %t24, label %arm16, label %check27
arm16:
  store i32 0, ptr %t27
  %t29 = load %enum.State, ptr %t27
  store %enum.State %t29, ptr %t26
  store i32 0, ptr %t31
  %t33 = load %enum.Action, ptr %t31
  %t34 = getelementptr i8, ptr %t26, i64 8
  store %enum.Action %t33, ptr %t34
  %t35 = load %struct.TransResult, ptr %t26
  ret %struct.TransResult %t35
check27:
  %t36 = icmp eq i64 %t9, 2
  br i1 %t36, label %arm28, label %check39
arm28:
  store i32 0, ptr %t41
  %t43 = load %enum.State, ptr %t41
  store %enum.State %t43, ptr %t40
  store i32 0, ptr %t45
  %t47 = load %enum.Action, ptr %t45
  %t48 = getelementptr i8, ptr %t40, i64 8
  store %enum.Action %t47, ptr %t48
  %t49 = load %struct.TransResult, ptr %t40
  ret %struct.TransResult %t49
check39:
  %t50 = icmp eq i64 %t9, 3
  br i1 %t50, label %arm310, label %check411
arm310:
  store i32 4, ptr %t53
  %t55 = load %enum.State, ptr %t53
  store %enum.State %t55, ptr %t52
  store i32 0, ptr %t57
  %t59 = load %enum.Action, ptr %t57
  %t60 = getelementptr i8, ptr %t52, i64 8
  store %enum.Action %t59, ptr %t60
  %t61 = load %struct.TransResult, ptr %t52
  ret %struct.TransResult %t61
check411:
  %t62 = icmp eq i64 %t9, 4
  br i1 %t62, label %arm412, label %check513
arm412:
  store i32 0, ptr %t65
  %t67 = load %enum.State, ptr %t65
  store %enum.State %t67, ptr %t64
  store i32 0, ptr %t69
  %t71 = load %enum.Action, ptr %t69
  %t72 = getelementptr i8, ptr %t64, i64 8
  store %enum.Action %t71, ptr %t72
  %t73 = load %struct.TransResult, ptr %t64
  ret %struct.TransResult %t73
check513:
  unreachable
check12:
  %t74 = icmp eq i64 %t3, 1
  br i1 %t74, label %arm114, label %check215
arm114:
  store %enum.State %t0, ptr %ssa.t3
  %t75 = getelementptr i8, ptr %ssa.t3, i64 4
  %t77 = load i32, ptr %t75
  %t78 = load %enum.Event, ptr %event
  store %enum.Event %t78, ptr %ssa.t4
  %t80 = load i32, ptr %ssa.t4
  %t81 = sext i32 %t80 to i64
  %t82 = icmp eq i64 %t81, 1
  br i1 %t82, label %arm017, label %check118
arm017:
  store i32 2, ptr %t85
  %t86 = getelementptr i8, ptr %t85, i64 4
  store i32 0, ptr %t86
  %t88 = load %enum.State, ptr %t85
  store %enum.State %t88, ptr %t84
  store i32 1, ptr %t90
  %t91 = getelementptr i8, ptr %t90, i64 4
  store i32 1, ptr %t91
  %t93 = load %enum.Action, ptr %t90
  %t94 = getelementptr i8, ptr %t84, i64 8
  store %enum.Action %t93, ptr %t94
  %t95 = load %struct.TransResult, ptr %t84
  ret %struct.TransResult %t95
check118:
  %t96 = icmp eq i64 %t81, 4
  br i1 %t96, label %arm119, label %check220
arm119:
  %t98 = icmp slt i32 %t77, 3
  br i1 %t98, label %then21, label %merge23
then21:
  store i32 1, ptr %t100
  %t101 = getelementptr i8, ptr %t100, i64 4
  %t102 = add i32 %t77, 1
  store i32 %t102, ptr %t101
  %t104 = load %enum.State, ptr %t100
  store %enum.State %t104, ptr %t99
  store i32 1, ptr %t106
  %t107 = getelementptr i8, ptr %t106, i64 4
  store i32 1, ptr %t107
  %t109 = load %enum.Action, ptr %t106
  %t110 = getelementptr i8, ptr %t99, i64 8
  store %enum.Action %t109, ptr %t110
  %t111 = load %struct.TransResult, ptr %t99
  ret %struct.TransResult %t111
merge23:
  store i32 4, ptr %t113
  %t115 = load %enum.State, ptr %t113
  store %enum.State %t115, ptr %t112
  store i32 2, ptr %t117
  %t119 = load %enum.Action, ptr %t117
  %t120 = getelementptr i8, ptr %t112, i64 8
  store %enum.Action %t119, ptr %t120
  %t121 = load %struct.TransResult, ptr %t112
  ret %struct.TransResult %t121
check220:
  %t122 = icmp eq i64 %t81, 3
  br i1 %t122, label %arm224, label %check325
arm224:
  store i32 4, ptr %t125
  %t127 = load %enum.State, ptr %t125
  store %enum.State %t127, ptr %t124
  store i32 2, ptr %t129
  %t131 = load %enum.Action, ptr %t129
  %t132 = getelementptr i8, ptr %t124, i64 8
  store %enum.Action %t131, ptr %t132
  %t133 = load %struct.TransResult, ptr %t124
  ret %struct.TransResult %t133
check325:
  %t134 = icmp eq i64 %t81, 0
  br i1 %t134, label %arm326, label %check427
arm326:
  %t137 = load %enum.State, ptr %state
  store %enum.State %t137, ptr %t136
  store i32 0, ptr %t139
  %t141 = load %enum.Action, ptr %t139
  %t142 = getelementptr i8, ptr %t136, i64 8
  store %enum.Action %t141, ptr %t142
  %t143 = load %struct.TransResult, ptr %t136
  ret %struct.TransResult %t143
check427:
  %t144 = icmp eq i64 %t81, 2
  br i1 %t144, label %arm428, label %check529
arm428:
  %t149 = load %enum.State, ptr %state
  store %enum.State %t149, ptr %t148
  store i32 0, ptr %t151
  %t153 = load %enum.Action, ptr %t151
  %t154 = getelementptr i8, ptr %t148, i64 8
  store %enum.Action %t153, ptr %t154
  %t155 = load %struct.TransResult, ptr %t148
  ret %struct.TransResult %t155
check529:
  unreachable
check215:
  %t156 = icmp eq i64 %t3, 2
  br i1 %t156, label %arm230, label %check331
arm230:
  store %enum.State %t0, ptr %ssa.t5
  %t157 = getelementptr i8, ptr %ssa.t5, i64 4
  %t159 = load i32, ptr %t157
  %t160 = load %enum.Event, ptr %event
  store %enum.Event %t160, ptr %ssa.t6
  %t162 = load i32, ptr %ssa.t6
  %t163 = sext i32 %t162 to i64
  %t164 = icmp eq i64 %t163, 2
  br i1 %t164, label %arm033, label %check134
arm033:
  store %enum.Event %t160, ptr %ssa.t7
  %t165 = getelementptr i8, ptr %ssa.t7, i64 4
  %t167 = load i32, ptr %t165
  store i32 2, ptr %t169
  %t170 = getelementptr i8, ptr %t169, i64 4
  %t171 = add i32 %t159, %t167
  store i32 %t171, ptr %t170
  %t173 = load %enum.State, ptr %t169
  store %enum.State %t173, ptr %t168
  store i32 1, ptr %t175
  %t176 = getelementptr i8, ptr %t175, i64 4
  store i32 %t167, ptr %t176
  %t178 = load %enum.Action, ptr %t175
  %t179 = getelementptr i8, ptr %t168, i64 8
  store %enum.Action %t178, ptr %t179
  %t180 = load %struct.TransResult, ptr %t168
  ret %struct.TransResult %t180
check134:
  %t181 = icmp eq i64 %t163, 3
  br i1 %t181, label %arm135, label %check236
arm135:
  store i32 3, ptr %t184
  %t185 = getelementptr i8, ptr %t184, i64 4
  store i32 %t159, ptr %t185
  %t187 = load %enum.State, ptr %t184
  store %enum.State %t187, ptr %t183
  store i32 1, ptr %t189
  %t190 = getelementptr i8, ptr %t189, i64 4
  store i32 1, ptr %t190
  %t192 = load %enum.Action, ptr %t189
  %t193 = getelementptr i8, ptr %t183, i64 8
  store %enum.Action %t192, ptr %t193
  %t194 = load %struct.TransResult, ptr %t183
  ret %struct.TransResult %t194
check236:
  %t195 = icmp eq i64 %t163, 4
  br i1 %t195, label %arm237, label %check338
arm237:
  store i32 2, ptr %t198
  %t199 = getelementptr i8, ptr %t198, i64 4
  store i32 %t159, ptr %t199
  %t201 = load %enum.State, ptr %t198
  store %enum.State %t201, ptr %t197
  store i32 0, ptr %t203
  %t205 = load %enum.Action, ptr %t203
  %t206 = getelementptr i8, ptr %t197, i64 8
  store %enum.Action %t205, ptr %t206
  %t207 = load %struct.TransResult, ptr %t197
  ret %struct.TransResult %t207
check338:
  %t208 = icmp eq i64 %t163, 0
  br i1 %t208, label %arm339, label %check440
arm339:
  %t211 = load %enum.State, ptr %state
  store %enum.State %t211, ptr %t210
  store i32 0, ptr %t213
  %t215 = load %enum.Action, ptr %t213
  %t216 = getelementptr i8, ptr %t210, i64 8
  store %enum.Action %t215, ptr %t216
  %t217 = load %struct.TransResult, ptr %t210
  ret %struct.TransResult %t217
check440:
  %t218 = icmp eq i64 %t163, 1
  br i1 %t218, label %arm441, label %check542
arm441:
  %t221 = load %enum.State, ptr %state
  store %enum.State %t221, ptr %t220
  store i32 0, ptr %t223
  %t225 = load %enum.Action, ptr %t223
  %t226 = getelementptr i8, ptr %t220, i64 8
  store %enum.Action %t225, ptr %t226
  %t227 = load %struct.TransResult, ptr %t220
  ret %struct.TransResult %t227
check542:
  unreachable
check331:
  %t228 = icmp eq i64 %t3, 3
  br i1 %t228, label %arm343, label %check444
arm343:
  %t232 = load %enum.Event, ptr %event
  store %enum.Event %t232, ptr %ssa.t8
  %t234 = load i32, ptr %ssa.t8
  %t235 = sext i32 %t234 to i64
  %t236 = icmp eq i64 %t235, 1
  br i1 %t236, label %arm046, label %check147
arm046:
  store i32 4, ptr %t239
  %t241 = load %enum.State, ptr %t239
  store %enum.State %t241, ptr %t238
  store i32 1, ptr %t243
  %t244 = getelementptr i8, ptr %t243, i64 4
  store i32 1, ptr %t244
  %t246 = load %enum.Action, ptr %t243
  %t247 = getelementptr i8, ptr %t238, i64 8
  store %enum.Action %t246, ptr %t247
  %t248 = load %struct.TransResult, ptr %t238
  ret %struct.TransResult %t248
check147:
  %t249 = icmp eq i64 %t235, 4
  br i1 %t249, label %arm148, label %check249
arm148:
  store i32 4, ptr %t252
  %t254 = load %enum.State, ptr %t252
  store %enum.State %t254, ptr %t251
  store i32 2, ptr %t256
  %t258 = load %enum.Action, ptr %t256
  %t259 = getelementptr i8, ptr %t251, i64 8
  store %enum.Action %t258, ptr %t259
  %t260 = load %struct.TransResult, ptr %t251
  ret %struct.TransResult %t260
check249:
  %t261 = icmp eq i64 %t235, 0
  br i1 %t261, label %arm250, label %check351
arm250:
  %t264 = load %enum.State, ptr %state
  store %enum.State %t264, ptr %t263
  store i32 0, ptr %t266
  %t268 = load %enum.Action, ptr %t266
  %t269 = getelementptr i8, ptr %t263, i64 8
  store %enum.Action %t268, ptr %t269
  %t270 = load %struct.TransResult, ptr %t263
  ret %struct.TransResult %t270
check351:
  %t271 = icmp eq i64 %t235, 2
  br i1 %t271, label %arm352, label %check453
arm352:
  %t276 = load %enum.State, ptr %state
  store %enum.State %t276, ptr %t275
  store i32 0, ptr %t278
  %t280 = load %enum.Action, ptr %t278
  %t281 = getelementptr i8, ptr %t275, i64 8
  store %enum.Action %t280, ptr %t281
  %t282 = load %struct.TransResult, ptr %t275
  ret %struct.TransResult %t282
check453:
  %t283 = icmp eq i64 %t235, 3
  br i1 %t283, label %arm454, label %check555
arm454:
  %t286 = load %enum.State, ptr %state
  store %enum.State %t286, ptr %t285
  store i32 0, ptr %t288
  %t290 = load %enum.Action, ptr %t288
  %t291 = getelementptr i8, ptr %t285, i64 8
  store %enum.Action %t290, ptr %t291
  %t292 = load %struct.TransResult, ptr %t285
  ret %struct.TransResult %t292
check555:
  unreachable
check444:
  %t293 = icmp eq i64 %t3, 4
  br i1 %t293, label %arm456, label %check557
arm456:
  store i32 4, ptr %t296
  %t298 = load %enum.State, ptr %t296
  store %enum.State %t298, ptr %t295
  store i32 0, ptr %t300
  %t302 = load %enum.Action, ptr %t300
  %t303 = getelementptr i8, ptr %t295, i64 8
  store %enum.Action %t302, ptr %t303
  %t304 = load %struct.TransResult, ptr %t295
  ret %struct.TransResult %t304
check557:
  unreachable
}

define i32 @action_bytes(ptr %a) {
entry:
  %ssa.t9 = alloca %enum.Action
  %ssa.t10 = alloca %enum.Action
  %t0 = load %enum.Action, ptr %a
  store %enum.Action %t0, ptr %ssa.t9
  %t2 = load i32, ptr %ssa.t9
  %t3 = sext i32 %t2 to i64
  %t4 = icmp eq i64 %t3, 1
  br i1 %t4, label %arm01, label %check12
arm01:
  store %enum.Action %t0, ptr %ssa.t10
  %t5 = getelementptr i8, ptr %ssa.t10, i64 4
  %t7 = load i32, ptr %t5
  ret i32 %t7
check12:
  %t8 = icmp eq i64 %t3, 0
  br i1 %t8, label %arm13, label %check24
arm13:
  ret i32 0
check24:
  %t10 = icmp eq i64 %t3, 2
  br i1 %t10, label %arm25, label %check36
arm25:
  ret i32 0
check36:
  unreachable
}

define i1 @is_reset(ptr %a) {
entry:
  %ssa.t11 = alloca %enum.Action
  %t0 = load %enum.Action, ptr %a
  store %enum.Action %t0, ptr %ssa.t11
  %t2 = load i32, ptr %ssa.t11
  %t3 = sext i32 %t2 to i64
  %t4 = icmp eq i64 %t3, 2
  br i1 %t4, label %arm01, label %check12
arm01:
  ret i1 1
check12:
  %t6 = icmp eq i64 %t3, 0
  br i1 %t6, label %arm13, label %check24
arm13:
  ret i1 0
check24:
  %t8 = icmp eq i64 %t3, 1
  br i1 %t8, label %arm25, label %check36
arm25:
  ret i1 0
check36:
  unreachable
}

define %struct.RawCounter @counter_new() {
entry:
  %t0 = alloca %struct.RawCounter
  store i32 0, ptr %t0
  %t2 = load %struct.RawCounter, ptr %t0
  ret %struct.RawCounter %t2
}

define void @counter_increment(ptr %c, i32 %amount) {
entry:
  %t1 = load i32, ptr %c
  %t2 = add i32 %t1, %amount
  store i32 %t2, ptr %c
  ret void
}

define i32 @counter_get(ptr %c) {
entry:
  %t1 = load i32, ptr %c
  ret i32 %t1
}

define i64 @user_main() {
entry:
  %mutref.21 = alloca %struct.RawCounter
  %mutref.40 = alloca %struct.RawCounter
  %mutref.60 = alloca %struct.RawCounter
  %mutref.77 = alloca %struct.RawCounter
  %mutref.94 = alloca %struct.RawCounter
  %mutref.113 = alloca %struct.RawCounter
  %mutref.138 = alloca %struct.RawCounter
  %mutref.158 = alloca %struct.RawCounter
  %t0 = alloca %enum.State
  %borrow.4 = alloca %enum.State
  %t7 = alloca %enum.Event
  %borrow.10 = alloca %enum.State
  %borrow.11 = alloca %enum.Event
  %ssa.t12 = alloca %struct.TransResult
  %ssa.t13 = alloca %struct.TransResult
  %borrow.17 = alloca %enum.Action
  %borrow.23 = alloca %enum.State
  %t26 = alloca %enum.Event
  %borrow.29 = alloca %enum.State
  %borrow.30 = alloca %enum.Event
  %ssa.t14 = alloca %struct.TransResult
  %ssa.t15 = alloca %struct.TransResult
  %borrow.36 = alloca %enum.Action
  %borrow.42 = alloca %enum.State
  %t45 = alloca %enum.Event
  %borrow.49 = alloca %enum.State
  %borrow.50 = alloca %enum.Event
  %ssa.t16 = alloca %struct.TransResult
  %ssa.t17 = alloca %struct.TransResult
  %borrow.56 = alloca %enum.Action
  %t62 = alloca %enum.Event
  %borrow.66 = alloca %enum.State
  %borrow.67 = alloca %enum.Event
  %ssa.t18 = alloca %struct.TransResult
  %ssa.t19 = alloca %struct.TransResult
  %borrow.73 = alloca %enum.Action
  %t79 = alloca %enum.Event
  %borrow.83 = alloca %enum.State
  %borrow.84 = alloca %enum.Event
  %ssa.t20 = alloca %struct.TransResult
  %ssa.t21 = alloca %struct.TransResult
  %borrow.90 = alloca %enum.Action
  %borrow.96 = alloca %enum.State
  %t99 = alloca %enum.Event
  %borrow.102 = alloca %enum.State
  %borrow.103 = alloca %enum.Event
  %ssa.t22 = alloca %struct.TransResult
  %ssa.t23 = alloca %struct.TransResult
  %borrow.109 = alloca %enum.Action
  %borrow.115 = alloca %enum.State
  %t118 = alloca %enum.Event
  %borrow.121 = alloca %enum.State
  %borrow.122 = alloca %enum.Event
  %ssa.t24 = alloca %struct.TransResult
  %ssa.t25 = alloca %struct.TransResult
  %borrow.128 = alloca %enum.Action
  %ssa.t26 = alloca %struct.TransResult
  %borrow.134 = alloca %enum.Action
  %borrow.140 = alloca %enum.State
  %t143 = alloca %enum.Event
  %borrow.147 = alloca %enum.State
  %borrow.148 = alloca %enum.Event
  %ssa.t27 = alloca %struct.TransResult
  %borrow.154 = alloca %enum.Action
  %borrow.160 = alloca %struct.RawCounter
  %t166 = alloca %enum.State
  %t170 = alloca %enum.Event
  %borrow.173 = alloca %enum.State
  %borrow.174 = alloca %enum.Event
  %ssa.t28 = alloca %struct.TransResult
  %borrow.178 = alloca %enum.Action
  %ssa.t29 = alloca %struct.TransResult
  %borrow.184 = alloca %enum.State
  store i32 0, ptr %t0
  %t2 = load %enum.State, ptr %t0
  %t3 = call %struct.RawCounter @counter_new()
  store %enum.State %t2, ptr %borrow.4
  %t5 = call i32 @state_code(ptr %borrow.4)
  %t6 = icmp ne i32 %t5, 0
  br i1 %t6, label %then0, label %merge2
then0:
  ret i64 1
merge2:
  store i32 0, ptr %t7
  %t9 = load %enum.Event, ptr %t7
  store %enum.State %t2, ptr %borrow.10
  store %enum.Event %t9, ptr %borrow.11
  %t12 = call %struct.TransResult @transition(ptr %borrow.10, ptr %borrow.11)
  store %struct.TransResult %t12, ptr %ssa.t12
  %t14 = load %enum.State, ptr %ssa.t12
  store %struct.TransResult %t12, ptr %ssa.t13
  %t15 = getelementptr i8, ptr %ssa.t13, i64 8
  %t16 = load %enum.Action, ptr %t15
  store %enum.Action %t16, ptr %borrow.17
  %t18 = call i32 @action_bytes(ptr %borrow.17)
  store %struct.RawCounter %t3, ptr %mutref.21
  call void @counter_increment(ptr %mutref.21, i32 1)
  %wb.22 = load %struct.RawCounter, ptr %mutref.21
  store %enum.State %t14, ptr %borrow.23
  %t24 = call i32 @state_code(ptr %borrow.23)
  %t25 = icmp ne i32 %t24, 1
  br i1 %t25, label %then3, label %merge5
then3:
  ret i64 2
merge5:
  store i32 1, ptr %t26
  %t28 = load %enum.Event, ptr %t26
  store %enum.State %t14, ptr %borrow.29
  store %enum.Event %t28, ptr %borrow.30
  %t31 = call %struct.TransResult @transition(ptr %borrow.29, ptr %borrow.30)
  store %struct.TransResult %t31, ptr %ssa.t14
  %t33 = load %enum.State, ptr %ssa.t14
  store %struct.TransResult %t31, ptr %ssa.t15
  %t34 = getelementptr i8, ptr %ssa.t15, i64 8
  %t35 = load %enum.Action, ptr %t34
  store %enum.Action %t35, ptr %borrow.36
  %t37 = call i32 @action_bytes(ptr %borrow.36)
  %t38 = add i32 %t18, %t37
  store %struct.RawCounter %wb.22, ptr %mutref.40
  call void @counter_increment(ptr %mutref.40, i32 1)
  %wb.41 = load %struct.RawCounter, ptr %mutref.40
  store %enum.State %t33, ptr %borrow.42
  %t43 = call i32 @state_code(ptr %borrow.42)
  %t44 = icmp ne i32 %t43, 2
  br i1 %t44, label %then6, label %merge8
then6:
  ret i64 3
merge8:
  store i32 2, ptr %t45
  %t46 = getelementptr i8, ptr %t45, i64 4
  store i32 10, ptr %t46
  %t48 = load %enum.Event, ptr %t45
  store %enum.State %t33, ptr %borrow.49
  store %enum.Event %t48, ptr %borrow.50
  %t51 = call %struct.TransResult @transition(ptr %borrow.49, ptr %borrow.50)
  store %struct.TransResult %t51, ptr %ssa.t16
  %t53 = load %enum.State, ptr %ssa.t16
  store %struct.TransResult %t51, ptr %ssa.t17
  %t54 = getelementptr i8, ptr %ssa.t17, i64 8
  %t55 = load %enum.Action, ptr %t54
  store %enum.Action %t55, ptr %borrow.56
  %t57 = call i32 @action_bytes(ptr %borrow.56)
  %t58 = add i32 %t38, %t57
  store %struct.RawCounter %wb.41, ptr %mutref.60
  call void @counter_increment(ptr %mutref.60, i32 1)
  %wb.61 = load %struct.RawCounter, ptr %mutref.60
  store i32 2, ptr %t62
  %t63 = getelementptr i8, ptr %t62, i64 4
  store i32 15, ptr %t63
  %t65 = load %enum.Event, ptr %t62
  store %enum.State %t53, ptr %borrow.66
  store %enum.Event %t65, ptr %borrow.67
  %t68 = call %struct.TransResult @transition(ptr %borrow.66, ptr %borrow.67)
  store %struct.TransResult %t68, ptr %ssa.t18
  %t70 = load %enum.State, ptr %ssa.t18
  store %struct.TransResult %t68, ptr %ssa.t19
  %t71 = getelementptr i8, ptr %ssa.t19, i64 8
  %t72 = load %enum.Action, ptr %t71
  store %enum.Action %t72, ptr %borrow.73
  %t74 = call i32 @action_bytes(ptr %borrow.73)
  %t75 = add i32 %t58, %t74
  store %struct.RawCounter %wb.61, ptr %mutref.77
  call void @counter_increment(ptr %mutref.77, i32 1)
  %wb.78 = load %struct.RawCounter, ptr %mutref.77
  store i32 2, ptr %t79
  %t80 = getelementptr i8, ptr %t79, i64 4
  store i32 12, ptr %t80
  %t82 = load %enum.Event, ptr %t79
  store %enum.State %t70, ptr %borrow.83
  store %enum.Event %t82, ptr %borrow.84
  %t85 = call %struct.TransResult @transition(ptr %borrow.83, ptr %borrow.84)
  store %struct.TransResult %t85, ptr %ssa.t20
  %t87 = load %enum.State, ptr %ssa.t20
  store %struct.TransResult %t85, ptr %ssa.t21
  %t88 = getelementptr i8, ptr %ssa.t21, i64 8
  %t89 = load %enum.Action, ptr %t88
  store %enum.Action %t89, ptr %borrow.90
  %t91 = call i32 @action_bytes(ptr %borrow.90)
  %t92 = add i32 %t75, %t91
  store %struct.RawCounter %wb.78, ptr %mutref.94
  call void @counter_increment(ptr %mutref.94, i32 1)
  %wb.95 = load %struct.RawCounter, ptr %mutref.94
  store %enum.State %t87, ptr %borrow.96
  %t97 = call i32 @state_code(ptr %borrow.96)
  %t98 = icmp ne i32 %t97, 2
  br i1 %t98, label %then9, label %merge11
then9:
  ret i64 4
merge11:
  store i32 3, ptr %t99
  %t101 = load %enum.Event, ptr %t99
  store %enum.State %t87, ptr %borrow.102
  store %enum.Event %t101, ptr %borrow.103
  %t104 = call %struct.TransResult @transition(ptr %borrow.102, ptr %borrow.103)
  store %struct.TransResult %t104, ptr %ssa.t22
  %t106 = load %enum.State, ptr %ssa.t22
  store %struct.TransResult %t104, ptr %ssa.t23
  %t107 = getelementptr i8, ptr %ssa.t23, i64 8
  %t108 = load %enum.Action, ptr %t107
  store %enum.Action %t108, ptr %borrow.109
  %t110 = call i32 @action_bytes(ptr %borrow.109)
  %t111 = add i32 %t92, %t110
  store %struct.RawCounter %wb.95, ptr %mutref.113
  call void @counter_increment(ptr %mutref.113, i32 1)
  %wb.114 = load %struct.RawCounter, ptr %mutref.113
  store %enum.State %t106, ptr %borrow.115
  %t116 = call i32 @state_code(ptr %borrow.115)
  %t117 = icmp ne i32 %t116, 3
  br i1 %t117, label %then12, label %merge14
then12:
  ret i64 5
merge14:
  store i32 1, ptr %t118
  %t120 = load %enum.Event, ptr %t118
  store %enum.State %t106, ptr %borrow.121
  store %enum.Event %t120, ptr %borrow.122
  %t123 = call %struct.TransResult @transition(ptr %borrow.121, ptr %borrow.122)
  store %struct.TransResult %t123, ptr %ssa.t24
  %t125 = load %enum.State, ptr %ssa.t24
  store %struct.TransResult %t123, ptr %ssa.t25
  %t126 = getelementptr i8, ptr %ssa.t25, i64 8
  %t127 = load %enum.Action, ptr %t126
  store %enum.Action %t127, ptr %borrow.128
  %t129 = call i32 @action_bytes(ptr %borrow.128)
  %t130 = add i32 %t111, %t129
  store %struct.TransResult %t123, ptr %ssa.t26
  %t132 = getelementptr i8, ptr %ssa.t26, i64 8
  %t133 = load %enum.Action, ptr %t132
  store %enum.Action %t133, ptr %borrow.134
  %t135 = call i1 @is_reset(ptr %borrow.134)
  br i1 %t135, label %then15, label %else16
then15:
  br label %merge17
else16:
  br label %merge17
merge17:
  %if.phi.137 = phi i32 [1, %then15], [0, %else16]
  store %struct.RawCounter %wb.114, ptr %mutref.138
  call void @counter_increment(ptr %mutref.138, i32 1)
  %wb.139 = load %struct.RawCounter, ptr %mutref.138
  store %enum.State %t125, ptr %borrow.140
  %t141 = call i32 @state_code(ptr %borrow.140)
  %t142 = icmp ne i32 %t141, 4
  br i1 %t142, label %then18, label %merge20
then18:
  ret i64 6
merge20:
  store i32 2, ptr %t143
  %t144 = getelementptr i8, ptr %t143, i64 4
  store i32 999, ptr %t144
  %t146 = load %enum.Event, ptr %t143
  store %enum.State %t125, ptr %borrow.147
  store %enum.Event %t146, ptr %borrow.148
  %t149 = call %struct.TransResult @transition(ptr %borrow.147, ptr %borrow.148)
  store %struct.TransResult %t149, ptr %ssa.t27
  %t152 = getelementptr i8, ptr %ssa.t27, i64 8
  %t153 = load %enum.Action, ptr %t152
  store %enum.Action %t153, ptr %borrow.154
  %t155 = call i32 @action_bytes(ptr %borrow.154)
  %t156 = add i32 %t130, %t155
  store %struct.RawCounter %wb.139, ptr %mutref.158
  call void @counter_increment(ptr %mutref.158, i32 1)
  %wb.159 = load %struct.RawCounter, ptr %mutref.158
  store %struct.RawCounter %wb.159, ptr %borrow.160
  %t161 = call i32 @counter_get(ptr %borrow.160)
  %t162 = icmp ne i32 %t161, 8
  br i1 %t162, label %then21, label %merge26
then21:
  ret i64 7
merge26:
  %t164 = icmp ne i32 %if.phi.137, 0
  br i1 %t164, label %then27, label %merge29
then27:
  ret i64 9
merge29:
  %t165 = icmp ne i32 %t156, 41
  br i1 %t165, label %then30, label %merge32
then30:
  ret i64 10
merge32:
  store i32 1, ptr %t166
  %t167 = getelementptr i8, ptr %t166, i64 4
  store i32 3, ptr %t167
  %t169 = load %enum.State, ptr %t166
  store i32 4, ptr %t170
  %t172 = load %enum.Event, ptr %t170
  store %enum.State %t169, ptr %borrow.173
  store %enum.Event %t172, ptr %borrow.174
  %t175 = call %struct.TransResult @transition(ptr %borrow.173, ptr %borrow.174)
  store %struct.TransResult %t175, ptr %ssa.t28
  %t176 = getelementptr i8, ptr %ssa.t28, i64 8
  %t177 = load %enum.Action, ptr %t176
  store %enum.Action %t177, ptr %borrow.178
  %t179 = call i1 @is_reset(ptr %borrow.178)
  br i1 %t179, label %then33, label %else34
then33:
  %t180 = add i32 %if.phi.137, 1
  br label %merge35
else34:
  br label %merge35
merge35:
  %if.phi.181 = phi i32 [%t180, %then33], [%if.phi.137, %else34]
  store %struct.TransResult %t175, ptr %ssa.t29
  %t183 = load %enum.State, ptr %ssa.t29
  store %enum.State %t183, ptr %borrow.184
  %t185 = call i32 @state_code(ptr %borrow.184)
  %t186 = icmp ne i32 %t185, 4
  br i1 %t186, label %then36, label %merge38
then36:
  ret i64 11
merge38:
  %t187 = icmp ne i32 %if.phi.181, 1
  br i1 %t187, label %then39, label %merge41
then39:
  ret i64 12
merge41:
  %t188 = add i32 %t156, %if.phi.181
  %t189 = icmp ne i32 %t188, 42
  br i1 %t189, label %then42, label %merge44
then42:
  ret i64 13
merge44:
  %t190 = sext i32 %t188 to i64
  ret i64 %t190
}

define i32 @__concrete_get_argc() {
entry:
  %argc = load i32, ptr @__concrete_argc
  ret i32 %argc
}

define ptr @__concrete_get_argv(i32 %idx) {
entry:
  %argv = load ptr, ptr @__concrete_argv
  %idx64 = sext i32 %idx to i64
  %argp = getelementptr ptr, ptr %argv, i64 %idx64
  %arg = load ptr, ptr %argp
  ret ptr %arg
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  store i32 %argc, ptr @__concrete_argc
  store ptr %argv, ptr @__concrete_argv
  %result = call i64 @user_main()
  %fmt = getelementptr [6 x i8], ptr @fmt.main, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %fmt, i64 %result)
  ret i32 0
}

define ptr @__concrete_check_oom(ptr %p) {
entry:
  %is_null = icmp eq ptr %p, null
  br i1 %is_null, label %oom, label %ok
oom:
  call void @abort()
  unreachable
ok:
  ret ptr %p
}

define i64 @string_length(ptr %s) {
entry:
  %len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len = load i64, ptr %len_ptr
  ret i64 %len
}

define void @drop_string(ptr %s) {
entry:
  %data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data = load ptr, ptr %data_ptr
  call void @free(ptr %data)
  ret void
}

define %struct.String @string_concat(ptr %a, ptr %b) {
entry:
  %a_data_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 0
  %a_data = load ptr, ptr %a_data_ptr
  %a_len_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 1
  %a_len = load i64, ptr %a_len_ptr
  %b_data_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 0
  %b_data = load ptr, ptr %b_data_ptr
  %b_len_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 1
  %b_len = load i64, ptr %b_len_ptr
  %total_len = add i64 %a_len, %b_len
  %buf.raw = call ptr @malloc(i64 %total_len)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %buf, ptr %a_data, i64 %a_len, i1 false)
  %dst = getelementptr i8, ptr %buf, i64 %a_len
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %b_data, i64 %b_len, i1 false)
  call void @free(ptr %a_data)
  call void @free(ptr %b_data)
  %sc_alloca = alloca %struct.String
  %sc_data_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 0
  store ptr %buf, ptr %sc_data_ptr
  %sc_len_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 1
  store i64 %total_len, ptr %sc_len_ptr
  %sc_cap_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 2
  store i64 %total_len, ptr %sc_cap_ptr
  %sc_result = load %struct.String, ptr %sc_alloca
  ret %struct.String %sc_result
}

define %struct.String @string_slice(ptr %s, i64 %start, i64 %end_) {
entry:
  %len_ptr.ss = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len.ss = load i64, ptr %len_ptr.ss
  %s_clamped = call i64 @llvm.smax.i64(i64 %start, i64 0)
  %s_min = call i64 @llvm.smin.i64(i64 %s_clamped, i64 %len.ss)
  %e_clamped = call i64 @llvm.smax.i64(i64 %end_, i64 0)
  %e_min = call i64 @llvm.smin.i64(i64 %e_clamped, i64 %len.ss)
  %e_final = call i64 @llvm.smax.i64(i64 %e_min, i64 %s_min)
  %slice_len = sub i64 %e_final, %s_min
  %slice_buf.raw = call ptr @malloc(i64 %slice_len)
  %slice_buf = call ptr @__concrete_check_oom(ptr %slice_buf.raw)
  %data_ptr.ss = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data.ss = load ptr, ptr %data_ptr.ss
  %src = getelementptr i8, ptr %data.ss, i64 %s_min
  call void @llvm.memcpy.p0.p0.i64(ptr %slice_buf, ptr %src, i64 %slice_len, i1 false)
  %res.ss = alloca %struct.String
  %res_d.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 0
  store ptr %slice_buf, ptr %res_d.ss
  %res_l.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 1
  store i64 %slice_len, ptr %res_l.ss
  %res_c.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 2
  store i64 %slice_len, ptr %res_c.ss
  %result.ss = load %struct.String, ptr %res.ss
  ret %struct.String %result.ss
}

define %struct.String @string_substr(ptr %s, i64 %start, i64 %len) {
entry:
  %end_ = add i64 %start, %len
  %result.ssub = call %struct.String @string_slice(ptr %s, i64 %start, i64 %end_)
  ret %struct.String %result.ssub
}

define i64 @string_char_at(ptr %s, i64 %index) {
entry:
  %len_ptr.sca = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len.sca = load i64, ptr %len_ptr.sca
  %neg = icmp slt i64 %index, 0
  %oob = icmp sge i64 %index, %len.sca
  %bad = or i1 %neg, %oob
  br i1 %bad, label %ret_neg, label %ok_idx
ret_neg:
  ret i64 -1
ok_idx:
  %data_ptr.sca = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data.sca = load ptr, ptr %data_ptr.sca
  %char_ptr = getelementptr i8, ptr %data.sca, i64 %index
  %byte = load i8, ptr %char_ptr
  %char = zext i8 %byte to i64
  ret i64 %char
}

define i1 @string_contains(ptr %haystack, ptr %needle) {
entry:
  %h_data_ptr = getelementptr %struct.String, ptr %haystack, i32 0, i32 0
  %h_data = load ptr, ptr %h_data_ptr
  %h_len_ptr = getelementptr %struct.String, ptr %haystack, i32 0, i32 1
  %h_len = load i64, ptr %h_len_ptr
  %n_data_ptr = getelementptr %struct.String, ptr %needle, i32 0, i32 0
  %n_data = load ptr, ptr %n_data_ptr
  %n_len_ptr = getelementptr %struct.String, ptr %needle, i32 0, i32 1
  %n_len = load i64, ptr %n_len_ptr
  %n_empty = icmp eq i64 %n_len, 0
  br i1 %n_empty, label %found, label %check_len
check_len:
  %too_long = icmp ugt i64 %n_len, %h_len
  br i1 %too_long, label %not_found, label %loop_start
loop_start:
  %max_i = sub i64 %h_len, %n_len
  br label %loop
loop:
  %i = phi i64 [0, %loop_start], [%i_next, %loop_cont]
  %h_ptr = getelementptr i8, ptr %h_data, i64 %i
  %cmp = call i32 @memcmp(ptr %h_ptr, ptr %n_data, i64 %n_len)
  %match = icmp eq i32 %cmp, 0
  br i1 %match, label %found, label %loop_cont
loop_cont:
  %i_next = add i64 %i, 1
  %done = icmp ugt i64 %i_next, %max_i
  br i1 %done, label %not_found, label %loop
found:
  ret i1 1
not_found:
  ret i1 0
}

define i1 @string_eq(ptr %a, ptr %b) {
entry:
  %a_len_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 1
  %a_len = load i64, ptr %a_len_ptr
  %b_len_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 1
  %b_len = load i64, ptr %b_len_ptr
  %len_eq = icmp eq i64 %a_len, %b_len
  br i1 %len_eq, label %cmp_data, label %not_eq
cmp_data:
  %zero_len = icmp eq i64 %a_len, 0
  br i1 %zero_len, label %eq, label %do_cmp
do_cmp:
  %a_data_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 0
  %a_data = load ptr, ptr %a_data_ptr
  %b_data_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 0
  %b_data = load ptr, ptr %b_data_ptr
  %cmp_res = call i32 @memcmp(ptr %a_data, ptr %b_data, i64 %a_len)
  %eq_data = icmp eq i32 %cmp_res, 0
  br i1 %eq_data, label %eq, label %not_eq
eq:
  ret i1 1
not_eq:
  ret i1 0
}

define %struct.String @int_to_string(i64 %n) {
entry:
  %buf.raw = call ptr @malloc(i64 32)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  %fmt_its = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %buf, i64 32, ptr %fmt_its, i64 %n)
  %wext = sext i32 %written to i64
  %res.its = alloca %struct.String
  %res_d.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 0
  store ptr %buf, ptr %res_d.its
  %res_l.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 1
  store i64 %wext, ptr %res_l.its
  %res_c.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 2
  store i64 32, ptr %res_c.its
  %result.its = load %struct.String, ptr %res.its
  ret %struct.String %result.its
}

define %enum.Result @string_to_int(ptr %s) {
entry:
  %sti_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sti_data = load ptr, ptr %sti_data_ptr
  %sti_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sti_len = load i64, ptr %sti_len_ptr
  %sti_buf_sz = add i64 %sti_len, 1
  %sti_buf.raw = call ptr @malloc(i64 %sti_buf_sz)
  %sti_buf = call ptr @__concrete_check_oom(ptr %sti_buf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %sti_buf, ptr %sti_data, i64 %sti_len, i1 false)
  %sti_null = getelementptr i8, ptr %sti_buf, i64 %sti_len
  store i8 0, ptr %sti_null
  %endptr_alloca = alloca ptr
  %sti_val = call i64 @strtol(ptr %sti_buf, ptr %endptr_alloca, i32 10)
  %endptr = load ptr, ptr %endptr_alloca
  %end_expected = getelementptr i8, ptr %sti_buf, i64 %sti_len
  %valid = icmp eq ptr %endptr, %end_expected
  %empty_input = icmp eq i64 %sti_len, 0
  %not_empty = xor i1 %empty_input, 1
  %final_ok = and i1 %valid, %not_empty
  call void @free(ptr %sti_buf)
  %res.sti = alloca %enum.Result
  br i1 %final_ok, label %sti_ok, label %sti_err
sti_ok:
  store i32 0, ptr %res.sti
  %data_ptr.sti_ok = getelementptr i8, ptr %res.sti, i64 8
  store i64 %sti_val, ptr %data_ptr.sti_ok
  br label %sti_done
sti_err:
  store i32 1, ptr %res.sti
  %data_ptr.sti_err = getelementptr i8, ptr %res.sti, i64 8
  store i64 1, ptr %data_ptr.sti_err
  br label %sti_done
sti_done:
  %result.sti = load %enum.Result, ptr %res.sti
  ret %enum.Result %result.sti
}

define %struct.String @bool_to_string(i1 %b) {
entry:
  br i1 %b, label %bts_true, label %bts_false
bts_true:
  %tbuf.raw = call ptr @malloc(i64 4)
  %tbuf = call ptr @__concrete_check_oom(ptr %tbuf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %tbuf, ptr @.str_true, i64 4, i1 false)
  %tres = alloca %struct.String
  %td = getelementptr %struct.String, ptr %tres, i32 0, i32 0
  store ptr %tbuf, ptr %td
  %tl = getelementptr %struct.String, ptr %tres, i32 0, i32 1
  store i64 4, ptr %tl
  %tc = getelementptr %struct.String, ptr %tres, i32 0, i32 2
  store i64 4, ptr %tc
  %tresult = load %struct.String, ptr %tres
  ret %struct.String %tresult
bts_false:
  %fbuf.raw = call ptr @malloc(i64 5)
  %fbuf = call ptr @__concrete_check_oom(ptr %fbuf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %fbuf, ptr @.str_false, i64 5, i1 false)
  %fres = alloca %struct.String
  %fd = getelementptr %struct.String, ptr %fres, i32 0, i32 0
  store ptr %fbuf, ptr %fd
  %fl = getelementptr %struct.String, ptr %fres, i32 0, i32 1
  store i64 5, ptr %fl
  %fc = getelementptr %struct.String, ptr %fres, i32 0, i32 2
  store i64 5, ptr %fc
  %fresult = load %struct.String, ptr %fres
  ret %struct.String %fresult
}

define %struct.String @float_to_string(double %f) {
entry:
  %fbuf.fts.raw = call ptr @malloc(i64 64)
  %fbuf.fts = call ptr @__concrete_check_oom(ptr %fbuf.fts.raw)
  %fmt.fts = getelementptr [3 x i8], ptr @.fmt_f, i64 0, i64 0
  %written.fts = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %fbuf.fts, i64 64, ptr %fmt.fts, double %f)
  %wext.fts = sext i32 %written.fts to i64
  %res.fts = alloca %struct.String
  %res_d.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 0
  store ptr %fbuf.fts, ptr %res_d.fts
  %res_l.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 1
  store i64 %wext.fts, ptr %res_l.fts
  %res_c.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 2
  store i64 64, ptr %res_c.fts
  %result.fts = load %struct.String, ptr %res.fts
  ret %struct.String %result.fts
}

define %struct.String @string_trim(ptr %s) {
entry:
  %st_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %st_data = load ptr, ptr %st_data_ptr
  %st_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %st_len = load i64, ptr %st_len_ptr
  br label %trim_left
trim_left:
  %tl_i = phi i64 [0, %entry], [%tl_next, %tl_ws]
  %tl_done = icmp uge i64 %tl_i, %st_len
  br i1 %tl_done, label %trim_result, label %tl_check
tl_check:
  %tl_ptr = getelementptr i8, ptr %st_data, i64 %tl_i
  %tl_ch = load i8, ptr %tl_ptr
  %tl_is_sp = icmp eq i8 %tl_ch, 32
  %tl_is_tab = icmp eq i8 %tl_ch, 9
  %tl_is_nl = icmp eq i8 %tl_ch, 10
  %tl_is_cr = icmp eq i8 %tl_ch, 13
  %tl_w1 = or i1 %tl_is_sp, %tl_is_tab
  %tl_w2 = or i1 %tl_is_nl, %tl_is_cr
  %tl_is_ws = or i1 %tl_w1, %tl_w2
  br i1 %tl_is_ws, label %tl_ws, label %trim_right_init
tl_ws:
  %tl_next = add i64 %tl_i, 1
  br label %trim_left
trim_right_init:
  %tr_start = sub i64 %st_len, 1
  br label %trim_right
trim_right:
  %tr_i = phi i64 [%tr_start, %trim_right_init], [%tr_prev, %tr_ws]
  %tr_done = icmp ult i64 %tr_i, %tl_i
  br i1 %tr_done, label %trim_result, label %tr_check
tr_check:
  %tr_ptr = getelementptr i8, ptr %st_data, i64 %tr_i
  %tr_ch = load i8, ptr %tr_ptr
  %tr_is_sp = icmp eq i8 %tr_ch, 32
  %tr_is_tab = icmp eq i8 %tr_ch, 9
  %tr_is_nl = icmp eq i8 %tr_ch, 10
  %tr_is_cr = icmp eq i8 %tr_ch, 13
  %tr_w1 = or i1 %tr_is_sp, %tr_is_tab
  %tr_w2 = or i1 %tr_is_nl, %tr_is_cr
  %tr_is_ws = or i1 %tr_w1, %tr_w2
  br i1 %tr_is_ws, label %tr_ws, label %trim_result
tr_ws:
  %tr_prev = sub i64 %tr_i, 1
  br label %trim_right
trim_result:
  %tr_left = phi i64 [%tl_i, %trim_left], [%tl_i, %trim_right], [%tl_i, %tr_check]
  %tr_right_raw = phi i64 [0, %trim_left], [%tl_i, %trim_right], [%tr_i, %tr_check]
  %tr_right = add i64 %tr_right_raw, 1
  %tr_empty = icmp uge i64 %tr_left, %tr_right
  br i1 %tr_empty, label %trim_empty, label %trim_copy
trim_empty:
  %te_buf.raw = call ptr @malloc(i64 1)
  %te_buf = call ptr @__concrete_check_oom(ptr %te_buf.raw)
  %te_res = alloca %struct.String
  %te_d = getelementptr %struct.String, ptr %te_res, i32 0, i32 0
  store ptr %te_buf, ptr %te_d
  %te_l = getelementptr %struct.String, ptr %te_res, i32 0, i32 1
  store i64 0, ptr %te_l
  %te_c = getelementptr %struct.String, ptr %te_res, i32 0, i32 2
  store i64 1, ptr %te_c
  %te_result = load %struct.String, ptr %te_res
  ret %struct.String %te_result
trim_copy:
  %tc_len = sub i64 %tr_right, %tr_left
  %tc_buf.raw = call ptr @malloc(i64 %tc_len)
  %tc_buf = call ptr @__concrete_check_oom(ptr %tc_buf.raw)
  %tc_src = getelementptr i8, ptr %st_data, i64 %tr_left
  call void @llvm.memcpy.p0.p0.i64(ptr %tc_buf, ptr %tc_src, i64 %tc_len, i1 false)
  %tc_res = alloca %struct.String
  %tc_d = getelementptr %struct.String, ptr %tc_res, i32 0, i32 0
  store ptr %tc_buf, ptr %tc_d
  %tc_l = getelementptr %struct.String, ptr %tc_res, i32 0, i32 1
  store i64 %tc_len, ptr %tc_l
  %tc_c = getelementptr %struct.String, ptr %tc_res, i32 0, i32 2
  store i64 %tc_len, ptr %tc_c
  %tc_result = load %struct.String, ptr %tc_res
  ret %struct.String %tc_result
}

define void @print_string(ptr %s) {
entry:
  %ps_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %ps_data = load ptr, ptr %ps_data_ptr
  %ps_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %ps_len = load i64, ptr %ps_len_ptr
  %ps_fmt = getelementptr [5 x i8], ptr @.fmt_str, i64 0, i64 0
  %ps_len32 = trunc i64 %ps_len to i32
  %ps_written = call i32 (ptr, ...) @printf(ptr %ps_fmt, i32 %ps_len32, ptr %ps_data)
  ret void
}

define void @print_int(i64 %n) {
entry:
  %pi_fmt = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %pi_written = call i32 (ptr, ...) @printf(ptr %pi_fmt, i64 %n)
  ret void
}

define void @print_char(i64 %c) {
entry:
  %pc_int = trunc i64 %c to i32
  %pc_wr = call i32 @putchar(i32 %pc_int)
  ret void
}

define void @print_bool(i1 %b) {
entry:
  %is_true = icmp eq i1 %b, 1
  br i1 %is_true, label %print_true, label %print_false
print_true:
  %true_ptr = getelementptr [5 x i8], ptr @.str_true, i64 0, i64 0
  %tw = call i32 (ptr, ...) @printf(ptr %true_ptr)
  ret void
print_false:
  %false_ptr = getelementptr [6 x i8], ptr @.str_false, i64 0, i64 0
  %fw = call i32 (ptr, ...) @printf(ptr %false_ptr)
  ret void
}

define void @string_push_char(ptr %s, i64 %c) {
entry:
  %spc_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %spc_len = load i64, ptr %spc_len_ptr
  %spc_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %spc_cap = load i64, ptr %spc_cap_ptr
  %spc_full = icmp eq i64 %spc_len, %spc_cap
  br i1 %spc_full, label %spc_grow, label %spc_store
spc_grow:
  %spc_newcap = mul i64 %spc_cap, 2
  %spc_nc_clamped = call i64 @llvm.smax.i64(i64 %spc_newcap, i64 8)
  %spc_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %spc_data = load ptr, ptr %spc_data_ptr
  %spc_newbuf.raw = call ptr @realloc(ptr %spc_data, i64 %spc_nc_clamped)
  %spc_newbuf = call ptr @__concrete_check_oom(ptr %spc_newbuf.raw)
  store ptr %spc_newbuf, ptr %spc_data_ptr
  store i64 %spc_nc_clamped, ptr %spc_cap_ptr
  br label %spc_store
spc_store:
  %spc_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %spc_data2 = load ptr, ptr %spc_dp2
  %spc_slot = getelementptr i8, ptr %spc_data2, i64 %spc_len
  %spc_byte = trunc i64 %c to i8
  store i8 %spc_byte, ptr %spc_slot
  %spc_newlen = add i64 %spc_len, 1
  store i64 %spc_newlen, ptr %spc_len_ptr
  ret void
}

define void @string_append(ptr %s, ptr %other) {
entry:
  %sa_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sa_len = load i64, ptr %sa_len_ptr
  %sa_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sa_cap = load i64, ptr %sa_cap_ptr
  %sa_olen_ptr = getelementptr %struct.String, ptr %other, i32 0, i32 1
  %sa_olen = load i64, ptr %sa_olen_ptr
  %sa_needed = add i64 %sa_len, %sa_olen
  %sa_need_grow = icmp ugt i64 %sa_needed, %sa_cap
  br i1 %sa_need_grow, label %sa_grow, label %sa_copy
sa_grow:
  %sa_dblcap = mul i64 %sa_cap, 2
  %sa_newcap = call i64 @llvm.smax.i64(i64 %sa_dblcap, i64 %sa_needed)
  %sa_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sa_data = load ptr, ptr %sa_data_ptr
  %sa_newbuf.raw = call ptr @realloc(ptr %sa_data, i64 %sa_newcap)
  %sa_newbuf = call ptr @__concrete_check_oom(ptr %sa_newbuf.raw)
  store ptr %sa_newbuf, ptr %sa_data_ptr
  store i64 %sa_newcap, ptr %sa_cap_ptr
  br label %sa_copy
sa_copy:
  %sa_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sa_data2 = load ptr, ptr %sa_dp2
  %sa_dst = getelementptr i8, ptr %sa_data2, i64 %sa_len
  %sa_odata_ptr = getelementptr %struct.String, ptr %other, i32 0, i32 0
  %sa_odata = load ptr, ptr %sa_odata_ptr
  call void @llvm.memcpy.p0.p0.i64(ptr %sa_dst, ptr %sa_odata, i64 %sa_olen, i1 false)
  store i64 %sa_needed, ptr %sa_len_ptr
  ret void
}

define void @string_append_int(ptr %s, i64 %n) {
entry:
  %sai_buf = alloca [32 x i8]
  %sai_fmt = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %sai_written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %sai_buf, i64 32, ptr %sai_fmt, i64 %n)
  %sai_len = sext i32 %sai_written to i64
  %sai_slen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sai_slen = load i64, ptr %sai_slen_ptr
  %sai_scap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sai_scap = load i64, ptr %sai_scap_ptr
  %sai_needed = add i64 %sai_slen, %sai_len
  %sai_need_grow = icmp ugt i64 %sai_needed, %sai_scap
  br i1 %sai_need_grow, label %sai_grow, label %sai_copy
sai_grow:
  %sai_dblcap = mul i64 %sai_scap, 2
  %sai_newcap = call i64 @llvm.smax.i64(i64 %sai_dblcap, i64 %sai_needed)
  %sai_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sai_data = load ptr, ptr %sai_data_ptr
  %sai_newbuf.raw = call ptr @realloc(ptr %sai_data, i64 %sai_newcap)
  %sai_newbuf = call ptr @__concrete_check_oom(ptr %sai_newbuf.raw)
  store ptr %sai_newbuf, ptr %sai_data_ptr
  store i64 %sai_newcap, ptr %sai_scap_ptr
  br label %sai_copy
sai_copy:
  %sai_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sai_data2 = load ptr, ptr %sai_dp2
  %sai_dst = getelementptr i8, ptr %sai_data2, i64 %sai_slen
  call void @llvm.memcpy.p0.p0.i64(ptr %sai_dst, ptr %sai_buf, i64 %sai_len, i1 false)
  store i64 %sai_needed, ptr %sai_slen_ptr
  ret void
}

define void @string_append_bool(ptr %s, i1 %b) {
entry:
  br i1 %b, label %sab_true, label %sab_false
sab_true:
  %sab_tlen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sab_tlen = load i64, ptr %sab_tlen_ptr
  %sab_tcap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sab_tcap = load i64, ptr %sab_tcap_ptr
  %sab_tneeded = add i64 %sab_tlen, 4
  %sab_tneed_grow = icmp ugt i64 %sab_tneeded, %sab_tcap
  br i1 %sab_tneed_grow, label %sab_tgrow, label %sab_tcopy
sab_tgrow:
  %sab_tdblcap = mul i64 %sab_tcap, 2
  %sab_tnewcap = call i64 @llvm.smax.i64(i64 %sab_tdblcap, i64 %sab_tneeded)
  %sab_tdata_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_tdata = load ptr, ptr %sab_tdata_ptr
  %sab_tnewbuf.raw = call ptr @realloc(ptr %sab_tdata, i64 %sab_tnewcap)
  %sab_tnewbuf = call ptr @__concrete_check_oom(ptr %sab_tnewbuf.raw)
  store ptr %sab_tnewbuf, ptr %sab_tdata_ptr
  store i64 %sab_tnewcap, ptr %sab_tcap_ptr
  br label %sab_tcopy
sab_tcopy:
  %sab_tdp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_tdata2 = load ptr, ptr %sab_tdp2
  %sab_tdst = getelementptr i8, ptr %sab_tdata2, i64 %sab_tlen
  call void @llvm.memcpy.p0.p0.i64(ptr %sab_tdst, ptr @.str_true, i64 4, i1 false)
  store i64 %sab_tneeded, ptr %sab_tlen_ptr
  ret void
sab_false:
  %sab_flen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sab_flen = load i64, ptr %sab_flen_ptr
  %sab_fcap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sab_fcap = load i64, ptr %sab_fcap_ptr
  %sab_fneeded = add i64 %sab_flen, 5
  %sab_fneed_grow = icmp ugt i64 %sab_fneeded, %sab_fcap
  br i1 %sab_fneed_grow, label %sab_fgrow, label %sab_fcopy
sab_fgrow:
  %sab_fdblcap = mul i64 %sab_fcap, 2
  %sab_fnewcap = call i64 @llvm.smax.i64(i64 %sab_fdblcap, i64 %sab_fneeded)
  %sab_fdata_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_fdata = load ptr, ptr %sab_fdata_ptr
  %sab_fnewbuf.raw = call ptr @realloc(ptr %sab_fdata, i64 %sab_fnewcap)
  %sab_fnewbuf = call ptr @__concrete_check_oom(ptr %sab_fnewbuf.raw)
  store ptr %sab_fnewbuf, ptr %sab_fdata_ptr
  store i64 %sab_fnewcap, ptr %sab_fcap_ptr
  br label %sab_fcopy
sab_fcopy:
  %sab_fdp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_fdata2 = load ptr, ptr %sab_fdp2
  %sab_fdst = getelementptr i8, ptr %sab_fdata2, i64 %sab_flen
  call void @llvm.memcpy.p0.p0.i64(ptr %sab_fdst, ptr @.str_false, i64 5, i1 false)
  store i64 %sab_fneeded, ptr %sab_flen_ptr
  ret void
}

define void @string_reserve(ptr %s, i64 %extra) {
entry:
  %sr_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sr_cap = load i64, ptr %sr_cap_ptr
  %sr_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sr_len = load i64, ptr %sr_len_ptr
  %sr_needed = add i64 %sr_len, %extra
  %sr_need_grow = icmp ugt i64 %sr_needed, %sr_cap
  br i1 %sr_need_grow, label %sr_grow, label %sr_done
sr_grow:
  %sr_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sr_data = load ptr, ptr %sr_data_ptr
  %sr_newbuf.raw = call ptr @realloc(ptr %sr_data, i64 %sr_needed)
  %sr_newbuf = call ptr @__concrete_check_oom(ptr %sr_newbuf.raw)
  store ptr %sr_newbuf, ptr %sr_data_ptr
  store i64 %sr_needed, ptr %sr_cap_ptr
  br label %sr_done
sr_done:
  ret void
}

define i64 @clock_monotonic_ns() {
entry:
  %ts = alloca [2 x i64]
  %clk_ret = call i32 @clock_gettime(i32 6, ptr %ts)
  %sec_ptr = getelementptr i64, ptr %ts, i64 0
  %sec = load i64, ptr %sec_ptr
  %nsec_ptr = getelementptr i64, ptr %ts, i64 1
  %nsec = load i64, ptr %nsec_ptr
  %sec_ns = mul i64 %sec, 1000000000
  %total = add i64 %sec_ns, %nsec
  ret i64 %total
}

define i64 @vec_len(ptr %vec) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  ret i64 %len
}

define void @vec_free(ptr %vec) {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  call void @free(ptr %data)
  ret void
}

