; Generated by Concrete compiler (SSA path)
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx14.0.0"
%struct.String = type { ptr, i64, i64 }
%struct.Vec = type { ptr, i64, i64 }
%variant.Option.Some = type { i64 }
%variant.Option.None = type {}
%enum.Option = type { i32, [12 x i8] }
%variant.Result.Ok = type { i64 }
%variant.Result.Err = type { i64 }
%enum.Result = type { i32, [12 x i8] }
%variant.ExprNode.Lit = type { i32 }
%variant.ExprNode.Add = type { i32, i32 }
%variant.ExprNode.Mul = type { i32, i32 }
%variant.ExprNode.Neg = type { i32 }
%variant.ExprNode.Const = type { i32 }
%enum.ExprNode = type { i32, [8 x i8] }
%struct.EvalResult = type { i32, i32, i32 }
@__concrete_argc = private global i32 0
@__concrete_argv = private global ptr null
@fmt.main = private constant [6 x i8] c"%lld\0A\00"
@.fmt_ld = private constant [4 x i8] c"%ld\00"
@.fmt_str = private constant [5 x i8] c"%.*s\00"
@.str_true = private constant [5 x i8] c"true\00"
@.str_false = private constant [6 x i8] c"false\00"
@.fmt_f = private constant [3 x i8] c"%g\00"
declare ptr @malloc(i64)
declare void @free(ptr)
declare ptr @realloc(ptr, i64)
declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
declare i64 @write(i32, ptr, i64)
declare void @abort()
declare i32 @printf(ptr, ...)
declare i64 @strlen(ptr)
declare ptr @memset(ptr, i32, i64)
declare i32 @memcmp(ptr, ptr, i64)
declare i32 @snprintf(ptr, i64, ptr, ...)
declare i64 @strtol(ptr, ptr, i32)
declare i64 @llvm.smax.i64(i64, i64)
declare i64 @llvm.smin.i64(i64, i64)
declare i32 @clock_gettime(i32, ptr)
declare i32 @putchar(i32)
define i32 @encode_lit(ptr %arena, i32 %value) {
entry:
  %ssa.t0 = alloca i32
  %ssa.t1 = alloca i32
  %ssa.t2 = alloca i32
  %t0 = call i64 @vec_len(ptr %arena)
  %t1 = trunc i64 %t0 to i32
  %t2 = sdiv i32 %t1, 3
  store i32 0, ptr %ssa.t0
  call void @vec_push_4(ptr %arena, ptr %ssa.t0)
  store i32 %value, ptr %ssa.t1
  call void @vec_push_4(ptr %arena, ptr %ssa.t1)
  store i32 0, ptr %ssa.t2
  call void @vec_push_4(ptr %arena, ptr %ssa.t2)
  ret i32 %t2
}

define i32 @encode_add(ptr %arena, i32 %left, i32 %right) {
entry:
  %ssa.t3 = alloca i32
  %ssa.t4 = alloca i32
  %ssa.t5 = alloca i32
  %t0 = call i64 @vec_len(ptr %arena)
  %t1 = trunc i64 %t0 to i32
  %t2 = sdiv i32 %t1, 3
  store i32 1, ptr %ssa.t3
  call void @vec_push_4(ptr %arena, ptr %ssa.t3)
  store i32 %left, ptr %ssa.t4
  call void @vec_push_4(ptr %arena, ptr %ssa.t4)
  store i32 %right, ptr %ssa.t5
  call void @vec_push_4(ptr %arena, ptr %ssa.t5)
  ret i32 %t2
}

define i32 @encode_mul(ptr %arena, i32 %left, i32 %right) {
entry:
  %ssa.t6 = alloca i32
  %ssa.t7 = alloca i32
  %ssa.t8 = alloca i32
  %t0 = call i64 @vec_len(ptr %arena)
  %t1 = trunc i64 %t0 to i32
  %t2 = sdiv i32 %t1, 3
  store i32 2, ptr %ssa.t6
  call void @vec_push_4(ptr %arena, ptr %ssa.t6)
  store i32 %left, ptr %ssa.t7
  call void @vec_push_4(ptr %arena, ptr %ssa.t7)
  store i32 %right, ptr %ssa.t8
  call void @vec_push_4(ptr %arena, ptr %ssa.t8)
  ret i32 %t2
}

define i32 @encode_neg(ptr %arena, i32 %inner) {
entry:
  %ssa.t9 = alloca i32
  %ssa.t10 = alloca i32
  %ssa.t11 = alloca i32
  %t0 = call i64 @vec_len(ptr %arena)
  %t1 = trunc i64 %t0 to i32
  %t2 = sdiv i32 %t1, 3
  store i32 3, ptr %ssa.t9
  call void @vec_push_4(ptr %arena, ptr %ssa.t9)
  store i32 %inner, ptr %ssa.t10
  call void @vec_push_4(ptr %arena, ptr %ssa.t10)
  store i32 0, ptr %ssa.t11
  call void @vec_push_4(ptr %arena, ptr %ssa.t11)
  ret i32 %t2
}

define i32 @encode_const(ptr %arena, i32 %tag) {
entry:
  %ssa.t12 = alloca i32
  %ssa.t13 = alloca i32
  %ssa.t14 = alloca i32
  %t0 = call i64 @vec_len(ptr %arena)
  %t1 = trunc i64 %t0 to i32
  %t2 = sdiv i32 %t1, 3
  store i32 4, ptr %ssa.t12
  call void @vec_push_4(ptr %arena, ptr %ssa.t12)
  store i32 %tag, ptr %ssa.t13
  call void @vec_push_4(ptr %arena, ptr %ssa.t13)
  store i32 0, ptr %ssa.t14
  call void @vec_push_4(ptr %arena, ptr %ssa.t14)
  ret i32 %t2
}

define %enum.ExprNode @decode_node(ptr %arena, i32 %idx) {
entry:
  %t8 = alloca %enum.ExprNode
  %t13 = alloca %enum.ExprNode
  %t19 = alloca %enum.ExprNode
  %t25 = alloca %enum.ExprNode
  %t29 = alloca %enum.ExprNode
  %t0 = mul i32 %idx, 3
  %t1 = sext i32 %t0 to i64
  %ssa.t15 = call ptr @vec_get_4(ptr %arena, i64 %t1)
  %t2 = load i32, ptr %ssa.t15
  %t3 = add i64 %t1, 1
  %ssa.t16 = call ptr @vec_get_4(ptr %arena, i64 %t3)
  %t4 = load i32, ptr %ssa.t16
  %t5 = add i64 %t1, 2
  %ssa.t17 = call ptr @vec_get_4(ptr %arena, i64 %t5)
  %t6 = load i32, ptr %ssa.t17
  %t7 = icmp eq i32 %t2, 0
  br i1 %t7, label %then0, label %merge2
then0:
  store i32 0, ptr %t8
  %t9 = getelementptr i8, ptr %t8, i64 4
  store i32 %t4, ptr %t9
  %t11 = load %enum.ExprNode, ptr %t8
  ret %enum.ExprNode %t11
merge2:
  %t12 = icmp eq i32 %t2, 1
  br i1 %t12, label %then3, label %merge5
then3:
  store i32 1, ptr %t13
  %t14 = getelementptr i8, ptr %t13, i64 4
  store i32 %t4, ptr %t14
  %t16 = getelementptr i8, ptr %t14, i64 4
  store i32 %t6, ptr %t16
  %t17 = load %enum.ExprNode, ptr %t13
  ret %enum.ExprNode %t17
merge5:
  %t18 = icmp eq i32 %t2, 2
  br i1 %t18, label %then6, label %merge8
then6:
  store i32 2, ptr %t19
  %t20 = getelementptr i8, ptr %t19, i64 4
  store i32 %t4, ptr %t20
  %t22 = getelementptr i8, ptr %t20, i64 4
  store i32 %t6, ptr %t22
  %t23 = load %enum.ExprNode, ptr %t19
  ret %enum.ExprNode %t23
merge8:
  %t24 = icmp eq i32 %t2, 3
  br i1 %t24, label %then9, label %merge11
then9:
  store i32 3, ptr %t25
  %t26 = getelementptr i8, ptr %t25, i64 4
  store i32 %t4, ptr %t26
  %t28 = load %enum.ExprNode, ptr %t25
  ret %enum.ExprNode %t28
merge11:
  store i32 4, ptr %t29
  %t30 = getelementptr i8, ptr %t29, i64 4
  store i32 %t4, ptr %t30
  %t32 = load %enum.ExprNode, ptr %t29
  ret %enum.ExprNode %t32
}

define i32 @node_count(ptr %arena) {
entry:
  %t0 = call i64 @vec_len(ptr %arena)
  %t1 = trunc i64 %t0 to i32
  %t2 = sdiv i32 %t1, 3
  ret i32 %t2
}

define i32 @resolve_const(i32 %tag) {
entry:
  %t0 = icmp eq i32 %tag, 0
  br i1 %t0, label %then0, label %merge2
then0:
  ret i32 3
merge2:
  %t1 = icmp eq i32 %tag, 1
  br i1 %t1, label %then3, label %merge5
then3:
  ret i32 2
merge5:
  %t2 = icmp eq i32 %tag, 2
  br i1 %t2, label %then6, label %merge8
then6:
  ret i32 7
merge8:
  ret i32 0
}

define i32 @apply_binop(ptr %op, i32 %a, i32 %b) {
entry:
  %t0 = call i32 %op(i32 %a, i32 %b)
  ret i32 %t0
}

define %struct.Vec @eval_all(ptr %arena) {
entry:
  %agg.4 = alloca %struct.Vec
  %mutref.15 = alloca %struct.Vec
  %borrow.10 = alloca %enum.ExprNode
  %borrow.12 = alloca %struct.Vec
  %ssa.t18 = alloca i32
  %t0 = call i64 @vec_len(ptr %arena)
  %t1 = trunc i64 %t0 to i32
  %t2 = sdiv i32 %t1, 3
  %t3 = call %struct.Vec @vec_new_4()
  store %struct.Vec %t3, ptr %agg.4
  br label %while.hdr0
while.hdr0:
  %phi.7 = phi i32 [0, %entry], [%t17, %while.body1]
  %t8 = icmp slt i32 %phi.7, %t2
  br i1 %t8, label %while.body1, label %while.exit2
while.body1:
  %t9 = call %enum.ExprNode @decode_node(ptr %arena, i32 %phi.7)
  store %enum.ExprNode %t9, ptr %borrow.10
  %pload.11 = load %struct.Vec, ptr %agg.4
  store %struct.Vec %pload.11, ptr %borrow.12
  %t13 = call i32 @eval_node(ptr %borrow.10, ptr %borrow.12)
  %pload.14 = load %struct.Vec, ptr %agg.4
  store %struct.Vec %pload.14, ptr %mutref.15
  store i32 %t13, ptr %ssa.t18
  call void @vec_push_4(ptr %mutref.15, ptr %ssa.t18)
  %wb.16 = load %struct.Vec, ptr %mutref.15
  store %struct.Vec %wb.16, ptr %agg.4
  %t17 = add i32 %phi.7, 1
  br label %while.hdr0
while.exit2:
  %unpro.18 = load %struct.Vec, ptr %agg.4
  ret %struct.Vec %unpro.18
}

define i32 @eval_node(ptr %node, ptr %results) {
entry:
  %ssa.t19 = alloca %enum.ExprNode
  %ssa.t20 = alloca %enum.ExprNode
  %ssa.t21 = alloca %enum.ExprNode
  %ssa.t24 = alloca %enum.ExprNode
  %ssa.t27 = alloca %enum.ExprNode
  %ssa.t29 = alloca %enum.ExprNode
  %t0 = load %enum.ExprNode, ptr %node
  store %enum.ExprNode %t0, ptr %ssa.t19
  %t2 = load i32, ptr %ssa.t19
  %t3 = sext i32 %t2 to i64
  %t4 = icmp eq i64 %t3, 0
  br i1 %t4, label %arm01, label %check12
arm01:
  store %enum.ExprNode %t0, ptr %ssa.t20
  %t5 = getelementptr i8, ptr %ssa.t20, i64 4
  %t7 = load i32, ptr %t5
  ret i32 %t7
check12:
  %t8 = icmp eq i64 %t3, 1
  br i1 %t8, label %arm13, label %check24
arm13:
  store %enum.ExprNode %t0, ptr %ssa.t21
  %t9 = getelementptr i8, ptr %ssa.t21, i64 4
  %t11 = load i32, ptr %t9
  %t12 = getelementptr i8, ptr %t9, i64 4
  %t13 = load i32, ptr %t12
  %t14 = sext i32 %t11 to i64
  %ssa.t22 = call ptr @vec_get_4(ptr %results, i64 %t14)
  %t15 = load i32, ptr %ssa.t22
  %t16 = sext i32 %t13 to i64
  %ssa.t23 = call ptr @vec_get_4(ptr %results, i64 %t16)
  %t17 = load i32, ptr %ssa.t23
  %t18 = add i32 %t15, %t17
  ret i32 %t18
check24:
  %t19 = icmp eq i64 %t3, 2
  br i1 %t19, label %arm25, label %check36
arm25:
  store %enum.ExprNode %t0, ptr %ssa.t24
  %t20 = getelementptr i8, ptr %ssa.t24, i64 4
  %t22 = load i32, ptr %t20
  %t23 = getelementptr i8, ptr %t20, i64 4
  %t24 = load i32, ptr %t23
  %t25 = sext i32 %t22 to i64
  %ssa.t25 = call ptr @vec_get_4(ptr %results, i64 %t25)
  %t26 = load i32, ptr %ssa.t25
  %t27 = sext i32 %t24 to i64
  %ssa.t26 = call ptr @vec_get_4(ptr %results, i64 %t27)
  %t28 = load i32, ptr %ssa.t26
  %t29 = mul i32 %t26, %t28
  ret i32 %t29
check36:
  %t30 = icmp eq i64 %t3, 3
  br i1 %t30, label %arm37, label %check48
arm37:
  store %enum.ExprNode %t0, ptr %ssa.t27
  %t31 = getelementptr i8, ptr %ssa.t27, i64 4
  %t33 = load i32, ptr %t31
  %t34 = sext i32 %t33 to i64
  %ssa.t28 = call ptr @vec_get_4(ptr %results, i64 %t34)
  %t35 = load i32, ptr %ssa.t28
  %t36 = sub i32 0, %t35
  ret i32 %t36
check48:
  %t37 = icmp eq i64 %t3, 4
  br i1 %t37, label %arm49, label %check510
arm49:
  store %enum.ExprNode %t0, ptr %ssa.t29
  %t38 = getelementptr i8, ptr %ssa.t29, i64 4
  %t40 = load i32, ptr %t38
  %t41 = call i32 @resolve_const(i32 %t40)
  ret i32 %t41
check510:
  unreachable
}

define i32 @node_depth(ptr %arena, i32 %idx) {
entry:
  %ssa.t30 = alloca %enum.ExprNode
  %ssa.t31 = alloca %enum.ExprNode
  %ssa.t32 = alloca %enum.ExprNode
  %ssa.t33 = alloca %enum.ExprNode
  %t0 = call %enum.ExprNode @decode_node(ptr %arena, i32 %idx)
  store %enum.ExprNode %t0, ptr %ssa.t30
  %t2 = load i32, ptr %ssa.t30
  %t3 = sext i32 %t2 to i64
  %t4 = icmp eq i64 %t3, 0
  br i1 %t4, label %arm01, label %check12
arm01:
  ret i32 1
check12:
  %t8 = icmp eq i64 %t3, 1
  br i1 %t8, label %arm13, label %check24
arm13:
  store %enum.ExprNode %t0, ptr %ssa.t31
  %t9 = getelementptr i8, ptr %ssa.t31, i64 4
  %t11 = load i32, ptr %t9
  %t12 = getelementptr i8, ptr %t9, i64 4
  %t13 = load i32, ptr %t12
  %t14 = call i32 @node_depth(ptr %arena, i32 %t11)
  %t15 = call i32 @node_depth(ptr %arena, i32 %t13)
  %t16 = icmp sgt i32 %t14, %t15
  br i1 %t16, label %then5, label %merge7
then5:
  %t17 = add i32 %t14, 1
  ret i32 %t17
merge7:
  %t18 = add i32 %t15, 1
  ret i32 %t18
check24:
  %t19 = icmp eq i64 %t3, 2
  br i1 %t19, label %arm28, label %check39
arm28:
  store %enum.ExprNode %t0, ptr %ssa.t32
  %t20 = getelementptr i8, ptr %ssa.t32, i64 4
  %t22 = load i32, ptr %t20
  %t23 = getelementptr i8, ptr %t20, i64 4
  %t24 = load i32, ptr %t23
  %t25 = call i32 @node_depth(ptr %arena, i32 %t22)
  %t26 = call i32 @node_depth(ptr %arena, i32 %t24)
  %t27 = icmp sgt i32 %t25, %t26
  br i1 %t27, label %then10, label %merge12
then10:
  %t28 = add i32 %t25, 1
  ret i32 %t28
merge12:
  %t29 = add i32 %t26, 1
  ret i32 %t29
check39:
  %t30 = icmp eq i64 %t3, 3
  br i1 %t30, label %arm313, label %check414
arm313:
  store %enum.ExprNode %t0, ptr %ssa.t33
  %t31 = getelementptr i8, ptr %ssa.t33, i64 4
  %t33 = load i32, ptr %t31
  %t34 = call i32 @node_depth(ptr %arena, i32 %t33)
  %t35 = add i32 %t34, 1
  ret i32 %t35
check414:
  %t36 = icmp eq i64 %t3, 4
  br i1 %t36, label %arm415, label %check516
arm415:
  ret i32 1
check516:
  unreachable
}

define i32 @count_kind(ptr %arena, i32 %target_kind) {
entry:
  %t0 = call i64 @vec_len(ptr %arena)
  %t1 = trunc i64 %t0 to i32
  %t2 = sdiv i32 %t1, 3
  br label %while.hdr0
while.hdr0:
  %phi.6 = phi i32 [0, %entry], [%if.phi.14, %merge5]
  %phi.7 = phi i32 [0, %entry], [%t15, %merge5]
  %t8 = icmp slt i32 %phi.7, %t2
  br i1 %t8, label %while.body1, label %while.exit2
while.body1:
  %t9 = mul i32 %phi.7, 3
  %t10 = sext i32 %t9 to i64
  %ssa.t34 = call ptr @vec_get_4(ptr %arena, i64 %t10)
  %t11 = load i32, ptr %ssa.t34
  %t12 = icmp eq i32 %t11, %target_kind
  br i1 %t12, label %then3, label %else4
then3:
  %t13 = add i32 %phi.6, 1
  br label %merge5
else4:
  br label %merge5
merge5:
  %if.phi.14 = phi i32 [%t13, %then3], [%phi.6, %else4]
  %t15 = add i32 %phi.7, 1
  br label %while.hdr0
while.exit2:
  ret i32 %phi.6
}

define i32 @EvalResult_display_metric(ptr %self) {
entry:
  %t0 = getelementptr i8, ptr %self, i64 4
  %t1 = load i32, ptr %t0
  %t3 = load i32, ptr %self
  %t4 = add i32 %t1, %t3
  %t5 = getelementptr i8, ptr %self, i64 8
  %t6 = load i32, ptr %t5
  %t7 = add i32 %t4, %t6
  ret i32 %t7
}

define i32 @add_op(i32 %a, i32 %b) {
entry:
  %t0 = add i32 %a, %b
  ret i32 %t0
}

define i32 @mul_op(i32 %a, i32 %b) {
entry:
  %t0 = mul i32 %a, %b
  ret i32 %t0
}

define i64 @user_main() {
entry:
  %mutref.1 = alloca %struct.Vec
  %mutref.4 = alloca %struct.Vec
  %mutref.7 = alloca %struct.Vec
  %mutref.10 = alloca %struct.Vec
  %mutref.13 = alloca %struct.Vec
  %mutref.16 = alloca %struct.Vec
  %mutref.19 = alloca %struct.Vec
  %mutref.22 = alloca %struct.Vec
  %borrow.25 = alloca %struct.Vec
  %ssa.t35 = alloca %struct.Vec
  %borrow.28 = alloca %struct.Vec
  %borrow.30 = alloca %struct.Vec
  %ssa.t37 = alloca %struct.Vec
  %ssa.t38 = alloca %struct.Vec
  %borrow.33 = alloca %struct.Vec
  %borrow.35 = alloca %struct.Vec
  %borrow.37 = alloca %struct.Vec
  %borrow.39 = alloca %struct.Vec
  %borrow.41 = alloca %struct.Vec
  %ssa.t44 = alloca %struct.Vec
  %ssa.t45 = alloca %struct.Vec
  %ssa.t46 = alloca %struct.Vec
  %ssa.t47 = alloca %struct.Vec
  %ssa.t48 = alloca %struct.Vec
  %ssa.t49 = alloca %struct.Vec
  %ssa.t50 = alloca %struct.Vec
  %ssa.t51 = alloca %struct.Vec
  %ssa.t52 = alloca %struct.Vec
  %ssa.t53 = alloca %struct.Vec
  %ssa.t54 = alloca %struct.Vec
  %ssa.t55 = alloca %struct.Vec
  %ssa.t56 = alloca %struct.Vec
  %ssa.t57 = alloca %struct.Vec
  %borrow.53 = alloca %struct.Vec
  %ssa.t58 = alloca %struct.Vec
  %ssa.t59 = alloca %struct.Vec
  %borrow.56 = alloca %struct.Vec
  %borrow.58 = alloca %struct.Vec
  %borrow.60 = alloca %struct.Vec
  %borrow.62 = alloca %struct.Vec
  %borrow.64 = alloca %struct.Vec
  %ssa.t60 = alloca %struct.Vec
  %ssa.t61 = alloca %struct.Vec
  %ssa.t62 = alloca %struct.Vec
  %ssa.t63 = alloca %struct.Vec
  %ssa.t64 = alloca %struct.Vec
  %ssa.t65 = alloca %struct.Vec
  %ssa.t66 = alloca %struct.Vec
  %ssa.t67 = alloca %struct.Vec
  %ssa.t68 = alloca %struct.Vec
  %ssa.t69 = alloca %struct.Vec
  %t71 = alloca %struct.EvalResult
  %borrow.76 = alloca %struct.EvalResult
  %ssa.t70 = alloca %struct.Vec
  %ssa.t71 = alloca %struct.Vec
  %ssa.t72 = alloca %struct.Vec
  %ssa.t73 = alloca %struct.Vec
  %t0 = call %struct.Vec @vec_new_4()
  store %struct.Vec %t0, ptr %mutref.1
  %t2 = call i32 @encode_lit(ptr %mutref.1, i32 3)
  %wb.3 = load %struct.Vec, ptr %mutref.1
  store %struct.Vec %wb.3, ptr %mutref.4
  %t5 = call i32 @encode_const(ptr %mutref.4, i32 2)
  %wb.6 = load %struct.Vec, ptr %mutref.4
  store %struct.Vec %wb.6, ptr %mutref.7
  %t8 = call i32 @encode_add(ptr %mutref.7, i32 %t2, i32 %t5)
  %wb.9 = load %struct.Vec, ptr %mutref.7
  store %struct.Vec %wb.9, ptr %mutref.10
  %t11 = call i32 @encode_lit(ptr %mutref.10, i32 2)
  %wb.12 = load %struct.Vec, ptr %mutref.10
  store %struct.Vec %wb.12, ptr %mutref.13
  %t14 = call i32 @encode_neg(ptr %mutref.13, i32 %t11)
  %wb.15 = load %struct.Vec, ptr %mutref.13
  store %struct.Vec %wb.15, ptr %mutref.16
  %t17 = call i32 @encode_lit(ptr %mutref.16, i32 5)
  %wb.18 = load %struct.Vec, ptr %mutref.16
  store %struct.Vec %wb.18, ptr %mutref.19
  %t20 = call i32 @encode_add(ptr %mutref.19, i32 %t14, i32 %t17)
  %wb.21 = load %struct.Vec, ptr %mutref.19
  store %struct.Vec %wb.21, ptr %mutref.22
  %t23 = call i32 @encode_mul(ptr %mutref.22, i32 %t8, i32 %t20)
  %wb.24 = load %struct.Vec, ptr %mutref.22
  store %struct.Vec %wb.24, ptr %borrow.25
  %t26 = call i32 @node_count(ptr %borrow.25)
  %t27 = icmp ne i32 %t26, 8
  br i1 %t27, label %then0, label %merge2
then0:
  store %struct.Vec %wb.24, ptr %ssa.t35
  call void @vec_free(ptr %ssa.t35)
  ret i64 1
merge2:
  store %struct.Vec %wb.24, ptr %borrow.28
  %t29 = call %struct.Vec @eval_all(ptr %borrow.28)
  store %struct.Vec %t29, ptr %borrow.30
  %ssa.t36 = call ptr @vec_get_4(ptr %borrow.30, i64 7)
  %t31 = load i32, ptr %ssa.t36
  %t32 = icmp ne i32 %t31, 30
  br i1 %t32, label %then3, label %merge5
then3:
  store %struct.Vec %wb.24, ptr %ssa.t37
  call void @vec_free(ptr %ssa.t37)
  store %struct.Vec %t29, ptr %ssa.t38
  call void @vec_free(ptr %ssa.t38)
  ret i64 2
merge5:
  store %struct.Vec %t29, ptr %borrow.33
  %ssa.t39 = call ptr @vec_get_4(ptr %borrow.33, i64 0)
  %t34 = load i32, ptr %ssa.t39
  store %struct.Vec %t29, ptr %borrow.35
  %ssa.t40 = call ptr @vec_get_4(ptr %borrow.35, i64 1)
  %t36 = load i32, ptr %ssa.t40
  store %struct.Vec %t29, ptr %borrow.37
  %ssa.t41 = call ptr @vec_get_4(ptr %borrow.37, i64 2)
  %t38 = load i32, ptr %ssa.t41
  store %struct.Vec %t29, ptr %borrow.39
  %ssa.t42 = call ptr @vec_get_4(ptr %borrow.39, i64 4)
  %t40 = load i32, ptr %ssa.t42
  store %struct.Vec %t29, ptr %borrow.41
  %ssa.t43 = call ptr @vec_get_4(ptr %borrow.41, i64 6)
  %t42 = load i32, ptr %ssa.t43
  %t43 = icmp ne i32 %t34, 3
  br i1 %t43, label %then6, label %merge8
then6:
  store %struct.Vec %wb.24, ptr %ssa.t44
  call void @vec_free(ptr %ssa.t44)
  store %struct.Vec %t29, ptr %ssa.t45
  call void @vec_free(ptr %ssa.t45)
  ret i64 3
merge8:
  %t44 = icmp ne i32 %t36, 7
  br i1 %t44, label %then9, label %merge11
then9:
  store %struct.Vec %wb.24, ptr %ssa.t46
  call void @vec_free(ptr %ssa.t46)
  store %struct.Vec %t29, ptr %ssa.t47
  call void @vec_free(ptr %ssa.t47)
  ret i64 4
merge11:
  %t45 = icmp ne i32 %t38, 10
  br i1 %t45, label %then12, label %merge14
then12:
  store %struct.Vec %wb.24, ptr %ssa.t48
  call void @vec_free(ptr %ssa.t48)
  store %struct.Vec %t29, ptr %ssa.t49
  call void @vec_free(ptr %ssa.t49)
  ret i64 5
merge14:
  %t47 = icmp ne i32 %t40, -2
  br i1 %t47, label %then15, label %merge17
then15:
  store %struct.Vec %wb.24, ptr %ssa.t50
  call void @vec_free(ptr %ssa.t50)
  store %struct.Vec %t29, ptr %ssa.t51
  call void @vec_free(ptr %ssa.t51)
  ret i64 6
merge17:
  %t48 = icmp ne i32 %t42, 3
  br i1 %t48, label %then18, label %merge20
then18:
  store %struct.Vec %wb.24, ptr %ssa.t52
  call void @vec_free(ptr %ssa.t52)
  store %struct.Vec %t29, ptr %ssa.t53
  call void @vec_free(ptr %ssa.t53)
  ret i64 7
merge20:
  %t49 = call i32 @apply_binop(ptr @add_op, i32 15, i32 25)
  %t50 = call i32 @apply_binop(ptr @mul_op, i32 4, i32 3)
  %t51 = icmp ne i32 %t49, 40
  br i1 %t51, label %then21, label %merge23
then21:
  store %struct.Vec %wb.24, ptr %ssa.t54
  call void @vec_free(ptr %ssa.t54)
  store %struct.Vec %t29, ptr %ssa.t55
  call void @vec_free(ptr %ssa.t55)
  ret i64 8
merge23:
  %t52 = icmp ne i32 %t50, 12
  br i1 %t52, label %then24, label %merge26
then24:
  store %struct.Vec %wb.24, ptr %ssa.t56
  call void @vec_free(ptr %ssa.t56)
  store %struct.Vec %t29, ptr %ssa.t57
  call void @vec_free(ptr %ssa.t57)
  ret i64 9
merge26:
  store %struct.Vec %wb.24, ptr %borrow.53
  %t54 = call i32 @node_depth(ptr %borrow.53, i32 %t23)
  %t55 = icmp ne i32 %t54, 4
  br i1 %t55, label %then27, label %merge29
then27:
  store %struct.Vec %wb.24, ptr %ssa.t58
  call void @vec_free(ptr %ssa.t58)
  store %struct.Vec %t29, ptr %ssa.t59
  call void @vec_free(ptr %ssa.t59)
  ret i64 10
merge29:
  store %struct.Vec %wb.24, ptr %borrow.56
  %t57 = call i32 @count_kind(ptr %borrow.56, i32 0)
  store %struct.Vec %wb.24, ptr %borrow.58
  %t59 = call i32 @count_kind(ptr %borrow.58, i32 1)
  store %struct.Vec %wb.24, ptr %borrow.60
  %t61 = call i32 @count_kind(ptr %borrow.60, i32 2)
  store %struct.Vec %wb.24, ptr %borrow.62
  %t63 = call i32 @count_kind(ptr %borrow.62, i32 3)
  store %struct.Vec %wb.24, ptr %borrow.64
  %t65 = call i32 @count_kind(ptr %borrow.64, i32 4)
  %t66 = icmp ne i32 %t57, 3
  br i1 %t66, label %then30, label %merge32
then30:
  store %struct.Vec %wb.24, ptr %ssa.t60
  call void @vec_free(ptr %ssa.t60)
  store %struct.Vec %t29, ptr %ssa.t61
  call void @vec_free(ptr %ssa.t61)
  ret i64 11
merge32:
  %t67 = icmp ne i32 %t59, 2
  br i1 %t67, label %then33, label %merge35
then33:
  store %struct.Vec %wb.24, ptr %ssa.t62
  call void @vec_free(ptr %ssa.t62)
  store %struct.Vec %t29, ptr %ssa.t63
  call void @vec_free(ptr %ssa.t63)
  ret i64 12
merge35:
  %t68 = icmp ne i32 %t61, 1
  br i1 %t68, label %then36, label %merge38
then36:
  store %struct.Vec %wb.24, ptr %ssa.t64
  call void @vec_free(ptr %ssa.t64)
  store %struct.Vec %t29, ptr %ssa.t65
  call void @vec_free(ptr %ssa.t65)
  ret i64 13
merge38:
  %t69 = icmp ne i32 %t63, 1
  br i1 %t69, label %then39, label %merge41
then39:
  store %struct.Vec %wb.24, ptr %ssa.t66
  call void @vec_free(ptr %ssa.t66)
  store %struct.Vec %t29, ptr %ssa.t67
  call void @vec_free(ptr %ssa.t67)
  ret i64 14
merge41:
  %t70 = icmp ne i32 %t65, 1
  br i1 %t70, label %then42, label %merge44
then42:
  store %struct.Vec %wb.24, ptr %ssa.t68
  call void @vec_free(ptr %ssa.t68)
  store %struct.Vec %t29, ptr %ssa.t69
  call void @vec_free(ptr %ssa.t69)
  ret i64 15
merge44:
  store i32 %t26, ptr %t71
  %t73 = getelementptr i8, ptr %t71, i64 4
  store i32 %t31, ptr %t73
  %t74 = getelementptr i8, ptr %t71, i64 8
  store i32 %t54, ptr %t74
  %t75 = load %struct.EvalResult, ptr %t71
  store %struct.EvalResult %t75, ptr %borrow.76
  %t77 = call i32 @compute_display_for_EvalResult(ptr %borrow.76)
  %t78 = icmp ne i32 %t77, 42
  br i1 %t78, label %then45, label %merge47
then45:
  store %struct.Vec %wb.24, ptr %ssa.t70
  call void @vec_free(ptr %ssa.t70)
  store %struct.Vec %t29, ptr %ssa.t71
  call void @vec_free(ptr %ssa.t71)
  ret i64 16
merge47:
  store %struct.Vec %wb.24, ptr %ssa.t72
  call void @vec_free(ptr %ssa.t72)
  store %struct.Vec %t29, ptr %ssa.t73
  call void @vec_free(ptr %ssa.t73)
  %t79 = sext i32 %t77 to i64
  ret i64 %t79
}

define i32 @compute_display_for_EvalResult(ptr %item) {
entry:
  %t0 = call i32 @EvalResult_display_metric(ptr %item)
  ret i32 %t0
}

define i32 @__concrete_get_argc() {
entry:
  %argc = load i32, ptr @__concrete_argc
  ret i32 %argc
}

define ptr @__concrete_get_argv(i32 %idx) {
entry:
  %argv = load ptr, ptr @__concrete_argv
  %idx64 = sext i32 %idx to i64
  %argp = getelementptr ptr, ptr %argv, i64 %idx64
  %arg = load ptr, ptr %argp
  ret ptr %arg
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  store i32 %argc, ptr @__concrete_argc
  store ptr %argv, ptr @__concrete_argv
  %result = call i64 @user_main()
  %fmt = getelementptr [6 x i8], ptr @fmt.main, i32 0, i32 0
  call i32 (ptr, ...) @printf(ptr %fmt, i64 %result)
  ret i32 0
}

define ptr @__concrete_check_oom(ptr %p) {
entry:
  %is_null = icmp eq ptr %p, null
  br i1 %is_null, label %oom, label %ok
oom:
  call void @abort()
  unreachable
ok:
  ret ptr %p
}

define i64 @string_length(ptr %s) {
entry:
  %len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len = load i64, ptr %len_ptr
  ret i64 %len
}

define void @drop_string(ptr %s) {
entry:
  %data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data = load ptr, ptr %data_ptr
  call void @free(ptr %data)
  ret void
}

define %struct.String @string_concat(ptr %a, ptr %b) {
entry:
  %a_data_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 0
  %a_data = load ptr, ptr %a_data_ptr
  %a_len_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 1
  %a_len = load i64, ptr %a_len_ptr
  %b_data_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 0
  %b_data = load ptr, ptr %b_data_ptr
  %b_len_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 1
  %b_len = load i64, ptr %b_len_ptr
  %total_len = add i64 %a_len, %b_len
  %buf.raw = call ptr @malloc(i64 %total_len)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %buf, ptr %a_data, i64 %a_len, i1 false)
  %dst = getelementptr i8, ptr %buf, i64 %a_len
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %b_data, i64 %b_len, i1 false)
  call void @free(ptr %a_data)
  call void @free(ptr %b_data)
  %sc_alloca = alloca %struct.String
  %sc_data_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 0
  store ptr %buf, ptr %sc_data_ptr
  %sc_len_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 1
  store i64 %total_len, ptr %sc_len_ptr
  %sc_cap_ptr = getelementptr %struct.String, ptr %sc_alloca, i32 0, i32 2
  store i64 %total_len, ptr %sc_cap_ptr
  %sc_result = load %struct.String, ptr %sc_alloca
  ret %struct.String %sc_result
}

define %struct.String @string_slice(ptr %s, i64 %start, i64 %end_) {
entry:
  %len_ptr.ss = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len.ss = load i64, ptr %len_ptr.ss
  %s_clamped = call i64 @llvm.smax.i64(i64 %start, i64 0)
  %s_min = call i64 @llvm.smin.i64(i64 %s_clamped, i64 %len.ss)
  %e_clamped = call i64 @llvm.smax.i64(i64 %end_, i64 0)
  %e_min = call i64 @llvm.smin.i64(i64 %e_clamped, i64 %len.ss)
  %e_final = call i64 @llvm.smax.i64(i64 %e_min, i64 %s_min)
  %slice_len = sub i64 %e_final, %s_min
  %slice_buf.raw = call ptr @malloc(i64 %slice_len)
  %slice_buf = call ptr @__concrete_check_oom(ptr %slice_buf.raw)
  %data_ptr.ss = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data.ss = load ptr, ptr %data_ptr.ss
  %src = getelementptr i8, ptr %data.ss, i64 %s_min
  call void @llvm.memcpy.p0.p0.i64(ptr %slice_buf, ptr %src, i64 %slice_len, i1 false)
  %res.ss = alloca %struct.String
  %res_d.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 0
  store ptr %slice_buf, ptr %res_d.ss
  %res_l.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 1
  store i64 %slice_len, ptr %res_l.ss
  %res_c.ss = getelementptr %struct.String, ptr %res.ss, i32 0, i32 2
  store i64 %slice_len, ptr %res_c.ss
  %result.ss = load %struct.String, ptr %res.ss
  ret %struct.String %result.ss
}

define %struct.String @string_substr(ptr %s, i64 %start, i64 %len) {
entry:
  %end_ = add i64 %start, %len
  %result.ssub = call %struct.String @string_slice(ptr %s, i64 %start, i64 %end_)
  ret %struct.String %result.ssub
}

define i64 @string_char_at(ptr %s, i64 %index) {
entry:
  %len_ptr.sca = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %len.sca = load i64, ptr %len_ptr.sca
  %neg = icmp slt i64 %index, 0
  %oob = icmp sge i64 %index, %len.sca
  %bad = or i1 %neg, %oob
  br i1 %bad, label %ret_neg, label %ok_idx
ret_neg:
  ret i64 -1
ok_idx:
  %data_ptr.sca = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %data.sca = load ptr, ptr %data_ptr.sca
  %char_ptr = getelementptr i8, ptr %data.sca, i64 %index
  %byte = load i8, ptr %char_ptr
  %char = zext i8 %byte to i64
  ret i64 %char
}

define i1 @string_contains(ptr %haystack, ptr %needle) {
entry:
  %h_data_ptr = getelementptr %struct.String, ptr %haystack, i32 0, i32 0
  %h_data = load ptr, ptr %h_data_ptr
  %h_len_ptr = getelementptr %struct.String, ptr %haystack, i32 0, i32 1
  %h_len = load i64, ptr %h_len_ptr
  %n_data_ptr = getelementptr %struct.String, ptr %needle, i32 0, i32 0
  %n_data = load ptr, ptr %n_data_ptr
  %n_len_ptr = getelementptr %struct.String, ptr %needle, i32 0, i32 1
  %n_len = load i64, ptr %n_len_ptr
  %n_empty = icmp eq i64 %n_len, 0
  br i1 %n_empty, label %found, label %check_len
check_len:
  %too_long = icmp ugt i64 %n_len, %h_len
  br i1 %too_long, label %not_found, label %loop_start
loop_start:
  %max_i = sub i64 %h_len, %n_len
  br label %loop
loop:
  %i = phi i64 [0, %loop_start], [%i_next, %loop_cont]
  %h_ptr = getelementptr i8, ptr %h_data, i64 %i
  %cmp = call i32 @memcmp(ptr %h_ptr, ptr %n_data, i64 %n_len)
  %match = icmp eq i32 %cmp, 0
  br i1 %match, label %found, label %loop_cont
loop_cont:
  %i_next = add i64 %i, 1
  %done = icmp ugt i64 %i_next, %max_i
  br i1 %done, label %not_found, label %loop
found:
  ret i1 1
not_found:
  ret i1 0
}

define i1 @string_eq(ptr %a, ptr %b) {
entry:
  %a_len_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 1
  %a_len = load i64, ptr %a_len_ptr
  %b_len_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 1
  %b_len = load i64, ptr %b_len_ptr
  %len_eq = icmp eq i64 %a_len, %b_len
  br i1 %len_eq, label %cmp_data, label %not_eq
cmp_data:
  %zero_len = icmp eq i64 %a_len, 0
  br i1 %zero_len, label %eq, label %do_cmp
do_cmp:
  %a_data_ptr = getelementptr %struct.String, ptr %a, i32 0, i32 0
  %a_data = load ptr, ptr %a_data_ptr
  %b_data_ptr = getelementptr %struct.String, ptr %b, i32 0, i32 0
  %b_data = load ptr, ptr %b_data_ptr
  %cmp_res = call i32 @memcmp(ptr %a_data, ptr %b_data, i64 %a_len)
  %eq_data = icmp eq i32 %cmp_res, 0
  br i1 %eq_data, label %eq, label %not_eq
eq:
  ret i1 1
not_eq:
  ret i1 0
}

define %struct.String @int_to_string(i64 %n) {
entry:
  %buf.raw = call ptr @malloc(i64 32)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  %fmt_its = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %buf, i64 32, ptr %fmt_its, i64 %n)
  %wext = sext i32 %written to i64
  %res.its = alloca %struct.String
  %res_d.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 0
  store ptr %buf, ptr %res_d.its
  %res_l.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 1
  store i64 %wext, ptr %res_l.its
  %res_c.its = getelementptr %struct.String, ptr %res.its, i32 0, i32 2
  store i64 32, ptr %res_c.its
  %result.its = load %struct.String, ptr %res.its
  ret %struct.String %result.its
}

define %enum.Result @string_to_int(ptr %s) {
entry:
  %sti_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sti_data = load ptr, ptr %sti_data_ptr
  %sti_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sti_len = load i64, ptr %sti_len_ptr
  %sti_buf_sz = add i64 %sti_len, 1
  %sti_buf.raw = call ptr @malloc(i64 %sti_buf_sz)
  %sti_buf = call ptr @__concrete_check_oom(ptr %sti_buf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %sti_buf, ptr %sti_data, i64 %sti_len, i1 false)
  %sti_null = getelementptr i8, ptr %sti_buf, i64 %sti_len
  store i8 0, ptr %sti_null
  %endptr_alloca = alloca ptr
  %sti_val = call i64 @strtol(ptr %sti_buf, ptr %endptr_alloca, i32 10)
  %endptr = load ptr, ptr %endptr_alloca
  %end_expected = getelementptr i8, ptr %sti_buf, i64 %sti_len
  %valid = icmp eq ptr %endptr, %end_expected
  %empty_input = icmp eq i64 %sti_len, 0
  %not_empty = xor i1 %empty_input, 1
  %final_ok = and i1 %valid, %not_empty
  call void @free(ptr %sti_buf)
  %res.sti = alloca %enum.Result
  br i1 %final_ok, label %sti_ok, label %sti_err
sti_ok:
  store i32 0, ptr %res.sti
  %data_ptr.sti_ok = getelementptr i8, ptr %res.sti, i64 8
  store i64 %sti_val, ptr %data_ptr.sti_ok
  br label %sti_done
sti_err:
  store i32 1, ptr %res.sti
  %data_ptr.sti_err = getelementptr i8, ptr %res.sti, i64 8
  store i64 1, ptr %data_ptr.sti_err
  br label %sti_done
sti_done:
  %result.sti = load %enum.Result, ptr %res.sti
  ret %enum.Result %result.sti
}

define %struct.String @bool_to_string(i1 %b) {
entry:
  br i1 %b, label %bts_true, label %bts_false
bts_true:
  %tbuf.raw = call ptr @malloc(i64 4)
  %tbuf = call ptr @__concrete_check_oom(ptr %tbuf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %tbuf, ptr @.str_true, i64 4, i1 false)
  %tres = alloca %struct.String
  %td = getelementptr %struct.String, ptr %tres, i32 0, i32 0
  store ptr %tbuf, ptr %td
  %tl = getelementptr %struct.String, ptr %tres, i32 0, i32 1
  store i64 4, ptr %tl
  %tc = getelementptr %struct.String, ptr %tres, i32 0, i32 2
  store i64 4, ptr %tc
  %tresult = load %struct.String, ptr %tres
  ret %struct.String %tresult
bts_false:
  %fbuf.raw = call ptr @malloc(i64 5)
  %fbuf = call ptr @__concrete_check_oom(ptr %fbuf.raw)
  call void @llvm.memcpy.p0.p0.i64(ptr %fbuf, ptr @.str_false, i64 5, i1 false)
  %fres = alloca %struct.String
  %fd = getelementptr %struct.String, ptr %fres, i32 0, i32 0
  store ptr %fbuf, ptr %fd
  %fl = getelementptr %struct.String, ptr %fres, i32 0, i32 1
  store i64 5, ptr %fl
  %fc = getelementptr %struct.String, ptr %fres, i32 0, i32 2
  store i64 5, ptr %fc
  %fresult = load %struct.String, ptr %fres
  ret %struct.String %fresult
}

define %struct.String @float_to_string(double %f) {
entry:
  %fbuf.fts.raw = call ptr @malloc(i64 64)
  %fbuf.fts = call ptr @__concrete_check_oom(ptr %fbuf.fts.raw)
  %fmt.fts = getelementptr [3 x i8], ptr @.fmt_f, i64 0, i64 0
  %written.fts = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %fbuf.fts, i64 64, ptr %fmt.fts, double %f)
  %wext.fts = sext i32 %written.fts to i64
  %res.fts = alloca %struct.String
  %res_d.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 0
  store ptr %fbuf.fts, ptr %res_d.fts
  %res_l.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 1
  store i64 %wext.fts, ptr %res_l.fts
  %res_c.fts = getelementptr %struct.String, ptr %res.fts, i32 0, i32 2
  store i64 64, ptr %res_c.fts
  %result.fts = load %struct.String, ptr %res.fts
  ret %struct.String %result.fts
}

define %struct.String @string_trim(ptr %s) {
entry:
  %st_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %st_data = load ptr, ptr %st_data_ptr
  %st_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %st_len = load i64, ptr %st_len_ptr
  br label %trim_left
trim_left:
  %tl_i = phi i64 [0, %entry], [%tl_next, %tl_ws]
  %tl_done = icmp uge i64 %tl_i, %st_len
  br i1 %tl_done, label %trim_result, label %tl_check
tl_check:
  %tl_ptr = getelementptr i8, ptr %st_data, i64 %tl_i
  %tl_ch = load i8, ptr %tl_ptr
  %tl_is_sp = icmp eq i8 %tl_ch, 32
  %tl_is_tab = icmp eq i8 %tl_ch, 9
  %tl_is_nl = icmp eq i8 %tl_ch, 10
  %tl_is_cr = icmp eq i8 %tl_ch, 13
  %tl_w1 = or i1 %tl_is_sp, %tl_is_tab
  %tl_w2 = or i1 %tl_is_nl, %tl_is_cr
  %tl_is_ws = or i1 %tl_w1, %tl_w2
  br i1 %tl_is_ws, label %tl_ws, label %trim_right_init
tl_ws:
  %tl_next = add i64 %tl_i, 1
  br label %trim_left
trim_right_init:
  %tr_start = sub i64 %st_len, 1
  br label %trim_right
trim_right:
  %tr_i = phi i64 [%tr_start, %trim_right_init], [%tr_prev, %tr_ws]
  %tr_done = icmp ult i64 %tr_i, %tl_i
  br i1 %tr_done, label %trim_result, label %tr_check
tr_check:
  %tr_ptr = getelementptr i8, ptr %st_data, i64 %tr_i
  %tr_ch = load i8, ptr %tr_ptr
  %tr_is_sp = icmp eq i8 %tr_ch, 32
  %tr_is_tab = icmp eq i8 %tr_ch, 9
  %tr_is_nl = icmp eq i8 %tr_ch, 10
  %tr_is_cr = icmp eq i8 %tr_ch, 13
  %tr_w1 = or i1 %tr_is_sp, %tr_is_tab
  %tr_w2 = or i1 %tr_is_nl, %tr_is_cr
  %tr_is_ws = or i1 %tr_w1, %tr_w2
  br i1 %tr_is_ws, label %tr_ws, label %trim_result
tr_ws:
  %tr_prev = sub i64 %tr_i, 1
  br label %trim_right
trim_result:
  %tr_left = phi i64 [%tl_i, %trim_left], [%tl_i, %trim_right], [%tl_i, %tr_check]
  %tr_right_raw = phi i64 [0, %trim_left], [%tl_i, %trim_right], [%tr_i, %tr_check]
  %tr_right = add i64 %tr_right_raw, 1
  %tr_empty = icmp uge i64 %tr_left, %tr_right
  br i1 %tr_empty, label %trim_empty, label %trim_copy
trim_empty:
  %te_buf.raw = call ptr @malloc(i64 1)
  %te_buf = call ptr @__concrete_check_oom(ptr %te_buf.raw)
  %te_res = alloca %struct.String
  %te_d = getelementptr %struct.String, ptr %te_res, i32 0, i32 0
  store ptr %te_buf, ptr %te_d
  %te_l = getelementptr %struct.String, ptr %te_res, i32 0, i32 1
  store i64 0, ptr %te_l
  %te_c = getelementptr %struct.String, ptr %te_res, i32 0, i32 2
  store i64 1, ptr %te_c
  %te_result = load %struct.String, ptr %te_res
  ret %struct.String %te_result
trim_copy:
  %tc_len = sub i64 %tr_right, %tr_left
  %tc_buf.raw = call ptr @malloc(i64 %tc_len)
  %tc_buf = call ptr @__concrete_check_oom(ptr %tc_buf.raw)
  %tc_src = getelementptr i8, ptr %st_data, i64 %tr_left
  call void @llvm.memcpy.p0.p0.i64(ptr %tc_buf, ptr %tc_src, i64 %tc_len, i1 false)
  %tc_res = alloca %struct.String
  %tc_d = getelementptr %struct.String, ptr %tc_res, i32 0, i32 0
  store ptr %tc_buf, ptr %tc_d
  %tc_l = getelementptr %struct.String, ptr %tc_res, i32 0, i32 1
  store i64 %tc_len, ptr %tc_l
  %tc_c = getelementptr %struct.String, ptr %tc_res, i32 0, i32 2
  store i64 %tc_len, ptr %tc_c
  %tc_result = load %struct.String, ptr %tc_res
  ret %struct.String %tc_result
}

define void @print_string(ptr %s) {
entry:
  %ps_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %ps_data = load ptr, ptr %ps_data_ptr
  %ps_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %ps_len = load i64, ptr %ps_len_ptr
  %ps_fmt = getelementptr [5 x i8], ptr @.fmt_str, i64 0, i64 0
  %ps_len32 = trunc i64 %ps_len to i32
  %ps_written = call i32 (ptr, ...) @printf(ptr %ps_fmt, i32 %ps_len32, ptr %ps_data)
  ret void
}

define void @print_int(i64 %n) {
entry:
  %pi_fmt = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %pi_written = call i32 (ptr, ...) @printf(ptr %pi_fmt, i64 %n)
  ret void
}

define void @print_char(i64 %c) {
entry:
  %pc_int = trunc i64 %c to i32
  %pc_wr = call i32 @putchar(i32 %pc_int)
  ret void
}

define void @print_bool(i1 %b) {
entry:
  %is_true = icmp eq i1 %b, 1
  br i1 %is_true, label %print_true, label %print_false
print_true:
  %true_ptr = getelementptr [5 x i8], ptr @.str_true, i64 0, i64 0
  %tw = call i32 (ptr, ...) @printf(ptr %true_ptr)
  ret void
print_false:
  %false_ptr = getelementptr [6 x i8], ptr @.str_false, i64 0, i64 0
  %fw = call i32 (ptr, ...) @printf(ptr %false_ptr)
  ret void
}

define void @string_push_char(ptr %s, i64 %c) {
entry:
  %spc_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %spc_len = load i64, ptr %spc_len_ptr
  %spc_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %spc_cap = load i64, ptr %spc_cap_ptr
  %spc_full = icmp eq i64 %spc_len, %spc_cap
  br i1 %spc_full, label %spc_grow, label %spc_store
spc_grow:
  %spc_newcap = mul i64 %spc_cap, 2
  %spc_nc_clamped = call i64 @llvm.smax.i64(i64 %spc_newcap, i64 8)
  %spc_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %spc_data = load ptr, ptr %spc_data_ptr
  %spc_newbuf.raw = call ptr @realloc(ptr %spc_data, i64 %spc_nc_clamped)
  %spc_newbuf = call ptr @__concrete_check_oom(ptr %spc_newbuf.raw)
  store ptr %spc_newbuf, ptr %spc_data_ptr
  store i64 %spc_nc_clamped, ptr %spc_cap_ptr
  br label %spc_store
spc_store:
  %spc_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %spc_data2 = load ptr, ptr %spc_dp2
  %spc_slot = getelementptr i8, ptr %spc_data2, i64 %spc_len
  %spc_byte = trunc i64 %c to i8
  store i8 %spc_byte, ptr %spc_slot
  %spc_newlen = add i64 %spc_len, 1
  store i64 %spc_newlen, ptr %spc_len_ptr
  ret void
}

define void @string_append(ptr %s, ptr %other) {
entry:
  %sa_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sa_len = load i64, ptr %sa_len_ptr
  %sa_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sa_cap = load i64, ptr %sa_cap_ptr
  %sa_olen_ptr = getelementptr %struct.String, ptr %other, i32 0, i32 1
  %sa_olen = load i64, ptr %sa_olen_ptr
  %sa_needed = add i64 %sa_len, %sa_olen
  %sa_need_grow = icmp ugt i64 %sa_needed, %sa_cap
  br i1 %sa_need_grow, label %sa_grow, label %sa_copy
sa_grow:
  %sa_dblcap = mul i64 %sa_cap, 2
  %sa_newcap = call i64 @llvm.smax.i64(i64 %sa_dblcap, i64 %sa_needed)
  %sa_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sa_data = load ptr, ptr %sa_data_ptr
  %sa_newbuf.raw = call ptr @realloc(ptr %sa_data, i64 %sa_newcap)
  %sa_newbuf = call ptr @__concrete_check_oom(ptr %sa_newbuf.raw)
  store ptr %sa_newbuf, ptr %sa_data_ptr
  store i64 %sa_newcap, ptr %sa_cap_ptr
  br label %sa_copy
sa_copy:
  %sa_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sa_data2 = load ptr, ptr %sa_dp2
  %sa_dst = getelementptr i8, ptr %sa_data2, i64 %sa_len
  %sa_odata_ptr = getelementptr %struct.String, ptr %other, i32 0, i32 0
  %sa_odata = load ptr, ptr %sa_odata_ptr
  call void @llvm.memcpy.p0.p0.i64(ptr %sa_dst, ptr %sa_odata, i64 %sa_olen, i1 false)
  store i64 %sa_needed, ptr %sa_len_ptr
  ret void
}

define void @string_append_int(ptr %s, i64 %n) {
entry:
  %sai_buf = alloca [32 x i8]
  %sai_fmt = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0
  %sai_written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %sai_buf, i64 32, ptr %sai_fmt, i64 %n)
  %sai_len = sext i32 %sai_written to i64
  %sai_slen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sai_slen = load i64, ptr %sai_slen_ptr
  %sai_scap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sai_scap = load i64, ptr %sai_scap_ptr
  %sai_needed = add i64 %sai_slen, %sai_len
  %sai_need_grow = icmp ugt i64 %sai_needed, %sai_scap
  br i1 %sai_need_grow, label %sai_grow, label %sai_copy
sai_grow:
  %sai_dblcap = mul i64 %sai_scap, 2
  %sai_newcap = call i64 @llvm.smax.i64(i64 %sai_dblcap, i64 %sai_needed)
  %sai_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sai_data = load ptr, ptr %sai_data_ptr
  %sai_newbuf.raw = call ptr @realloc(ptr %sai_data, i64 %sai_newcap)
  %sai_newbuf = call ptr @__concrete_check_oom(ptr %sai_newbuf.raw)
  store ptr %sai_newbuf, ptr %sai_data_ptr
  store i64 %sai_newcap, ptr %sai_scap_ptr
  br label %sai_copy
sai_copy:
  %sai_dp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sai_data2 = load ptr, ptr %sai_dp2
  %sai_dst = getelementptr i8, ptr %sai_data2, i64 %sai_slen
  call void @llvm.memcpy.p0.p0.i64(ptr %sai_dst, ptr %sai_buf, i64 %sai_len, i1 false)
  store i64 %sai_needed, ptr %sai_slen_ptr
  ret void
}

define void @string_append_bool(ptr %s, i1 %b) {
entry:
  br i1 %b, label %sab_true, label %sab_false
sab_true:
  %sab_tlen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sab_tlen = load i64, ptr %sab_tlen_ptr
  %sab_tcap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sab_tcap = load i64, ptr %sab_tcap_ptr
  %sab_tneeded = add i64 %sab_tlen, 4
  %sab_tneed_grow = icmp ugt i64 %sab_tneeded, %sab_tcap
  br i1 %sab_tneed_grow, label %sab_tgrow, label %sab_tcopy
sab_tgrow:
  %sab_tdblcap = mul i64 %sab_tcap, 2
  %sab_tnewcap = call i64 @llvm.smax.i64(i64 %sab_tdblcap, i64 %sab_tneeded)
  %sab_tdata_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_tdata = load ptr, ptr %sab_tdata_ptr
  %sab_tnewbuf.raw = call ptr @realloc(ptr %sab_tdata, i64 %sab_tnewcap)
  %sab_tnewbuf = call ptr @__concrete_check_oom(ptr %sab_tnewbuf.raw)
  store ptr %sab_tnewbuf, ptr %sab_tdata_ptr
  store i64 %sab_tnewcap, ptr %sab_tcap_ptr
  br label %sab_tcopy
sab_tcopy:
  %sab_tdp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_tdata2 = load ptr, ptr %sab_tdp2
  %sab_tdst = getelementptr i8, ptr %sab_tdata2, i64 %sab_tlen
  call void @llvm.memcpy.p0.p0.i64(ptr %sab_tdst, ptr @.str_true, i64 4, i1 false)
  store i64 %sab_tneeded, ptr %sab_tlen_ptr
  ret void
sab_false:
  %sab_flen_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sab_flen = load i64, ptr %sab_flen_ptr
  %sab_fcap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sab_fcap = load i64, ptr %sab_fcap_ptr
  %sab_fneeded = add i64 %sab_flen, 5
  %sab_fneed_grow = icmp ugt i64 %sab_fneeded, %sab_fcap
  br i1 %sab_fneed_grow, label %sab_fgrow, label %sab_fcopy
sab_fgrow:
  %sab_fdblcap = mul i64 %sab_fcap, 2
  %sab_fnewcap = call i64 @llvm.smax.i64(i64 %sab_fdblcap, i64 %sab_fneeded)
  %sab_fdata_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_fdata = load ptr, ptr %sab_fdata_ptr
  %sab_fnewbuf.raw = call ptr @realloc(ptr %sab_fdata, i64 %sab_fnewcap)
  %sab_fnewbuf = call ptr @__concrete_check_oom(ptr %sab_fnewbuf.raw)
  store ptr %sab_fnewbuf, ptr %sab_fdata_ptr
  store i64 %sab_fnewcap, ptr %sab_fcap_ptr
  br label %sab_fcopy
sab_fcopy:
  %sab_fdp2 = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sab_fdata2 = load ptr, ptr %sab_fdp2
  %sab_fdst = getelementptr i8, ptr %sab_fdata2, i64 %sab_flen
  call void @llvm.memcpy.p0.p0.i64(ptr %sab_fdst, ptr @.str_false, i64 5, i1 false)
  store i64 %sab_fneeded, ptr %sab_flen_ptr
  ret void
}

define void @string_reserve(ptr %s, i64 %extra) {
entry:
  %sr_cap_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 2
  %sr_cap = load i64, ptr %sr_cap_ptr
  %sr_len_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 1
  %sr_len = load i64, ptr %sr_len_ptr
  %sr_needed = add i64 %sr_len, %extra
  %sr_need_grow = icmp ugt i64 %sr_needed, %sr_cap
  br i1 %sr_need_grow, label %sr_grow, label %sr_done
sr_grow:
  %sr_data_ptr = getelementptr %struct.String, ptr %s, i32 0, i32 0
  %sr_data = load ptr, ptr %sr_data_ptr
  %sr_newbuf.raw = call ptr @realloc(ptr %sr_data, i64 %sr_needed)
  %sr_newbuf = call ptr @__concrete_check_oom(ptr %sr_newbuf.raw)
  store ptr %sr_newbuf, ptr %sr_data_ptr
  store i64 %sr_needed, ptr %sr_cap_ptr
  br label %sr_done
sr_done:
  ret void
}

define i64 @clock_monotonic_ns() {
entry:
  %ts = alloca [2 x i64]
  %clk_ret = call i32 @clock_gettime(i32 6, ptr %ts)
  %sec_ptr = getelementptr i64, ptr %ts, i64 0
  %sec = load i64, ptr %sec_ptr
  %nsec_ptr = getelementptr i64, ptr %ts, i64 1
  %nsec = load i64, ptr %nsec_ptr
  %sec_ns = mul i64 %sec, 1000000000
  %total = add i64 %sec_ns, %nsec
  ret i64 %total
}

define i64 @vec_len(ptr %vec) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  ret i64 %len
}

define void @vec_free(ptr %vec) {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  call void @free(ptr %data)
  ret void
}

define %struct.Vec @vec_new_4() alwaysinline {
entry:
  %buf.raw = call ptr @malloc(i64 32)
  %buf = call ptr @__concrete_check_oom(ptr %buf.raw)
  %v = alloca %struct.Vec
  %bp = getelementptr %struct.Vec, ptr %v, i32 0, i32 0
  store ptr %buf, ptr %bp
  %lp = getelementptr %struct.Vec, ptr %v, i32 0, i32 1
  store i64 0, ptr %lp
  %cp = getelementptr %struct.Vec, ptr %v, i32 0, i32 2
  store i64 8, ptr %cp
  %r = load %struct.Vec, ptr %v
  ret %struct.Vec %r
}

define void @vec_push_4(ptr %vec, ptr %val) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  %cp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 2
  %cap = load i64, ptr %cp
  %full = icmp eq i64 %len, %cap
  br i1 %full, label %grow, label %store
grow:
  %newcap = mul i64 %cap, 2
  %newbytes = mul i64 %newcap, 4
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %newbuf.raw = call ptr @realloc(ptr %data, i64 %newbytes)
  %newbuf = call ptr @__concrete_check_oom(ptr %newbuf.raw)
  store ptr %newbuf, ptr %dp
  store i64 %newcap, ptr %cp
  br label %store
store:
  %dp2 = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data2 = load ptr, ptr %dp2
  %offset = mul i64 %len, 4
  %slot = getelementptr i8, ptr %data2, i64 %offset
  call void @llvm.memcpy.p0.p0.i64(ptr %slot, ptr %val, i64 4, i1 false)
  %newlen = add i64 %len, 1
  store i64 %newlen, ptr %lp
  ret void
}

define ptr @vec_get_4(ptr %vec, i64 %idx) alwaysinline {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %offset = mul i64 %idx, 4
  %slot = getelementptr i8, ptr %data, i64 %offset
  ret ptr %slot
}

define void @vec_set_4(ptr %vec, i64 %idx, ptr %val) alwaysinline {
entry:
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %offset = mul i64 %idx, 4
  %slot = getelementptr i8, ptr %data, i64 %offset
  call void @llvm.memcpy.p0.p0.i64(ptr %slot, ptr %val, i64 4, i1 false)
  ret void
}

define %enum.Option @vec_pop_4_4(ptr %vec) alwaysinline {
entry:
  %lp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 1
  %len = load i64, ptr %lp
  %empty = icmp eq i64 %len, 0
  br i1 %empty, label %none, label %some
some:
  %newlen = sub i64 %len, 1
  store i64 %newlen, ptr %lp
  %dp = getelementptr %struct.Vec, ptr %vec, i32 0, i32 0
  %data = load ptr, ptr %dp
  %offset = mul i64 %newlen, 4
  %slot = getelementptr i8, ptr %data, i64 %offset
  %res = alloca %enum.Option
  call void @memset(ptr %res, i32 0, i64 8)
  store i32 0, ptr %res
  %payload = getelementptr i8, ptr %res, i64 4
  call void @llvm.memcpy.p0.p0.i64(ptr %payload, ptr %slot, i64 4, i1 false)
  %r = load %enum.Option, ptr %res
  ret %enum.Option %r
none:
  %res2 = alloca %enum.Option
  call void @memset(ptr %res2, i32 0, i64 8)
  store i32 1, ptr %res2
  %r2 = load %enum.Option, ptr %res2
  ret %enum.Option %r2
}

