[package]
name = "loc"
version = "0.1.0"
edition = "2024"

[dependencies]
tokei = "12.1.2"
serde = "1.0.215"
serde_json = "1.0.133"
clap = { version = "4.5.35", features = ["derive"] }
clap_complete = "4.5.17"
colored = "3.0.0"
spinoff = "0.8.0"
prettytable = "0.10.0"
